%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(combination_set2).
-export([combination/0]).

combination() ->
[ 
	{combination,513,
	             [{1,{elem, 6},null,null,null,null,9,null,null,3,0},
	              {2,{elem, 6},{elem, 6},null,null,null,10,null,null,3,0}]}, 
	{combination,514,[{1,{elem, 1},null,null,null,null,9,10,null,2,0}]}, 
	{combination,515,[{1,{elem, 6},null,null,null,null,9,null,null,2,0}]}, 
	{combination,516,[{1,{elem, 6},null,null,null,null,9,null,null,2,0}]}, 
	{combination,517,
	             [{1,{elem, 6},null,null,null,null,9,null,null,4,0},
	              {2,{elem, 4},{elem, 6},null,null,null,11,null,null,6,0}]}, 
	{combination,518,
	             [{1,{elem, 6},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 6},{elem, 6},null,null,null,11,null,4,4,0}]}, 
	{combination,519,[{1,{elem, 2},null,null,null,null,9,null,null,2,0}]}, 
	{combination,520,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},null,null,null,null,10,null,null,3,0}]}, 
	{combination,521,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 4},null,null,null,null,10,null,null,3,0}]}, 
	{combination,522,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 3},null,null,null,null,10,null,4,3,0},
	              {3,{type, "Dragon"},null,null,null,null,11,null,null,4,0}]}, 
	{combination,523,[{1,{elem, 6},null,null,null,null,7,null,null,2,0}]},
   {combination,524,[{1,{type, 7},{elem, 7},null,null,null,10,null,null,3,0}]},
	{combination,525,
	             [{1,{elem, 6},null,null,null,null,8,null,null,2,0},
	              {2,{type, "Dragon"},null,null,null,null,9,null,null,2,0}]}, 
	{combination,526,
	             [{1,{elem, 2},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 6},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,527,
	             [{1,{elem, 2},null,null,null,null,6,null,null,1,0},
	              {2,{elem, 3},null,null,null,null,7,null,5,1,0}]}, 
	{combination,528,
	             [{1,{elem, 1},null,null,null,null,10,11,null,3,0},
	              {2,{elem, 1},{elem, 1},null,null,null,11,12,null,4,0}]}, 
	{combination,529,
	             [{1,{elem, 1},null,null,null,null,null,8,null,2,0},
	              {2,{elem, 1},{elem, 1},null,null,null,null,9,null,2,0}]}, 
	{combination,530,[{1,{elem, 6},null,null,null,null,7,null,null,1,0}]}, 
	{combination,531,[{1,{elem, 1},null,null,null,null,null,12,null,1,0}]}, 
	{combination,532,
	             [{1,{elem, 1},null,null,null,null,null,10,null,1,0},
	              {2,{elem, 5},null,null,null,null,8,null,null,2,0}]}, 
	{combination,533,[{1,{type, 7},{elem, 7},null,null,null,10,null,null,3,0}]},
	{combination,534,[{1,{elem, 6},null,null,null,null,9,null,null,2,0}]}, 
	{combination,535,[{1,{elem, 5},null,null,null,null,7,null,null,1,0}]}, 
	{combination,536,
	             [{1,{elem, 1},null,null,null,null,8,8,null,2,0},
	              {2,{elem, 1},{type, "Monster"},null,null,null,10,9,3,3,0}]}, 
	{combination,537,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},null,null,null,null,9,null,null,2,0}]}, 
	{combination,538,
	             [{1,{elem, 1},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 1},{elem, 1},null,null,null,8,null,null,2,0}]}, 
	{combination,539,
	             [{1,{elem, 6},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 1},{elem, 6},null,null,null,9,9,null,2,0}]}, 
	{combination,540,
	             [{1,{elem, 1},null,null,null,null,null,9,null,2,0},
	              {2,{elem, 1},{elem, 1},null,null,null,null,11,null,3,0}]}, 
	{combination,541,[{1,{elem, 1},null,null,null,null,8,9,null,2,0}]}, 
	{combination,542,
	             [{1,{elem, 2},null,null,null,null,6,null,null,1,0},
	              {2,{elem, 1},null,null,null,null,7,null,null,1,0}]}, 
	{combination,543,
	             [{1,{elem, 4},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 4},{elem, 4},null,null,null,12,null,null,3,0}]}, 
	{combination,544,
	             [{1,{elem, 4},null,null,null,null,7,null,null,3,0},
	              {2,{elem, 4},{elem, 4},null,null,null,9,null,null,4,0}]}, 
	{combination,545,
	             [{1,{elem, 4},null,null,null,null,11,null,null,3,0},
					  	{2,{elem, 4},{elem, 4},null,null,null,12,null,null,3,0},
						{3,{type, "Dragon"},null,null,null,null,10,null,null,4,2}]}, 
	{combination,546,
	             [{1,{elem, 4},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,5,1}]}, 
	{combination,547,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},null,null,null,null,10,null,null,3,0}]}, 
	{combination,548,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},null,null,null,null,10,null,null,3,0}]}, 
	{combination,549,[{1,{type, "Dragon"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,550,
	             [{1,{type, "Dragon"},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 4},null,null,null,null,10,null,null,3,0}]},
	{combination,551,
	             [{1,{type, "Knight"},null,null,null,null,9,null,null,3,0},
	              {2,{elem, 4},{elem, 4},null,null,null,9,null,null,3,0}]},				  
	{combination,552,[{1,{elem, 4},{elem, 4},null,null,null,11,null,null,4,0}]}, 
	{combination,553,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 4},{elem, 5},null,null,null,10,null,null,3,0}]}, 
	{combination,554,
	             [{1,{elem, 4},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,3,0}]}, 
	{combination,555,
	             [{1,{elem, 4},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 5},null,null,null,null,8,null,null,2,0}]}, 
	{combination,556,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},null,null,null,null,8,null,null,2,0}]}, 
	{combination,557,
	             [{1,{elem, 4},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,3,0}]}, 
	{combination,558,[{1,{type, 7},{elem, 7},null,null,null,10,null,null,3,0}]},
	{combination,559,
	             [{1,{elem, 2},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,5,1}]}, 
	{combination,560,
	             [{1,{elem, 2},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 2},{elem, 2},null,null,null,12,null,null,3,0}]}, 
	{combination,561,[{1,{elem, 2},null,null,null,null,10,null,null,3,0}]}, 
	{combination,562,
	             [{1,{elem, 2},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},null,null,null,null,10,null,null,2,0}]}, 
	{combination,563,[{1,{elem, 2},{elem, 2},null,null,null,10,13,null,3,0}]}, 
	{combination,564,
	             [{1,{elem, 2},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,565,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},{elem, 2},null,null,null,11,null,null,4,0}]},
   {combination,566,[{1,{type, 7},{elem, 7},null,null,null,10,null,null,3,0}]},
	{combination,567,
	             [{1,{elem, 5},null,null,null,null,8,null,null,1,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,568,
	             [{1,{elem, 1},null,null,null,null,7,9,null,2,0},
	              {2,{elem, 1},{elem, 2},null,null,null,10,10,null,3,0}]}, 
	{combination,569,
	             [{1,{elem, 2},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 2},{elem, 2},null,null,null,9,null,null,2,0}]}, 
	{combination,570,
	             [{1,{elem, 2},null,null,null,null,8,null,null,1,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,2,0}]}, 
	{combination,571,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 2},null,null,null,null,8,null,null,2,0}]}, 
	{combination,572,
	             [{1,{elem, 2},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,573,
	             [{1,{elem, 2},null,null,null,null,8,null,null,2,0},
	              {2,{type, "Monster"},null,null,null,null,9,null,null,2,0}]}, 
	{combination,574,
	             [{1,{elem, 4},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 3},{elem, 4},null,null,null,12,null,null,3,0}]}, 
	{combination,575,
	             [{1,{elem, 3},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 3},{elem, 3},null,null,null,12,null,null,4,0}]}, 
	{combination,576,[{1,{elem, 3},{elem, 5},null,null,null,10,null,null,3,0}]}, 
	{combination,577,
	             [{1,{type, "Beast"},null,null,null,null,10,null,null,3,0},
	              {2,{type, "Dragon"},null,null,null,null,11,null,null,3,0}]}, 
	{combination,578,
						[
							{1,{elem, 3},null,null,null,null,9,null,null,2,0}, 
							{2,{type, "Beast"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,579,
	             [{1,{elem, 3},null,null,null,null,6,null,null,2,0},
	              {2,{elem, 6},null,null,null,null,7,null,null,2,0}]}, 
	{combination,580,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 3},{elem, 5},null,null,null,10,null,null,3,0}]}, 
	{combination,581,[{1,{elem, 3},null,null,null,null,9,null,null,2,0}]},
   {combination,582,[{1,{type, 7},{elem, 7},null,null,null,10,null,null,3,0}]},
	{combination,583,
	             [{1,{elem, 3},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 5},null,null,null,null,7,null,null,1,0}]}, 
	{combination,584,
	             [{1,{elem, 3},null,null,null,null,10,null,null,3,0}]}, 
	{combination,585,[{1,{elem, 3},null,null,null,null,9,null,null,2,0}]}, 
	{combination,586,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},null,null,null,null,9,null,null,2,0}]}, 
	{combination,587,
	             [{1,{type, "Monster"},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},{elem, 3},null,null,null,10,null,null,2,0}]}, 
	{combination,588,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{type, "Monster"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,589,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{type, "Monster"},{elem, 3},null,null,null,11,null,null,3,0}]}, 
	{combination,590,
	             [{1,{elem, 5},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 5},{elem, 5},null,null,null,12,null,null,4,0}]},
   {combination,591,[{1,{type, 7},{elem, 7},null,null,null,10,null,null,3,0}]},
	{combination,592,[{1,{elem, 5},{elem, 5},null,null,null,11,null,null,3,0}]}, 
	{combination,593,[{1,{elem, 6},null,null,null,null,11,null,null,3,0}]}, 
	{combination,594,
	             [{1,{elem, 5},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 5},{elem, 5},null,null,null,12,null,null,4,0}]}, 
	{combination,595,
	             [{1,{elem, 5},{elem, 5},null,null,null,11,null,null,3,0},
	              {2,{elem, 4},null,null,null,null,7,null,null,4,3}]}, 
	{combination,596,
	             [{1,{elem, 5},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,3,0}]}, 
	{combination,597,
	             [{1,{naming, "Viper"},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,10,null,null,3,0}]}, 
	{combination,598,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,10,null,null,3,0}]}, 
	{combination,599,
	             [{1,{elem, 5},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 4},null,null,null,null,9,null,null,2,0}]}, 
	{combination,600,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{type, "Dragon"},{type, "Dragon"},null,null,null,11,null,null,3,0}]}, 
	{combination,601,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 5},{elem, 5},null,null,null,10,null,null,3,0}]}, 
	{combination,602,[{1,{elem, 5},null,null,null,null,7,null,null,1,0}]},
   {combination,603,[{1,{type, 7},{elem, 7},null,null,null,10,null,null,3,0}]},
	{combination,604,[{1,{elem, 5},null,null,null,null,9,null,null,2,0}]}, 
	{combination,605,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},{elem, 4},null,null,null,10,null,null,3,0}]},
	{combination,621,
	             [{1,{elem, 6},null,null,null,null,8,null,null,1,0},
	              {2,{elem, 6},{elem, 6},null,null,null,10,null,null,3,0}]},
	{combination,622,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,3,0}]},
	{combination,623,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,9,null,null,4,1}]}
].
