%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(combination_set1).
-export([combination/0]).
combination() ->
[ 
	{combination,257,
	             [{1,{elem, 6},{elem, 6},null,null,null,12,null,null,4,0},
	              {2,{elem, 3},null,null,null,null,9,null,null,5,1}]}, 
	{combination,258,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},{elem, 6},null,null,null,11,null,null,3,0}]}, 
	{combination,259,
	             [{1,{elem, 6},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 6},{elem, 6},null,null,null,11,null,null,3,0}]}, 
	{combination,260,
	             [{1,{elem, 6},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 6},{elem, 6},null,null,null,10,null,null,3,0}]}, 
	{combination,261,[{1,{elem, 6},null,null,null,null,9,null,null,2,0}]}, 
	{combination,262,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},null,null,null,null,10,null,null,3,0}]}, 
	{combination,263,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{naming, "Martin"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,264,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 1},null,null,null,null,null,11,null,1,0}]}, 
	{combination,265,
	             [{1,{elem, 6},null,null,null,null,7,null,null,1,0},
	              {2,{type, "Beast"},null,null,null,null,9,null,null,2,0}]}, 
	{combination,266,[{1,{type, "Divine"},null,null,null,null,9,null,null,2,0}]}, 
	{combination,267,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},null,null,null,null,9,null,null,2,0}]}, 
	{combination,268,
	             [{1,{elem, 2},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 3},null,null,null,null,9,null,4,2,0}]}, 
	{combination,269,[{1,{elem, 6},null,null,null,null,9,null,null,2,0}]}, 
	{combination,270,
	             [{1,{elem, 6},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 1},null,null,null,null,null,8,null,1,0}]}, 
	{combination,271,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},{elem, 6},null,null,null,11,null,null,3,0}]}, 
	{combination,272,
	             [{1,{elem, 1},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 1},{elem, 1},null,null,null,11,13,null,4,0}]}, 
	{combination,273,
	             [{1,{elem, 1},null,null,null,null,10,13,null,3,0},
	              {2,{elem, 1},{elem, 1},null,null,null,10,null,null,5,1}]}, 
	{combination,274,[{1,{elem, 5},null,null,null,null,8,null,null,2,0}]}, 
	{combination,275,
	             [{1,{elem, 1},null,null,null,null,9,null,null,3,0},
	              {2,{elem, 1},{elem, 1},null,null,null,11,null,null,4,0}]}, 
	{combination,276,
	             [{1,{elem, 6},null,null,null,null,10,13,null,3,0},
	              {2,{elem, 1},{elem, 1},null,null,null,10,null,null,5,1}]}, 
	{combination,277,
	             [{1,{elem, 1},null,null,null,null,8,8,null,2,0},
	              {2,{elem, 1},{elem, 1},null,null,null,10,10,null,3,0}]}, 
	{combination,278,
	             [{1,{elem, 1},null,null,null,null,8,null,null,3,0},
	              {2,{elem, 1},{elem, 1},null,null,null,10,null,null,4,0}]}, 
	{combination,279,
	             [{1,{elem, 1},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 5},null,null,null,null,10,null,null,3,0}]}, 
	{combination,280,
	             [{1,{elem, 1},null,null,null,null,8,10,null,2,0},
	              {2,{elem, 1},{elem, 1},null,null,null,10,11,null,3,0}]}, 
	{combination,281,
	             [{1,{elem, 1},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 1},{elem, 1},null,null,null,11,null,null,4,0}]}, 
	{combination,282,
	             [{1,{elem, 1},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 1},{elem, 6},null,null,null,10,11,null,3,0}]}, 
	{combination,283,
	             [{1,{elem, 1},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 1},{elem, 1},null,null,null,10,null,null,3,0}]}, 
	{combination,284,
	             [{1,{elem, 1},null,null,null,null,null,9,null,1,0},
	              {2,{elem, 1},{elem, 1},null,null,null,9,10,null,2,0}]}, 
	{combination,285,
	             [{1,{elem, 6},null,null,null,null,9,null,null,3,0},
	              {2,{elem, 1},null,null,null,null,null,10,null,1,0}]}, 
	{combination,286,[{1,{elem, 1},null,null,null,null,8,null,null,2,0}]}, 
	{combination,287,
	             [{1,{elem, 4},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 4},{elem, 4},null,null,null,12,null,null,3,0}]}, 
	{combination,288,
	             [{1,{elem, 4},null,null,null,null,7,null,null,2,0},
	              {2,{elem, 4},{elem, 4},null,null,null,9,null,null,3,0}]}, 
	{combination,289,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 4},{elem, 4},null,null,null,11,null,null,3,0}]}, 
	{combination,290,
	             [{1,{elem, 4},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 4},{elem, 4},null,null,null,9,null,null,2,0}]}, 
	{combination,291,
	             [{1,{elem, 4},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,3,0}]}, 
	{combination,292,
	             [{1,{elem, 4},null,null,null,null,8,null,null,3,0},
	              {2,{elem, 4},{elem, 4},null,null,null,9,null,null,3,0}]}, 
	{combination,293,
	             [{1,{elem, 4},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,3,0}]}, 
	{combination,294,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{type, "Evil"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,295,
	             [{1,{elem, 2},{elem, 3},null,null,null,12,null,5,3,0},
	              {2,{elem, 4},{elem, 1},null,null,null,12,12,null,4,0}]}, 
	{combination,296,
	             [{1,{elem, 4},null,null,null,null,9,null,null,3,0},
	              {2,{elem, 4},{elem, 4},null,null,null,10,null,null,3,0}]}, 
	{combination,297,[{1,{elem, 4},null,null,null,null,9,null,null,2,0}]}, 
	{combination,298,[{1,{elem, 4},null,null,null,null,8,null,null,2,0}]}, 
	{combination,299,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 4},null,null,null,null,9,null,null,2,0}]}, 
	{combination,300,
	             [{1,{elem, 4},null,null,null,null,7,null,null,2,0},
	              {2,{name, "Zalom Fortress Archer"},null,null,null,null,9,null,null,2,0}]}, 
	{combination,301,
	             [{1,{elem, 4},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 4},{elem, 7},null,null,null,9,null,null,2,0}]}, 
	{combination,302,
	             [{1,{elem, 2},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 2},{elem, 2},null,null,null,12,null,null,3,0}]}, 
	{combination,303,
	             [{1,{elem, 2},null,null,null,null,6,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,8,null,null,3,0}]}, 
	{combination,304,
	             [{1,{elem, 2},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,5,1}]}, 
	{combination,305,
	             [{1,{elem, 2},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,8,null,null,4,1}]}, 
	{combination,306,
	             [{1,{elem, 2},null,null,null,null,9,8,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,9,null,3,0}]}, 
	{combination,307,
	             [{1,{elem, 2},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,308,
	             [{1,{elem, 2},null,null,null,null,6,null,null,1,0},
	              {2,{elem, 2},{elem, 2},null,null,null,8,null,null,1,0}]}, 
	{combination,309,[{1,{elem, 6},null,null,null,null,9,null,null,2,0}]}, 
	{combination,310,
	             [{1,{elem, 2},null,null,null,null,8,null,null,2,0},
	              {2,{type, "Machine"},null,null,null,null,8,null,null,2,0}]}, 
	{combination,311,[{1,{elem, 3},null,null,null,null,9,null,null,2,0}]}, 
	{combination,312,
	             [{1,{elem, 3},null,null,null,null,7,null,5,2,0},
	              {2,{elem, 1},{elem, 1},null,null,null,8,10,null,2,0}]}, 
	{combination,313,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 2},null,null,null,null,9,null,null,2,0}]}, 
	{combination,314,
	             [{1,{elem, 2},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,315,
	             [{1,{elem, 2},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,316,
	             [{1,{elem, 2},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,null,null,3,0}]}, 
	{combination,317,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 3},{elem, 3},null,null,null,10,null,null,3,0}]}, 
	{combination,318,
	             [{1,{elem, 3},null,null,null,null,10,null,null,3,0},
	              {2,{elem, 3},{elem, 3},null,null,null,9,null,null,5,1}]}, 
	{combination,319,
	             [{1,{elem, 3},null,null,null,null,11,null,null,3,0},
	              {2,{elem, 3},{elem, 6},null,null,null,12,null,null,4,0}]}, 
	{combination,320,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{type, "Monster"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,321,
	             [{1,{elem, 3},null,null,null,null,10,null,null,3,0},
	              {2,{type, "Evil"},{type, "Machine"},null,null,null,12,null,null,4,0}]}, 
	{combination,322,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 3},{elem, 3},null,null,null,11,null,null,3,0}]}, 
	{combination,323,[{1,{elem, 1},null,null,null,null,7,9,null,2,0}]}, 
	{combination,324,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{type, "Dragon"},null,null,null,null,9,null,null,2,0}]}, 
	{combination,325,[{1,{elem, 3},null,null,null,null,9,null,null,2,0}]}, 
	{combination,326,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{type, "Monster"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,327,
	             [{1,{elem, 3},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 3},{elem, 3},null,null,null,10,null,null,3,0}]}, 
	{combination,328,[{1,{elem, 3},null,null,null,null,9,null,null,2,0}]}, 
	{combination,329,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},null,null,null,null,10,null,null,3,0}]}, 
	{combination,330,
	             [{1,{elem, 3},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 3},{elem, 3},null,null,null,10,null,null,3,0}]}, 
	{combination,331,[{1,{elem, 5},null,null,null,null,7,null,null,1,0}]}, 
	{combination,332,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,11,null,null,3,0}]}, 
	{combination,333,[{1,{elem, 5},null,null,null,null,8,null,null,2,0}]}, 
	{combination,334,
	             [{1,{elem, 5},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 2},null,null,null,null,8,null,null,2,0}]}, 
	{combination,335,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,11,null,null,3,0}]}, 
	{combination,336,
	             [{1,{elem, 5},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,10,null,null,3,0}]}, 
	{combination,337,
	             [{1,{elem, 4},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 5},{elem, 4},null,null,null,6,null,null,3,1}]}, 
	{combination,338,[{1,{elem, 5},null,null,null,null,11,null,null,4,0}]}, 
	{combination,339,
	             [{1,{elem, 5},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 3},{elem, 5},null,null,null,11,null,4,3,0}]}, 
	{combination,340,[{1,{type, "Insect"},null,null,null,null,10,null,null,3,0}]}, 
	{combination,341,
	             [{1,{elem, 5},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,9,null,null,2,0}]}, 
	{combination,342,
	             [{1,{elem, 5},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 4},null,null,null,null,9,null,null,2,0}]}, 
	{combination,343,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 5},{elem, 5},null,null,null,9,null,null,2,0}]}, 
	{combination,344,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{type, "Insect"},null,null,null,null,9,null,null,2,0}]},
	{combination,345,
	             [{1,{elem, 5},null,null,null,null,8,null,null,2,0},
	              {2,{elem, 5},{elem, 5},null,null,null,9,null,null,3,0}]}, 
	{combination,346,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{type, "Bandit"},null,null,null,null,9,null,null,2,0}]},
	{combination,365,
	             [{1,{elem, 1},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},null,null,null,null,10,null,null,3,0}]},
	{combination,366,
		     [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 6},{elem, 2},null,null,null,8,null,null,4,1}]},
	{combination,367,
	             [{1,{elem, 3},null,null,null,null,9,null,null,3,0},
	              {2,{elem, 3},{elem, 3},null,null,null,11,null,null,4,0}]},			  
	{combination,368,
	             [{1,{elem, 1},null,null,null,null,7,9,null,1,0},
	              {2,{elem, 1},{elem, 1},null,null,null,10,10,null,3,0}]},
	{combination,369,
	             [{1,{elem, 1},null,null,null,null,7,9,null,1,0},
	              {2,{elem, 6},null,null,null,null,9,8,null,3,0}]},
	{combination,370,
	             [{1,{elem, 4},null,null,null,null,8,null,null,3,2},
	              {2,{elem, 4},{elem, 5},null,null,null,10,null,2,3,0}]},
	{combination,371,
	             [{1,{elem, 5},null,null,null,null,7,null,null,1,0},
	              {2,{elem, 4},null,null,null,null,8,null,null,2,0}]},
	{combination,372,
	             [{1,{elem, 2},null,null,null,null,8,8,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,10,9,null,3,0}]},
	{combination,373,
	             [{1,{elem, 2},null,null,null,null,9,null,null,2,0},
	              {2,{elem, 2},{elem, 2},null,null,null,11,null,null,3,0}]},
	{combination,374,
	             [{1,{elem, 3},null,null,null,null,8,null,null,2,0},
					  {2,{elem, 6},null,null,null,null,9,null,null,2,0}]},
	{combination,375,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0},
					  {2,{elem, 6},{elem, 3},null,null,null,10,null,null,3,0}]},
	{combination,376,
	             [
						{1,{elem, 4},null,null,null,null,11,null,null,3,0},
						{2,{elem, 4},{elem, 5},null,null,null,12,null,null,3,0}]},
	{combination,377,
	             [
						{1,{elem, 2},null,null,null,null,9,null,null,2,0},
						{2,{elem, 2},{elem, 2},null,null,null,8,null,null,4,1}]},
	{combination,378,
	             [{1,{elem, 6},null,null,null,null,9,null,null,2,0}]},
	{combination,379,
	             [{1,{elem, 1},null,null,null,null,8,null,null,2,0},
						{2,{elem, 1},{elem, 1},null,null,null,11,null,null,3,0}]},
	{combination,380,
	             [{1,{elem, 3},null,null,null,null,9,null,null,2,0},
						{2,{naming, "Witch"},null,null,null,null,10,null,null,3,0}]}
].
