%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(mystic_ability_set1).
-compile(export_all).

ability() ->
	[
		%นำ Seal 1 ใบเข้ามาในสนามจากมือเรา
		{mystic_ability,
			s1_no091_a1, 347, 1, y,
				n, [],
				y, owner, [hand_cards], seal, null, [], 1,
					null,
						null,
							n, null, {}, [], null,
							n, null, null, {}, [], null, 										
							n, null, {}, [], null,
							n, null, [], null, null, [],
								null, {}, [], null,
							y, owner, [hand_cards], seal, null, [],
								immediately, {player_select_exact_target, 1}, [{action, move_to_arena}], null
		},
		%Seal ที่ [S] ติด สามารถโจมตีด้วยท่าโจมตีใดก็ได้หรือใช้ Skill ได้แม้ไม่ตรงตามเงื่อนไขการรวมร่าง 1 ครั้งใน Subturn นี้
		{mystic_ability,
			s1_no092_a1, 348, 1, n,
				n, [],
				y, null, [arena_zone], seal, null, [{action, {n, card_casting}}], 1,
					null,
						null,
							n, null, {}, [], null,
							n, null, null, {}, [], null, 										
							n, null, {}, [], null,
							y, null, [arena_zone], seal, null, [{action, {n, card_casting}}],
								null, {player_select_exact_target, 1}, [{atk, without_combine}, {skill, without_combine}], 1,
							n, null, [null], null, null, [],
								null, {}, [], null
								
		},
		%Seal ที่ [S] ติด ติด Charm Curse ยกเว้น: Seal ตั้งแต่ Lv 3 ขึ้นไป, [Light] และ/หรือ [Machine]
		{mystic_ability,
			s1_no093_a1, 349, 1, n,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {level, "12"}, {elem, {n, 6}}, {type, {n, "Machine"}}, {protect_curse, {n, charm_curse}}, {curse, {n, charm_curse}}], 1,
						null,
							y,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {level, "12"}, {elem, {n, 6}}, {type, {n, "Machine"}}, {protect_curse, {n, charm_curse}}, {curse, {n, charm_curse}}],
									immediately, {player_select_exact_target, 1}, [{curse, charm_curse}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%เมื่อ [S] ใช้ Skill สำเร็จครบ 3 ครั้ง Sacrifice [S]
		{mystic_ability,
			s1_no094_a1, 350, 1, n,
				n, [],
					n, null, [], null, null, [], null,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								y, immediately, {do_not_need_select, 0}, [{move, sacrifice}], {use_skill, 3},
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%เรา Mp สูงสุด +1 และ การ์ดในมือสูงสุด -1
		{mystic_ability,
			s1_no095_a1, 351, 1, n,
				n, [],
					n, null, [], null, null, [], null,
						null,
							null,
								y, immediately, {do_not_need_select, 0}, [{mp_max, 1}, {card_on_hand, -1}], depend_on_s,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%ผู้เล่นทุกคนทิ้ง Mystic Card ทุกใบในมือ จากนั้นผู้เล่นทุกคนจั่ว Mystic Card อย่างน้อย 1 ใบแต่ไม่เกินจำนวน Mystic Card ที่ตนทิ้งไป 
		{mystic_ability,
			s1_no096_a1a, 352, 1, n,
				y, [{{opponent, [hand_cards], mystic, n}, {[], 1}}],
					y, owner, [hand_cards], mystic, n, [], 1,
						s1_no096_a1c,
							null,
								y, immediately, {do_not_need_select, 0}, [{discard, all_mystic_put_amount}], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		{mystic_ability,
			s1_no096_a1b, 352, 1, n,
				y, [{{opponent, [hand_cards], mystic, n}, {[], 1}}],
					y, owner, [hand_cards], mystic, n, [], 1,
						s1_no096_a1d,
							null,
								n, null, {}, [], null,
								y, opponent, immediately, {do_not_need_select, 0}, [{discard, all_mystic_put_amount}], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		{mystic_ability,
			s1_no096_a1c, 352, 1, n,
				n, [],
					y, owner, [mystic_deck], null, null, [], 1,
						null,
							null,
								y, immediately, {do_not_need_select, 0}, [{draw_mystic, {1, as_discard_amount}}], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		{mystic_ability,
			s1_no096_a1d, 352, 1, n,
				n, [],
					y, opponent, [mystic_deck], null, null, [], 1,
						null,
							null,
								n, null, {}, [], null,
								y, opponent, immediately, {do_not_need_select, 0}, [{draw_mystic, {1, as_discard_amount}}], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%Seal ที่ [S] ติดกลายเป็น Inactive Seal
		{mystic_ability,
			s1_no097_a1, 353, 1, y,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n, card_casting}}], 1,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n, card_casting}}],
									immediately, {player_select_exact_target, 1}, [{action, be_inactive}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%ผู้เล่นฝ่ายตรงข้ามนำ Seal ที่ไม่ใช่ [Machine] ทุกใบในสนามฝ่ายตนจาก At Line ไปที่ Df Line และนำ Seal จาก Df Line ไปที่ At Line 
		{mystic_ability,
			s1_no098_a1, 354, 1, n,
				n, [],
				y, opponent, [arena_zone], seal, null, [{type, {n, "Machine"}}, {can_move_to, 1}, {line, null}], 1,
					null,
						null,
							n, null, {}, [], null,
							n, null, null, {}, [], null, 										
							n, null, {}, [], null,
							n, null, [], null, null, [],
								null, {}, [], null,
							y, opponent, [arena_zone], seal, null, [{type, {n, "Machine"}}, {can_move_to, 1}, {line, null}],
								immediately, {do_not_need_select, 0}, [{player_action, change_line}], null
		},
		%Seal ที่ [S] ติดสามารถใช้ท่าโจมตีได้ 2 ครั้งโดยจ่าย Mp ค่าโจมตีเพียงครั้งเดียว  ยกเว้น: Seal ตั้งแต่ Lv 4 ขึ้นไป และ/หรือ [Machine]
		{mystic_ability,
			s1_no099_a1, 355, 1, n,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {level, "123"}, {type, {n, "Machine"}}], 1,
						null,
							y,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {level, "123"}, {type, {n, "Machine"}}],
									immediately, {player_select_exact_target, 1}, [{atk, additional_select_attack}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%ถ้า Seal ที่ [S] ติดไม่ได้รวมร่าง Seal นั้นนับว่าอยู่ในสภาพ Double Combination
		{mystic_ability,
			s1_no100_a1, 356, 1, n,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n, card_casting}}], 1,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n, card_casting}}],
									immediately, {player_select_exact_target, 1}, [{action, double_combine_when_not_combine}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%ฝ่ายตรงข้าม จำนวนการ์ดในมือสูงสุด -1
		{mystic_ability,
			s1_no101_a1, 357, 1, n,
				n, [],
					n, null, [], null, null, [], null,
						null,
							null,
								n, null, {}, [], null,
								y, opponent, immediately, {do_not_need_select, 0}, [{card_on_hand, -1}], depend_on_s, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%ฝ่ายตรงข้ามทิ้ง Mystic Card 1 ใบในมือแบบสุ่ม
		{mystic_ability,
			s1_no102_a1, 358, 1, n,
				n, [],
					y, opponent, [hand_cards], mystic, null, [], 1,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, opponent, [hand_cards], mystic, null, [],
									immediately, {random_select_exact_target, 1}, [{action, discard}], 1,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%เลือก 1 อย่าง
		%- ถ้า Seal ที่ [S] ติดคือ [Knight] Seal นั้น At +2
		{mystic_ability,
			s1_no103_a1, 359, 1, n,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}], 1,
						null,
							y,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}],
									immediately, {player_select_exact_target, 1}, [{check_condition, {[{type, "Knight"}], {at, 2}}}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%- ถ้า Seal ที่ [S] ติดคือ [Wind] Seal นั้น At +2 Sp +1 
		%ยกเว้น: Seal ตั้งแต่ Lv 3 ขึ้นไป และ/หรือ [Machine]
		{mystic_ability,
			s1_no103_a2, 359, 2, n,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}], 1,
						null,
							y,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}],
									immediately, {player_select_exact_target, 1}, [{check_condition, {[{elem, 3}], {at, 2}}}, {check_condition, {[{elem, 3}], {sp, 1}}}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%เลือก 1 อย่าง
			%- ถ้า Seal ที่ [S] ติดคือ [Mage] Seal นั้น At +2 
		{mystic_ability,
			s1_no104_a1, 360, 1, n,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}], 1,
						null,
							y,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}],
									immediately, {player_select_exact_target, 1}, [{check_condition, {[{type, "Mage"}], {at, 2}}}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%- ถ้า Seal ที่ [S] ติดคือ [Earth] Seal นั้น At +2 Df +1 
			%ยกเว้น: Seal ตั้งแต่ Lv 3 ขึ้นไป และ/หรือ [Machine]
		{mystic_ability,
			s1_no104_a2, 360, 2, n,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}], 1,
						null,
							y,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}, {type, {n, "Machine"}}, {level, "12"}],
									immediately, {player_select_exact_target, 1}, [{check_condition, {[{elem, 1}], {at, 2}}}, {check_condition, {[{elem, 1}], {df, 1}}}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%Seal ที่ [S] ติด - Df ตาม Lv ของ Seal ใบนั้น 
		{mystic_ability,
			s1_no105_a1, 361, 1, y,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}], 1,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}],
									immediately, {player_select_exact_target, 1}, [{df, {'-', target_level}}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%Seal ที่ [S] ติด - At ตาม Lv ของ Seal ใบนั้น
		{mystic_ability,
			s1_no106_a1, 362, 1, y,
				n, [],
					y, null, [arena_zone], seal, null, [{action, {n , card_casting}}], 1,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								y, null, [arena_zone], seal, null, [{action, {n , card_casting}}],
									immediately, {player_select_exact_target, 1}, [{at, {'-', target_level}}], depend_on_s,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%ผู้เล่น 1 คน Mp -1
		{mystic_ability,
			s1_no107_a1, 363, 1, n,
				n, [],
					n, null, [], null, null, [], null,
						null,
							null,
								n, null, {}, [], null,
								%y, null, immediately, {player_select_exact_target, 1}, [{mp, 1}], null,
								y, opponent, immediately, {do_not_need_select, 0}, [{mp, -1}], null,
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null							
		},
		%เลือก 1 อย่าง 
			%- รักษา Curse ทุกชนิดให้กับ Seal 1 ใบ 
		{mystic_ability,
			s1_no108_a1, 364, 1, y,
				n, [],
					y, null, [arena_zone], seal, null, [{curse, y}], 1,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								y, null, [arena_zone], seal, null, [{curse, y}],
									immediately, {player_select_exact_target, 1}, [{heal_curse, [all]}], null							
		},
			%- ทำลาย Mystic Card ชนิด [PS] 1 ใบในสนาม
		{mystic_ability,
			s1_no108_a2, 364, 2, y,
				n, [],
					y, null, [arena_zone], mystic, null, [{paste_type, 1}], 1,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], null,
								y, null, [arena_zone], mystic, null, [{paste_type, 1}],
									immediately, {player_select_exact_target, 1}, [{action, destroy}], null
		},
		%Seal ทุกใบที่อยู่ใน At Line ป้องกันการโจมตี
		{mystic_ability,
			p1_no125_a1, 381, 1, n,
				n, [],
					n, null, [], null, null, [], null,
						null,
							null,
								n, null, {}, [], null,
								n, null, null, {}, [], null, 										
								n, null, {}, [], null,
								n, null, [], null, null, [],
									null, {}, [], nul,
								y, null, [arena_zone], seal, null, [{line, 1}],
									immediately, {do_not_need_select, 1}, [{protect_attack, [all]}], 2							
		}
	].
