%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(s_skill_set2).
-compile(export_all).

light_skill() ->
[
	%[Skill]-Seal 1 ใบในสนามโจมตีด้วย Df และเมื่อ Seal นั้นถูกโจมตี เทียบ Df ของ Seal นั้นกับค่าพลังของ Seal ที่โจมตีจนออกจากการโจมตี 1 Turn (Df Line) (Mp 3) 
	{card_skill,
			s2_light_no002_s1, 514, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {line, 0}], 											
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{combat, {when_attack, {df, power}}}, {combat, {when_target, {power, df}}}]} , 2,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-ย้าย Mystic Card 1 ใบที่ติดบน Seal 1 ใบในสนามไปติดที่เป้าหมายใหม่ที่ Mystic Card นั้นสามารถติดได้เมื่อ [S] รวมร่าง (Mp 2)
	{card_skill,
			s2_light_no004_s1, 516, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								%y, [{zone, [arena_zone]}, {combine, y}, {seal_arena, {[{mystic_paste, y}], 1}}],
								y, [{zone, [arena_zone]}, {combine, y}],
									y, null, [arena_zone], mystic, n, [{paste_type, 1},  {can_paste_to_seal, other}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], mystic, n, [{paste_type, 1}, {can_paste_to_seal, other}],
														{player_select_exact_target, 1, [{action, paste_to_other_target}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	% {card_skill,
			% s2_light_no004_s1b, 516, 1, 2, n,
				% y, 
					% null, null,	
						% n, [],
							% n, null, [],									
								% y, [{zone, [arena_zone]}, {combine, y}],
									% y, null, [arena_zone], mystic, n, [{mystic_type, 1},  {can_paste_to_other, seal}], 2,			                        
										% n, [], null,
											% n, null, [], null,										
												% n, [], null, 
													% y, null, [arena_zone], mystic, n, [{mystic_type, 1}, {can_paste_to_other, seal}],
														% {{depend_on, s2_light_no004_s1a}, 1, [{action, {paste_select_to_other_target, s2_light_no004_s1a}}]} ,0,
															% n, null, [null], null, null, [],
																% [], null	
	% },
	%[Skill]-[Water] 1 ใบสามารถใช้ Skill ได้โดยไม่ต้องตรงตามเงื่อนไขของการรวมร่างจนจบ Subturn (At Line) (Mp 2)
	{card_skill,
			s2_light_no007_s1, 519, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, n, [{elem, 2}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, n, [{elem, 2}, {protect_skill, n}],
														{player_select_exact_target, 1, [{skill, without_combine}]} ,0,
															n, null, [null], null, null, [],
																[], null	
	},
	%Growth: [Dragon] + [Divine] :[Skill]-นำ [Dragon] 1 ใบใน Shrine ผู้ใช้ Skill ขึ้นมือ (At Line) (Mp 4)
	{card_skill,
			s2_light_no007_s2, 519, 2, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y}, {line, 1}], 											
									y, owner, [shrine_cards], seal, n, [{type, "Dragon"}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [shrine_cards], seal, n, [{type, "Dragon"}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, move_to_hand}]} ,0,
															n, null, [null], null, null, [],
																[], null	
	},
	%Growth: [Dragon's Egg]:[Skill]-Sacrifice [S]; Seal 2 ใบในสนามยกเลิก Curse และ Mystic Card 1 Turn (Mp 2)
	{card_skill,
			s2_light_no011_s1, 523, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y}, {zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, n, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{player_action, sacrifice}]}, 0, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 2, [{cancel_curse, [all]}, {cancel_mystic, [all]}]} , 2,
															n, null, [null], null, null, [],
																[], null	
	}
].

earth_skill() ->
[
	%[Skill]-นำ Seal 1 ใบใน Shrine ผู้ใช้ Skill ขึ้นมือ เมื่อ [S] รวมร่าง (Mp 3)
	{card_skill,
			s2_earth_no018_s1, 530, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, controller, [shrine_cards], seal, n, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [shrine_cards], seal, n, [{protect_skill, n}],
														{player_select_exact_target, 1, [{action, move_to_hand}]} , 0,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-[S] +At ตาม Df ของ Seal 1 ใบในสนามฝ่ายผู้ใช้ Skill จนจบ Subturn ? (Mp 2)
	{card_skill,
			s2_earth_no019_s1, 531, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{at, {{select_seal_controller_arena, []}, defend}}]}, 1, 
													n, null, [null], null, null, [],
														{} , null,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]–Seal 1 ใบที่มี Sp 2, 3, 4 ติด Stone Curse 2 Turn เมื่อ [S] รวมร่างกับ [Earth] (Mp 2)
	{card_skill,
			s2_earth_no020_s1, 532, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {elem, 1}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {curse, {n, stone_curse}}, {protect_curse, {n, stone_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {curse, {n, stone_curse}}, {protect_curse, {n, stone_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, stone_curse}]} , 4,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]–Seal 1 ใบที่มี Sp 2, 3, 4 ติด Charm Curse 2 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 2)
	{card_skill,
			s2_earth_no020_s2, 532, 2, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {curse, {n, charm_curse}}, {protect_curse, {n, charm_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {curse, {n, charm_curse}}, {protect_curse, {n, charm_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, charm_curse}]} , 4,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Seal 1 ใบในสนามติด Dimension Curse 1 Turn เมื่อ [S] รวมร่าง (Mp 3)
	{card_skill,
			s2_earth_no022_s1, 534, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{curse, {n, dimension_curse}}, {protect_curse, {n, dimension_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{curse, {n, dimension_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, dimension_curse}]} , 2,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]–Seal 1 ใบที่มี Sp 2, 3, 4 ติด Stone Curse 3 Turn เมื่อ [S] รวมร่าง (Df Line) (Mp 2)
	{card_skill,
			s2_earth_no023_s1, 535, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}, {line, 0}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {curse, {n, stone_curse}}, {protect_curse, {n, stone_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {curse, {n, stone_curse}}, {protect_curse, {n, stone_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, stone_curse}]} , 6,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Seal 1 ใบติด Stone Curse  ? Turn (At Line) (Mp 3)
	{card_skill,
			s2_earth_no025_s1, 537, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {growth, y}], 											
									y, null, [arena_zone], seal, y, [{protect_curse, {n, stone_curse}}, {curse, {n, stone_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_curse, {n, stone_curse}},{curse, {n, stone_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, stone_curse}]} , infinite,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]– [S] เปลี่ยน Line ? (Mp 1)
	{card_skill,
			s2_earth_no027_s1, 539, 1, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}, {line, null}, {can_move_to, any}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, change_line}]}, 0, 
													n, null, [null], null, null, [],
														{} , null,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]–Seal ที่ติด Stone Curse 1 ใบติด Poison Curse 3 Turn (Mp 2)
	{card_skill,
			s2_earth_no030_s1, 542, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{protect_curse, {n, stone_curse}}, {curse, stone_curse}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}},{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_curse, {n, stone_curse}}, {curse, stone_curse}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}},{protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]} , 6,
															n, null, [null], null, null, [],
																[], null	
	}
].

fire_skill() ->
[
	%[Skill]-ทิ้ง Seal 1 ใบในมือผู้ใช้ Skill; ทิ้งการ์ด 1 ใบในมือฝ่ายตรงข้ามแบบสุ่ม (Charge 1) (Mp 3)
	{card_skill,
			s2_fire_no035_s1a, 547, 1, {3, 1}, n,
				y, 
					null, s2_fire_no035_s1b,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {{uncontrol, [hand_cards], null, null}, {[], 1}}],
								%y, [{zone, [arena_zone]}],
									y, controller, [hand_cards], seal, null, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [],
														{player_select_exact_target, 1, [{player_action, discard}]} , 0,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s2_fire_no035_s1b, 547, 1, {3, 1}, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {{controller, [hand_cards], null, null}, {[], 1}}], 											
									y, uncontrol, [hand_cards], all, null, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, uncontrol, [hand_cards], all, null, [],
														{random_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill] – [Fire] 1 ใบในสนามฝ่ายผู้ใช้ Skill สามารถสั่งโจมตีได้อีกครั้ง แม้เป็น Inactive Seal จนจบ Subturn (Mp 1)
	{card_skill,
			s2_fire_no036_s1, 548, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, y, [{elem, 4}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{elem, 4}, {protect_skill, n}],
														{player_select_exact_target, 1, [{attack, again_even_inactive}]}, end_of_subturn,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]–[Wind] 1 ใบในสนาม At -2 / 1 Turn (Mp 2)
	{card_skill,
			s2_fire_no036_s2, 548, 2, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{elem, 3}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{elem, 3}, {protect_skill, n}],
														{player_select_exact_target, 1, [{at, -2}]}, 2, 
															n, null, [null], null, null, [],
																[] ,null
		},
	%[Skill]-Seal ที่ไม่ใช่ [Water] 1 ใบในสนามฝ่ายตรงข้ามแยกการรวมร่าง เมื่อ [S] มี [Fire] เป็น Seal ใบรองรวมร่าง (At Line) (Mp 3)
		{card_skill,
			s2_fire_no038_s1, 550, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {card_type, is_seal}}, {combine, {elem, 4}}, {line, 1}], 											
									y, opponent, [arena_zone], seal, n, [{combine, y}, {elem, {n, 2}}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, [], null, 
													y, opponent, [arena_zone], seal, n, [{combine, y}, {elem, {n, 2}}],
														{player_select_exact_target, 1, [{action, break_combine}]}, null,
															n, null, [null], null, null, [],
																[], null 
		},
	%[Skill]-Sacrifice Seal 1 ใบ; ทำลาย Seal 1 ใบที่มี Lv 1 (At Line) (Mp 2)
	{card_skill,
			s2_fire_no041_s1a, 553, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y}, {line, 1}, {{null, [arena_zone], seal, y}, {[{level, 1}, {protect_skill, n}], 1}}],
								%y, [{growth, y}, {line, 1}],
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, sacrifice}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s2_fire_no041_s1b, 553, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								%y, [{growth, y}, {line, 1}],
								y, [{growth, y}, {line, 1}, {{null, [arena_zone], seal, y}, {[{level, 1}, {protect_skill, n}], 1}}],
									y, null, [arena_zone], seal, y, [{level, 1}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{level, 1}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, destroy}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-Seal 1 ใบที่มี Sp 3, 4, 5 ติด Poison Curse 3 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 2) 
	{card_skill,
			s2_fire_no043_s1, 555, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 6,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-Seal 1 ใบที่มี Sp 3, 4, 5 ติด Last Dance Curse At +2 / 2 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 2) 
	{card_skill,
			s2_fire_no044_s1, 556, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, 2}}}]}, 4,
															n, null, [null], null, null, [],
																[], null
	}
].

water_skill() ->
[
	%[Skill]-Freeze Curse (All) 1 Turn เมื่อ [S] รวมร่างกับ [Water] (At Line) (Mp 4)
	{card_skill,
			s2_water_no047_s1, 559, 1, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 2}}],
								%y, null, [arena_zone], seal, y, [{protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}, {protect_skill, {n, [skill_all]}}], 1,
									n, null, [], null, null, [], null,
										n, [], null,
											y, controller, {player_select_exact_player, 1, [{curse, freeze_curse}]}, 2,										
												n, {}, null, 
													%y, null, [arena_zone], seal, y, [{protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}, {protect_skill, {n, [skill_all]}}],
													n, null, [], null, null, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-Seal 1 ใบติด Freeze Curse ? Turn (At Line) (Charge 2) (Mp 2)
	{card_skill,
			s2_water_no049_s1, 561, 1, {2, 2}, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}, {protect_skill, {n, [skill_all]}}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}, {protect_skill, {n, [skill_all]}}],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, infinity,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill] – เลือก [Water] ที่ไม่ได้ชื่อ [S] 1 ใบในสนามฝ่ายผู้ใช้ Skill ผู้ใช้ Skill สามารถสั่ง Seal นั้นใช้ Skill ได้อีก 1 ครั้ง แม้ Seal นั้นเป็น Inactive Seal จนจบ Subturn (Mp 1)
	{card_skill,
			s2_water_no050_s1, 562, 1, 1, n,
				y,  
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, n, [{elem, 2}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, n, [{elem, 2}, {protect_skill, n}],
														{player_select_exact_target, 1, [{skill, again_even_inactive}]}, 1,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]–[Fire] 1 ใบในสนามฝ่ายตรงข้ามสูญเสีย Ability 1 Turn (Mp 2)
	{card_skill,
			s2_water_no050_s2, 562, 2, 2, n,
				y,  
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, opponent, [arena_zone], seal, n, [{elem, 4}, {have_ability, y}, {protect_skill, n}], 1,
										n, [], null,
											n, null, [], null,	
												n, {}, null, 
													y, opponent, [arena_zone], seal, n, [{elem, 4}, {have_ability, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{ability, {loss, [all]}}]}, 2,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-นำ Seal 1 ใบไปที่ Df Line จากนั้น Seal ใบนั้นไม่สามารถเปลี่ยน Line และไม่สามารถเป็น Seal ใบรองรวมร่างได้ 2 Turn (Charge 2) (Mp 2)
	{card_skill,
			s2_water_no051_s1a, 563, 1, {2, 2}, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{line, 1}, {can_move_to, 0}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{line, 1}, {can_move_to, 0}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, change_line}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s2_water_no051_s1b, 563, 1, {2, 2}, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{line, 1}, {can_move_to, 0}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{line, 1}, {can_move_to, 0}, {protect_skill, n}],
														{{depend_on,s2_water_no051_s1a}, 1, [{change_line, disallow}, {supporter, disallow}]}, 4,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-[S] Df +2 / 1 Turn ? (Charge 1) (Mp 1)
	{card_skill,
			s2_water_no051_s2, 563, 2, {1, 1}, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}], 											
									n, null, [], null, null, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 1, [{df, 2}]}, 2,
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
	},
	%Growth: [Dragon] ธาตุ [Water] +[Water]:[Skill]-Seal ทุกใบที่อยู่ใน At Line ติด Freeze Curse 1 Turn เมื่อ [S] รวมร่าง (Mp 4)
	{card_skill,
			s2_water_no052_s1, 564, 1, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y}, {zone, [arena_zone]}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{line, 1}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{line, 1}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}],
														{do_not_need_select, 0, [{curse, freeze_curse}]}, 2,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-Seal 1 ใบที่มี Sp 3, 4, 5 ติด Poison Curse 2 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
	{card_skill,
			s2_water_no053_s1, 565, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 4,
															n, null, [null], null, null, [],
																[], null
	},
	%Growth: [Dragon] ธาตุ [Water][Skill]-Seal 1 ใบติด Poison Curse 1 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 3)
	{card_skill,
			s2_water_no055_s1, 567, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y}, {line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 2,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-Seal 1 ใบที่มี Sp 1, 2, 3 ติด Freeze Curse และ Stone Curse 2 Turn เมื่อ [S] รวมร่าง (Df Line) (Mp 3)
	{card_skill,
			s2_water_no056_s1, 568, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}, {line, 0}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "123"}, {protect_curse, {n, freeze_curse}}, {protect_curse, {n, stone_curse}}, {curse, {n, freeze_curse}}, {curse, {n, stone_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "123"}, {protect_curse, {n, freeze_curse}}, {protect_curse, {n, stone_curse}}, {curse, {n, freeze_curse}}, {curse, {n, stone_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, freeze_curse}, {curse, stone_curse}]}, 4,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-Seal 1 ใบที่มี Sp 2, 3, 4 ติด Freeze Curse 2 Turn เมื่อ [S] รวมร่าง (Df Line) (Mp 3)
	{card_skill,
			s2_water_no057_s1, 569, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {growth, y}, {line, 0}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, 4,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-Seal 1 ใบที่มี Sp 2, 3, 4 ติด Freeze Curse 1 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
	{card_skill,
			s2_water_no058_s1, 570, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, 2,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]–Seal ที่ติด Freeze Curse 1 ใบติด Poison Curse 2 Turn (At Line) (Mp 2)
	{card_skill,
			s2_water_no059_s1, 571, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{curse, freeze_curse}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{curse, freeze_curse}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 4,
															n, null, [null], null, null, [],
																[], null
	}
].

wind_skill() ->
[
	%[Skill]–ผู้ใช้ Skill สั่ง [S] รวมร่าง ? (Mp 2)
	{card_skill,
			s2_wind_no062_s1, 574, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {n, {card_type, is_seal}}}, {combine, have_choice}], 											
									n, null, [null], null, null, [], null,			                        
										n, {}, null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, assign_s_combine}]}, 0,
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-นำ [S] เข้ามาในสนามจากมือ ? (Mp 4) 
	{card_skill,
			s2_wind_no063_s1, 575, 1, 4, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [hand_cards]}, {protect_skill, n}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_arena}]}, 0, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]–Seal 1 ใบ ที่อยู่ใน Df Line ติด Death Curse เมื่อ [S] รวมร่าง (At Line) (Mp 5)
	{card_skill,
			s2_wind_no064_s1, 576, 1, 5, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{line, 0}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{line, 0}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, death_curse}]}, null,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-ทิ้ง [Beast] 1 ใบในมือผู้ใช้ Skill ; นำ [Beast] 1 ใบเข้ามาในสนามจาก Shrine ผู้ใช้ Skill (Df Line) (Mp 4)
	{card_skill,
			s2_wind_no065_s1a, 577, 1, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]},{line, 0}, {{controller, [shrine_cards], seal, null}, {[{type, "Beast"}, {protect_skill, n}], 1}}], 											
									y, controller, [hand_cards], seal, null, [{type, "Beast"}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [{type, "Beast"}, {protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s2_wind_no065_s1b, 577, 1, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]},{line, 0}, {{controller, [hand_cards], seal, null}, {[{type, "Beast"}, {protect_skill, n}], 1}}],
								%y, [{zone, [arena_zone]},{line, 0}],
									y, controller, [shrine_cards], seal, null, [{type, "Beast"}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [shrine_cards], seal, null, [{type, "Beast"}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, move_to_arena}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-ทิ้ง [Dragon] 1 ใบในมือผู้ใช้ Skill ; นำ [Dragon] 1 ใบเข้ามาในสนามจาก Shrine ผู้ใช้ Skill (Df Line) (Mp 4)
	{card_skill,
			s2_wind_no065_s2a, 577, 2, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]},{line, 0}, {{controller, [shrine_cards], seal, null}, {[{type, "Dragon"}], 1}}], 											
									y, controller, [hand_cards], seal, null, [{type, "Dragon"}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [{type, "Dragon"}],
														{player_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s2_wind_no065_s2b, 577, 2, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]},{line, 0}, {{controller, [hand_cards], seal, null}, {[{type, "Dragon"}], 1}}], 											
									y, controller, [shrine_cards], seal, null, [{type, "Dragon"}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [shrine_cards], seal, null, [{type, "Dragon"}],
														{player_select_exact_target, 1, [{action, move_to_arena}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]-แสดง [Beast] 1 ใบจากกองการ์ด Seal ผู้ใช้ Skill ถ้าเป็น N[Pegasus] และ/หรือ N[Unicorn] นำเข้ามาในสนาม ถ้าไม่ใช่นำขึ้นมือ (Df Line) (Mp 3)
	{card_skill,
			s2_wind_no066_s1, 578, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [seal_deck], null, n, [{type, "Beast"}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null,
													y, controller, [seal_deck], null, n, [{type, "Beast"}],
														{player_select_exact_target, 1, [{player_action, {recheck_condition, {[{naming_or, ["Pegasus", "Unicorn"]}], {action, move_to_arena}}, {{[], {action, move_to_hand}}}}}]}, null,
															n, null, [null], null, null, [],
																[], null
	},
	%[Skill]–ทิ้ง Seal 1 ใบในมือผู้ใช้ Skill; สั่ง [S] โจมตีข้ามไปยัง Df Line (At Line) (Mp 2)
	{card_skill,
			s2_wind_no067_s1a, 579, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {{uncontrol, [arena_zone], seal, null}, {[{line, 0}], 1}}],
								%y, [{line, 1}],
									y, controller, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [],
														{player_select_exact_target, 1, [{player_action, discard}]}, null,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s2_wind_no067_s1b, 579, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {{controller, [hand_cards], seal, null}, {[], 1}}], 											
									y, uncontrol, [arena_zone], seal, null, [{line, 0}], 1,			                        
										n, {}, null,
											n, null, [], null,
												y, {do_not_need_select, 0, [{assign_atk, assign_s_attack_to_df}]}, null,
													n, null, [null], null, null, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null
	},
	%Growth: Dimminuial, the Baby Dragon::[Skill]-Seal 1 ใบที่มี Sp 1, 2, 3, 4, 5 ติด Dimension Curse 1 Turn (At Line) (Mp 3)
	{card_skill,
			s2_wind_no068_s1, 580, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y}, {line, 1}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, dimension_curse}]} , 2,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Seal 1 ใบ ที่มี Sp 1, 2, 3 ติด Poison Curse 2 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 2)
	{card_skill,
			s2_wind_no071_s1, 583, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "123"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "123"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]} , 4,
															n, null, [null], null, null, [],
																[], null	
	},
	%Growth: [Dragon] ธาตุ [Wind] + [Water]::[Skill]-Seal 2 ใบที่มี Sp 0, 1, 2, 3 ติด Poison Curse 2 Turn (At Line) (Mp 3)
	{card_skill,
			s2_wind_no071_s2, 583, 2, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y}, {line, 1}],										
									y, null, [arena_zone], seal, y, [{skill_target_speed, "0123"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 2,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "0123"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 2, [{curse, poison_curse}]} , 4,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-นำการ์ดใบบนสุด 1 ใบของกองการ์ดทุกกองของผู้เล่นทุกคนไปวางไว้ล่างสุดของกองการ์ดนั้น ? (Mp 1)
	{card_skill,
			s2_wind_no072_s1a, 584, 1, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, owner, [seal_deck], n, null, [], 1,			                        
										y, {do_not_need_select, 0, [{swap, {head_to_tail, seal_deck}}]}, 0,
											n, null, [], null,										
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_wind_no072_s1b, 584, 1, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, opponent, [seal_deck], null, null, [], 1,			                        
										n, [], null,
											y, opponent, {do_not_need_select, 0, [{swap, {head_to_tail, seal_deck}}]}, 0,										
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_wind_no072_s1c, 584, 1, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, owner, [mystic_deck], null, null, [], 1,			                        
										y, {do_not_need_select, 0, [{swap, {head_to_tail, mystic_deck}}]}, 0,
											n, null, [], null,										
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_wind_no072_s1d, 584, 1, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, opponent, [mystic_deck], null, null, [], 1,			                        
										n, [], null,
											y, opponent, {do_not_need_select, 0, [{swap, {head_to_tail, mystic_deck}}]}, 0,										
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-นำการ์ดใบล่างสุด 1 ใบของกองการ์ดทุกกองของผู้เล่นทุกคนไปวางไว้บนสุดของกองการ์ดนั้น ? (Mp 1)
	{card_skill,
			s2_wind_no072_s2a, 584, 2, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, owner, [seal_deck], n, null, [], 1,			                        
										y, {do_not_need_select, 0, [{swap, {tail_to_head, seal_deck}}]}, 0,
											n, null, [], null,										
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_wind_no072_s2b, 584, 2, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, opponent, [seal_deck], null, null, [], 1,			                        
										n, [], null,
											y, opponent, {do_not_need_select, 0, [{swap, {tail_to_head, seal_deck}}]}, 0,
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_wind_no072_s2c, 584, 2, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, owner, [mystic_deck], null, null, [], 1,			                        
										y, {do_not_need_select, 0, [{swap, {tail_to_head, mystic_deck}}]}, 0,
											n, null, [], null,
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_wind_no072_s2d, 584, 2, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, opponent, [mystic_deck], null, null, [], 1,			                        
										n, [], null,
											y, opponent, {do_not_need_select, 0, [{swap, {tail_to_head, mystic_deck}}]}, 0,
												n, [], null, 
													n, null, [], null, n, [],
														{}, null,
															n, null, [], null, null, [],
																[], null	
	},
	% % [Skill]-ผู้เล่น 1 คนจั่วการ์ด 1 ใบ (Df Line) (Mp 3
	{card_skill,
			s2_wind_no075_s1, 587, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {line, 0}], 											
									y, null, [seal_deck, mystic_deck], all, y, [], 1,			                        
										n, {}, null,
											y, controller, {player_select_exact_player, 0, [{draw_card, 1}]}, 0,										
												n, [], null, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]- [S] รวมร่าง ? (At Line) (Mp 2) (ผลจาก Skill นี้ไม่นับเป็นการสั่งให้ [S] รวมร่าง)
	{card_skill,
			s2_wind_no077_s1, 589, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {n, {card_type, is_seal}}}, {combine, have_choice}], 											
									n, null, [], null, null, [], null,			                        
										n, {}, null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, combine}]}, 0,
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
	}
	% },
	% {card_skill,
			% s2_wind_no077_s1b, 589, 1, 2, y,
				% y, 
					% null, null,	
						% n, [],
							% n, null, [],									
								% y, [{line, 1}], 											
									% y, owner, [arena_zone], seal, n, [{type, "Monster"}, {protect_skill, n}], 1,			                        
										% n, {}, null,
											% n, null, [], null,										
												% y, {do_not_need_select, 0, [{action, combine}]}, null, 
													% n, null, [null], null, null, [],
														% [], null,
															% n, null, [null], null, null, [],
																% [], null	
	% }
].

dark_skill() ->
[
	%[Skill]-ทิ้ง Seal 1 ใบในมือผู้ใช้ Skill; [S] + At ตาม Mp ค่าร่ายย ของ Seal ใบนั้น 1 Turn ? (Mp 2) 
	{card_skill,
			s2_dark_no078_s1a, 590, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}], 											
									y, controller, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [],
														{player_select_exact_target, 1, [{player_action, {discard_collect, {target, mc}}}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_dark_no078_s1b, 590, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}], 											
									y, owner, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{at, {'+', {get_erase, mc}}}]}, 2, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]–Seal 1 ใบสูญเสีย Skill และ/หรือ Ability ? Turn (At Line) (Charge 2) (Mp 2)
	{card_skill,
			s2_dark_no080_s1, 592, 1, {2, 2}, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{have_one, y}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{have_one, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{skill, {loss, [all]}}, {ability, {loss, [all]}}]}, infinite,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-ทิ้ง Seal และ Mystic Card อย่างละ 1 ใบในมือผู้ใช้ Skill; ทิ้ง Seal 1ใบในมือฝ่ายตรงข้ามแบบสุ่ม (At Line) (Mp 3)
	{card_skill,
			s2_dark_no081_s1a, 593, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {{controller, [hand_cards], mystic, null}, {[], 1}}, {{uncontrol, [hand_cards], seal, null}, {[], 1}}],
								%y, [{line, 1}],
									y, controller, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [],
														{player_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_dark_no081_s1b, 593, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {{controller, [hand_cards], seal, null}, {[], 1}}, {{uncontrol, [hand_cards], seal, null}, {[], 1}}], 											
									y, controller, [hand_cards], mystic, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], mystic, null, [],
														{player_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_dark_no081_s1c, 593, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {{controller, [hand_cards], seal, null}, {[], 1}}, {{controller, [hand_cards], mystic, null}, {[], 1}}],
									y, uncontrol, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, uncontrol, [hand_cards], seal, null, [],
														{random_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill] – เมื่อ [S] เป็นเป้าหมายของ Skill สั่ง [S] โจมตี Seal ที่ใช้ Skill นั้น ? (At Line) (Mp 3)
	{card_skill,
			s2_dark_no082_s1, 594, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {action, skill_target}, {protect_skill, n}], 											
									y, uncontrol, [arena_zone], seal, n, [{action, using_skill}], 1,	                        
										n, {}, null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{assign_atk, to_seal_using_skill}]}, null, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Seal 1 ใบฝ่ายผู้ใช้ Skill ที่มี Sp 1,2,3,4,5 ติด Last Dance Curse At +3 / 2 Turn เมื่อ [S] รวมร่างกับ[Dark] (Mp 3)
	{card_skill,
			s2_dark_no084_s1, 596, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {elem, 5}}], 											
									y, controller, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, 3}}}]}, 4,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]–Seal ที่ติด Curse 1 ใบติด Poison Curse 2 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
	{card_skill,
			s2_dark_no085_s1, 597, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{curse, y}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 4,
															n, null, [null], null, null, [],
																[], null	
	},
	%086   Fierce Therion
	%[Skill]-Seal ที่ติด Curse 1 ใบสูญเสีย Ability 1 Turn (At Line) (Mp 2)
	{card_skill,
			s2_dark_no086_s1, 598, 1, 2, n,
				y,
					null, null,
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {have_ability, y}], 1,
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{curse, y}, {have_ability, y}],
														{player_select_exact_target, 1, [{ability, {loss, [all]}}]}, 2,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill] – Seal 1 ใบที่มี Sp 2, 3, 4, 5 ติด Last Dance Curse + At ตาม Lv ของ Seal ใบนั้น / 2 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
	{card_skill,
			s2_dark_no087_s1, 599, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, {target, level}}}}]}, 4,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Seal 1 ใบที่อยู่ใน At Line ติด Poison Curse 3 Turn เมื่อ [S] รวมร่าง (Mp 2)
	{card_skill,
			s2_dark_no088_s1, 600, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{line, 1}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{line, 1}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 6,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Poison Curse ที่ติดบน Seal 1 ใบนับว่าผ่านไป 1 Turn (At Line) (Mp 2)
	{card_skill,
			s2_dark_no089_s1, 601, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{curse, poison_curse}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{curse, poison_curse}, {protect_skill, n}],
														{player_select_exact_target, 1, [{{curse_timer, poison_curse}, -2}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Seal 1 ใบที่มี Sp 2, 3, 4, 5 ติด Last Dance Curse At +2 / 1 Turn (At Line) (Mp 3)
	{card_skill,
			s2_dark_no090_s1, 602, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{growth, y},{line, 1}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, 2}}}]}, 2,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-ทิ้ง [Dark] 1 ใบในมือผู้ใช้ Skill;
	{card_skill,
			s2_dark_no092_s1a, 604, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}, {{null, [arena_zone], seal, y}, {[{combine, y}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1}}], 											
									y, controller, [hand_cards], seal, null, [{elem, 5}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [{elem, 5}, {protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, discard}]}, 2,
															n, null, [null], null, null, [],
																[], null	
	},
	%Seal ที่รวมร่าง 1 ใบติด Poison Curse 1 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 1)
	{card_skill,
			s2_dark_no092_s1b, 604, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}, {{controller, [hand_cards], seal, null}, {[{elem, 5}, {protect_skill, n}], 1}}], 											
									y, null, [arena_zone], seal, y, [{combine, y}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{combine, y}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 2,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Seal 1 ใบที่มี Sp 2, 3, 4 ติด Last Dance Curse At +2 / 2 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
	{card_skill,
			s2_dark_no093_s1b, 605, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, 2}}}]}, 4,
															n, null, [null], null, null, [],
																[], null	
	}
].
promo_skill()->
[
	%[Skill]-ทิ้ง Seal 1 ใบในมือผู้ใช้ Skill; ผู้เล่นคนอื่นทุกคนทิ้ง Seal 1 ใบในมือ เมื่อ [S] รวมร่าง (Mp 3)
	{card_skill,
			s2_light_no109_s1a, 621, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, controller, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [],
														{player_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},

	{card_skill,
			s2_light_no109_s1b, 621, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 										
									y, uncontrol, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, uncontrol, [hand_cards], seal, null, [],
														{opponent_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-ทิ้ง Mystic Card 1 ใบในมือผู้ใช้ Skill; ผู้เล่นคนอื่นทุกคนทิ้ง Mystic Card 1 ใบในมือ เมื่อ [S] รวมร่าง (Mp 3)
	{card_skill,
			s2_light_no109_s2a, 621, 2, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}, {{uncontrol, [hand_cards], mystic, null}, {[], 1}}],
									y, controller, [hand_cards], mystic, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], mystic, null, [],
														{player_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_light_no109_s2b, 621, 2, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}, {{controller, [hand_cards], mystic, null}, {[], 1}}], 										
									y, uncontrol, [hand_cards], mystic, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, uncontrol, [hand_cards], mystic, null, [],
														{opponent_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	%[Skill]-Sacrifice [Fire] 1 ใบ; สั่ง [S] โจมตีโดยไม่ต้องจ่าย Mp ค่าโจมตี (Mp 0)
	{card_skill,
			s2_fire_no110_s1a, 622, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],
								y, [{line,1}, {zone, [arena_zone]}], 	
									y, controller, [arena_zone], seal, y, [{elem, 4}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{elem, 4}, {protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, sacrifice}]}, 0,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s2_fire_no110_s1b, 622, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],
								y, [{line, 1}, {zone, [arena_zone]}], 	
									y, controller, [arena_zone], seal, y, [{elem, 4}, {protect_skill, n}], 1,
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{assign_atk, once}]}, 0,
													n, null, [null], null, null, [],
														[] ,null,
															n, nul, [null], null, null, [],
																[], null
	},
	%[Skill]-ทิ้งการ์ด Seal 1 ใบในมือผู้ใช้ Skill จากนั้นผู้ใช้ Skill จั่วการ์ดตาม Mp ค่าร่ายของ Seal นั้น (Mp 1)
	{card_skill,
			s2_dark_no110_s1a, 623, 1, 1, n,
				y, 
					[{then_do, [s2_dark_no110_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [hand_cards], seal, null, [], 1,			                        
										n, {}, null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [],
														{player_select_exact_target, 1, [{player_action, {discard_collect, target}}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s2_dark_no110_s1b, 623, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [seal_deck, mystic_deck], all, y, [], 1,			                        
										n, {}, null,
											y, controller, {do_not_need_select, 0, [{draw_card, {target_erase, mc}}]}, 0,										
												n, [], null, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null	
	}
].