%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(s_skill_set1).
-compile(export_all).

light_skill() ->
	[
%[Skill]-ทิ้ง Mystic Card 1 ใบในมือผู้ใช้ Skill;  
		{card_skill,
			s1_light_no004_s1a, 260, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {{null, [arena_zone], mystic, null}, {[], 1}}], 											
									y, controller, [hand_cards], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [hand_cards], mystic, n, [],
														{player_select_exact_target, 1, [{player_action, discard}]} ,0,
															n, null, [null], null, null, [],
																[], null	
		},
		%ทำลาย Mystic Card 1 ใบในสนาม (Mp 2)
		{card_skill,
			s1_light_no004_s1b, 260, 1, 2, n,
				y, 
					null, null, 
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {{controller, [hand_cards], mystic, n}, {[], 1}}], 											
									y, null, [arena_zone], mystic, null, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], mystic, null, [],
														{player_select_exact_target, 1, [{action, destroy}]} ,0,
															n, null, [null], null, null, [],
																[], null
		},
%[Skill]–นำ Mystic Card 1 ใบใน Shrine ผู้ใช้ Skill กลับขึ้นมือ
		{card_skill,
			s1_light_no005_s1a, 261, 1, 2, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}],											
									y, controller, [shrine_cards], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [shrine_cards], mystic, n, [],
														{player_select_exact_target, 1, [{action, move_to_hand}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
%เมื่อ Mystic Card นั้นตก Shrine นำออกจากเกม
		{card_skill,
			s1_light_no005_s1b, 261, 1, 2, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 																						
									y, controller, [shrine_cards], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [shrine_cards], mystic, n, [],
														{{depend_on, s1_light_no005_s1a}, 0, [{move, to_remove_zone}]}, when_to_shrine,
															n, null, [null], null, null, [],
																[] ,null
		},
% เมื่อจบ Subturn ถ้าไม่ได้ใช้ Mystic Card นั้น นำ Mystic Card นั้นออกจากเกม เมื่อ [S] รวมร่าง
		{card_skill,
			s1_light_no005_s1c, 261, 1, 2, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}],								
									y, controller, [shrine_cards], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [shrine_cards], mystic, n, [],
														{{depend_on, s1_light_no005_s1a}, 0, [{move, to_remove_zone}]}, end_of_subturn_if_not_use,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]-ทำลาย Mystic Card 1 ใบในสนาม เมื่อ [S] รวมร่างกับ [Light] (Mp 2)
		{card_skill,
			s1_light_no008_s1, 264, 1, 2, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {elem, 6}}], 											
									y, null, [arena_zone], mystic, n, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], mystic, n, [{protect_skill, n}],
														{player_select_exact_target, 1, [{action, destroy}]}, 0,
															n, null, [null], null, null, [],
																[], null
		},
%[Skill]–นำ Mystic Card 1 ใบใน Shrine ผู้ใช้ Skill ออกจากเกม เมื่อ [S] รวมร่าง (Mp 1)
		{card_skill,
			s1_light_no010_s1, 266, 1, 1, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, controller, [shrine_cards], mystic, n, [], 1,			                        		                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [shrine_cards], mystic, n, [],
														{player_select_exact_target, 1, [{action, to_remove_zone}]} , 0,
															n, null, [null], null, null, [],
																[], null
		},
%รักษา Curse 1 ชนิดให้กับ Seal 1 ใบ (Mp 1)
		{card_skill,
			s1_light_no013_s1, 269, 1, 1, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{heal_curse, {select, 1}}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]-รักษา Curse 1 ชนิดให้กับ Seal ทุกใบในสนาม เมื่อ [S] รวมร่าง (Mp 3)
		{card_skill,
			s1_light_no013_s2, 269, 2, 3, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [],	null,										
												n, [], null, 
													y, null, [null], seal, y, [{curse, y}, {protect_skill, n}],
														{do_not_need_select, 0, [{heal_curse, {select, 1}}]} ,0,
															n, null, [null], null, null, [],
																[], null
		},
		%[Skill]-รักษา Curse ทุกชนิดให้กับ Seal 1 ใบ เมื่อ [S] รวมร่างกับ [Light] ~ (Mp 3);
		{card_skill,
			s1_light_no111_s1, 366, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, d}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{heal_curse, [all]}]} ,0,
															n, null, [null], null, null, [],
																[], null	
		},
		%[Titan] 1 ใบสูญเสีย 1 Charge Counter (Mp 0)
		{card_skill,
			s1_light_no122_s1, 378, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, n, [{type, "Titan"}, {counter, {more_than, 0}}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, n, [{type, "Titan"}, {counter, {more_than, 0}}],
														{player_select_exact_target, 1, [{counter, -1}]} ,0,
															n, null, [null], null, null, [],
																[], null	
		},
		%Seal 1 ใบไม่สามารถใช้ Skill ได้ 1 Turn เมื่อ [S] รวมร่าง (Mp 2)
		{card_skill,
			s1_light_no122_s2, 378, 2, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [], 1, %{have_skill, y}	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [], % {have_skill, y}
														{player_select_exact_target, 1, [{skill, {cannot_use, [all]}}]}, 2,
															n, null, [null], null, null, [],
																[], null	
		}
	].
	
earth_skill() ->
	[
		%[Skill]-ทำลาย Seal ที่ติด Stone Curse 1 ใบ (At Line) (Mp 3)
		{card_skill,
			s1_earth_no016_s1, 272, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{curse, stone_curse}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{curse, stone_curse}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, destroy}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal ใบอื่น 1 ใบ +Df ตาม Mp ค่าร่ายของ Seal นั้นจนจบ Subturn ?(Mp 2)
		{card_skill,
			s1_earth_no017_s1, 273, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, n, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, n, [{protect_skill, n}],
														{player_select_exact_target, 1, [{df, {'+', select_seal_mp}}]}, 1,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 ใบที่มี Sp 1, 2, 3, 4 ติด Stone Curse และ Poison Curse 2 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 3)
		{card_skill,
			s1_earth_no018_s1, 274, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "1234"}, {protect_curse, {n, stone_curse}}, {protect_curse, {n, poison_curse}}, {curse, {n, stone_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "1234"}, {protect_curse, {n, stone_curse}}, {protect_curse, {n, poison_curse}}, {curse, {n, stone_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, stone_curse}, {curse, poison_curse}]}, 4,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 ใบติด Dimension Curse 1 Turn เมื่อ [S] รวมร่างกับ [Light] (Mp 3)
		{card_skill,
			s1_earth_no020_s1, 276, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {elem, 6}}], 											
									y, null, [arena_zone], seal, y, [{protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, dimension_curse}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 ใบป้องกัน Curse 1 Turn (Mp 1)
		{card_skill,
			s1_earth_no029_s1, 285, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{protect_curse, [all]}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]- [Earth] 1 ใบใช้ Df เทียบขณะต่อสู้ได้ 1 Turn  (Mp 2)
		{card_skill,
				p1_earth_no113_s1, 369, 1, 2, n,
					y, 
						null, null,	
							n, [],
								n, null, [],									
									y, [{zone, [arena_zone]}], 											
										y, null, [arena_zone], seal, y, [{elem, 1}, {protect_skill, n}], 1,			                        
											n, [], null,
												n, null, [], null,										
													n, [], null, 
														y, null, [arena_zone], seal, y, [{elem, 1}, {protect_skill, n}],
															{player_select_exact_target, 1, [{combat, {when_fight_attack, {df, power}}}, {combat, {when_fight_target, {power, df}}}]} , 2,
																n, null, [null], null, null, [],
																	[], null	
		},
		%[Skill]- Seal 1 ใบที่มี sp 0, 3, 4 ติด Stone Curse 1 Turn เมื่อ [S] รวมร่าง (Mp 2)
		{card_skill,
				p1_earth_no113_s2, 369, 2, 2, n,
					y, 
						null, null,	
							n, [],
								n, null, [],									
									y, [{zone, [arena_zone]}, {combine, y}], 											
										y, null, [arena_zone], seal, y, [{skill_target_speed, "034"}, {curse, {n, stone_curse}}, {protect_curse, {n, stone_curse}}, {protect_skill, n}], 1,			                        
											n, [], null,
												n, null, [], null,										
													n, [], null, 
														y, null, [arena_zone], seal, y, [{skill_target_speed, "034"}, {curse, {n, stone_curse}}, {protect_curse, {n, stone_curse}}, {protect_skill, n}],
															{player_select_exact_target, 1, [{curse, stone_curse}]} , 2,
																n, null, [null], null, null, [],
																	[], null	
		}
	].

fire_skill() ->
	[
		%[Skill]–Sacrifice Seal 1 ใบ; 
		{card_skill,
			s1_fire_no031_s1a, 287, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								%y, [{line, 1}, {other_seal_arena, {[{elem, 4}], 1}}],
								y, [{line, 1}, {{null, [arena_zone], seal, n}, {[{elem, 4}], 1}}],
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, sacrifice}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%Seal ทุกใบฝ่ายผู้ใช้ Skill At +1 จนจบ Subturn เมื่อมี [Fire] ใบอื่นในสนาม (At Line) (Mp 1) 
		{card_skill,
			s1_fire_no031_s1b, 287, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {{null, [arena_zone], seal, n}, {[{elem, 4}], 1}}], 											
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],													
														{do_not_need_select, 0, [{at, 1}]}, 1,
															n, null, [null], null, null, [],
																[], null
		},
%[Skill]-Sacrifice Seal 1 ใบ;   
		{card_skill,
			s1_fire_no035_s1a, 291, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, {sacrifice_collect, {target, mc}}}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
%Seal 1 ใบ +At ตาม Mp ค่าร่ายของ Seal ที่ Sacrifice 1 Turn (Mp 2) 
		{card_skill,
			s1_fire_no035_s1b, 291, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}],
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{at, {'+', {get_erase, mc}}}]}, 2 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 ใบ At +1 จนจบ Subturn (Mp 1)
		{card_skill,
			s1_fire_no041_s1, 297, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{at, 1}]}, 1, 
															n, null, [null], null, null, [],
																[] ,null
		},
		%Seal 1 ใบที่มี Sp 3, 4, 5 ติด Last Dance Curse At + 3 / 2 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 2)
		{card_skill,
			s1_fire_no043_s1, 299, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, 3}}}]}, 4, 
															n, null, [null], null, null, [],
																[] ,null
		}
	].

water_skill() ->
	[
%[Skill]-นำ Seal ที่ติด Freeze Curse 1 ใบขึ้นมือ (At Line) (Mp 1)
		{card_skill,
			s1_water_no048_s1, 304, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{curse, freeze_curse}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, [], null, 
													y, null, [arena_zone], seal, y, [{curse, freeze_curse}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, move_to_hand}]}, 0 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]–Seal 1 ใบในสนาม Mp ค่าใช้ Skill +1 / 1 Turn (Mp 1)  
		{card_skill,
			s1_water_no052_s1, 308, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{ms, 1}]}, 2 ,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]-ทิ้ง [Machine] 1 ใบในมือผู้ใช้ Skill; 
		{card_skill,
			s1_water_no054_s1a, 310, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [hand_cards], seal, null, [{type, "Machine"}], 1,			                        			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [hand_cards], seal, null, [{type, "Machine"}],
														{player_select_exact_target, 1, [{player_action, {discard_collect, {target, mc}}}]}, 0 ,
															n, null, [null], null, null, [],
																[] ,null
		},
%ผู้ใช้ Skill + Mp ตาม Mp ค่าร่าย ของ [Machine] ใบนั้น (Mp 0)
		{card_skill,
			s1_water_no054_s1b, 310, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}],
									y, controller, [hand_cards], seal, null, [{type, "Machine"}], 1, 
										n, {}, null,
											y, controller, {do_not_need_select, 0, [{mp, {'+', {get_erase, mc}}}]}, 0,										
												n, [], null, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null 
		},
%[Skill]-นำ Seal 1 ใบที่มี Lv 1 เข้ามาในสนามจากมือผู้ใช้ Skill (Mp 1)
		{card_skill,
			s1_water_no055_s1, 311, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}],
									y, controller, [hand_cards], seal, null, [{level, 1}], 1,		                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [hand_cards], seal, null, [{level, 1}],
														{player_select_exact_target, 1, [{action, move_to_arena}]}, 0 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]–Seal 1 ใบที่มี Sp 2, 3, 4 ติด Poison Curse 1 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 2)
		{card_skill,
			s1_water_no057_s1, 313, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 2 ,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]–ผู้ใช้ Skill สั่ง [S] แยกการรวมร่าง ? (Mp 2)
		{card_skill,
			s1_water_no058_s1, 314, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {card_type, is_seal}}, {protect_skill, n}], 											
									n, null, [null], null, null, [], null,			                        
										n, {}, null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{player_action, assign_break_combine}]}, 0, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null 
		},
		%[Skill]–Seal 1 ใบที่มี Sp 3, 4 ติด Freeze Curse 2 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
		{card_skill,
			s1_water_no060_s1, 316, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "34"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "34"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, 4,  
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]- Seal 1 ใบที่มี Df น้อยกว่า [S] ติด Freeze Curse 1 Turn เมื่อ [S] รวมร่าง (At Line)(Mp 2)
		{card_skill,
				p1_water_no116_s1, 372, 1, 2, n,
					y, 
						null, null,	
							n, [],
								n, null, [],									
									y, [{line, 1}, {combine, y}], 											
										y, null, [arena_zone], seal, n, [{defend, less_than_s}, {curse, {n, freeze_curse}}, {protect_curse, {n, freeze_curse}}, {protect_skill, n}], 1,			                        
											n, [], null,
												n, null, [], null,										
													n, [], null, 
														y, null, [arena_zone], seal, n, [{defend, less_than_s}, {curse, {n, freeze_curse}}, {protect_curse, {n, freeze_curse}}, {protect_skill, n}],
															{player_select_exact_target, 1, [{curse, freeze_curse}]} , 2,
																n, null, [null], null, null, [],
																	[], null	
		},
		%[Skill]–Seal 1 ใบที่มี Sp 2, 3, 4, 5 ติด Freeze Curse 2 Turn เมื่อ [S] รวมร่าง (Mp 3)
		{card_skill,
			s1_water_no121_s1, 377, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, 4,  
															n, null, [null], null, null, [],
																[] ,null
		}
	].
	
wind_skill() ->
	[
		%[Skill]–Seal 1 ใบในสนาม Mp +1 / 1 Turn (Mp 0) 
		{card_skill,
			s1_wind_no062_s1, 318, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{ms, 1}, {ma, 1}, {mc, 1}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]-Seal 1 ใบที่มี Df น้อยกว่า [S] สามารถโจมตีข้ามไปยัง Df Line ได้จนจบ Subturn (At Line) (Mp2)
		{card_skill,
			s1_wind_no064_s1, 320, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{defend, less_than_s}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{defend, less_than_s}, {protect_skill, n}],
														{player_select_exact_target, 1, [{attack, to_df}]}, 1,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]- [S] และ Seal 1 ใบฝ่ายผู้ใช้ Skill เปลี่ยน Line ? (Mp3) (ผลจาก Skill  นี้ไม่นับว่าเป็นการกำหนด Line)
		{card_skill,
			s1_wind_no064_s2, 320, 2, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y ,[{zone, [arena_zone]}, {can_move_to, any}, {protect_skill, n}], 											
									y, controller, [arena_zone], seal, n, [{protect_skill, n}, {can_move_to, any}, {line, null}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, change_line}]}, 0, 
													y, controller, [arena_zone], seal, n, [{protect_skill, n}, {can_move_to, any}, {line, null}],
														{player_select_exact_target, 1, [{action, change_line}]}, 0,  
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]-นำ Seal 2 ใบในสนามที่มี Sp น้อยกว่า [S] ไปที่ At Line (At Line) (Mp3)(ผลจาก Skill  นี้ไม่นับว่าเป็นการกำหนด Line)
		{card_skill,
			s1_wind_no065_s1, 321, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, n, [{line, 0}, {can_move_to, 1}, {skill_target_speed, less_than_s}, {protect_skill, n}], 2,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, n, [{line, 0}, {can_move_to, 1}, {skill_target_speed, less_than_s}, {protect_skill, n}],
														{player_select_exact_target, 2, [{action, change_line}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]-เมื่อผู้เล่นฝ่ายตรงข้ามสั่ง Seal รวมร่าง นำ [S] เข้ามาที่ At Line จากมือ จากนั้นสั่ง [S] โจมตี Seal ที่กำลังรวมร่าง ? (Mp 4)
		{card_skill,
			s1_wind_no066_s1a, 322, 1, 4, y,
				y, 
					[{then_assign, [s1_wind_no066_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{pre_zone, [hand_cards]}], 											
									y, opponent, [arena_zone], seal, null, [{action, being_combine}], 1,			                        
										n, [], null, 
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_at_line}]}, 0,
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null  
		},
%จากนั้นสั่ง [S] โจมตี Seal ที่กำลังรวมร่าง 
		{card_skill,
			s1_wind_no066_s1b, 322, 1, 4, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, opponent, [arena_zone], seal, null, [{action, being_combine}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{assign_atk, to_seal_being_combine}]}, 0, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null  
		},
%[Skill]–Seal 1 ใบฝ่ายผู้ใช้ Skill เปลี่ยน Line เมื่อ [S] รวมร่าง? (Mp 3) (ผลจาก Skill  นี้ไม่นับว่าเป็นการกำหนด Line)
		{card_skill,
			s1_wind_no067_s1, 323, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, controller, [arena_zone], seal, y, [{protect_skill, n}, {can_move_to, any}, {line, null}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}, {can_move_to, any}, {line, null}],
														{player_select_exact_target, 1, [{action, change_line}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
%[Skill]-สั่ง [S] โจมตี 2 ครั้ง
	%-	ครั้งที่ 1 At = 9 
	%-	ครั้งที่ 2 At ปกติของ [Dragon] ที่เป็น Seal  ใบรองรวมร่างของ [S] 
		{card_skill,
			s1_wind_no068_s1, 324, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {type, "Dragon"}}, {protect_skill, n}], 																						
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{assign_atk, {once_with_at, 9}}, {assign_atk, once_with_dragon_supporter_at}]}, 0,
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null  
		},
	%[Skill]-ทำลาย Seal ที่ไม่ได้รวมร่าง 1 ใบที่มี Lv1 (At Line) (Mp 3)
		{card_skill,
			s1_wind_no069_s1, 325, 1, 3, n, 
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{combine, n}, {level, 1}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{combine, n}, {level, 1}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, destroy}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
	%[S] แยกการรวมร่าง ? (Mp 2)
		{card_skill,
			s1_wind_no111_s1, 367, 1, 2, y, 
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {card_type, is_seal}}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, break_combine}]}, null, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[] ,null
		},
	%Seal 1 ใบในสนาม Sp +2 / 1 Turn เมื่อ [S] รวมร่าง ? (Mp 2)
		{card_skill,
			s1_wind_no124_s1, 380, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{sp, 2}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		},
	%Seal 1 ใบในสนาม Sp -3 / 1 Turn เมื่อ [S] รวมร่าง ? (At Line) (Mp 2)
		{card_skill,
			s1_wind_no124_s2, 380, 2, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}, {line, 1}], 											
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{sp, -3}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		}
	].

dark_skill() ->
	[
	%[Skill]- [S] +At ตามจำนวน [Dark] ใน Shrine ผู้ใช้ Skill 1 Turn จากนั้นสั่ง [S] โจมตี (At Line) (Charge 2) (Mp 3)
		{card_skill,
			s1_dark_no077_s1a, 333, 1, {3,2}, n,
				y, 
					[{then_assign, [s1_dark_no077_s1b]}], null,
						n, [],
							n, null, [],									
								y, [{line, 1}, {protect_skill, n}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{at, {'+', {{owner, owner, [shrine_cards], seal, null}, [{elem, 5}]}}}]}, 2, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null
		},
	%จากนั้นสั่ง [S] โจมตี (At Line)
		{card_skill,
			s1_dark_no077_s1b, 333, 1, {3,2}, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {protect_skill, n}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{assign_atk, once}]}, 0,
													n, null, [null], null, null, [],
														[] ,null,
															n, nul, [null], null, null, [],
																[], null
		},
		%[Skill] – Seal 2 ใบติด Poison Curse 2 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 4)
		{card_skill,
			s1_dark_no078_s1, 334, 1, 4, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 2,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 2, [{curse, poison_curse}]}, 4,
															n, nul, [null], null, null, [],
																[] ,null
		},
	%[Skill]–ทำลาย Seal  ที่ติด Curse 1 ใบ เมื่อ [S] รวมร่าง (At Line) (Mp 3) 
		{card_skill,
			s1_dark_no079_s1, 335, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, destroy}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
	%[Skill]–นำ Mystic Card ชนิด PS 1 ใบใน Shrine ผู้ใช้ Skill มาติดที่ [S] เมื่อ Mystic Card นั้นตก Shrine นำ Mystic Card นั้นออกจากเกม (Mp 2) 
		{card_skill,
			s1_dark_no081_s1a, 337, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [shrine_cards], mystic, null, [{paste_type, 1}, {can_paste_to_seal, self}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [shrine_cards], mystic, null, [{paste_type, 1}, {can_paste_to_seal, self}],
														{player_select_exact_target, 1, [{action, attach_to_s}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		{card_skill,
			s1_dark_no081_s1b, 337, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [shrine_cards], mystic, null, [{paste_type, 1}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, controller, [shrine_cards], mystic, null, [{paste_type, 1}],
														{{depend_on, s1_dark_no081_s1a}, 0, [{move, to_remove_zone}]}, when_to_shrine,
															n, null, [null], null, null, [],
																[], null
		},
	%[Skill]–Seal 1 ใบ และ [S] ติด Poison Curse 1 Turn เมื่อ [S] รวมร่าง (At Line) (Mp3)
		{card_skill,
			s1_dark_no084_s1, 340, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 											
									y, null, [arena_zone], seal, n, [{protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{curse, poison_curse}]}, 2, 
													y, null, [arena_zone], seal, n, [{protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 2,
															n, null, [null], null, null, [],
																[] , null
		},
		%[Skill]-Seal ที่ไม่ใช่ [Light] 1 ใบที่มี Sp 1, 2, 3, 4, 5 ติด Charm Curse 1 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
		{card_skill,
			s1_dark_no085_s1, 341, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}],											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {elem, {n, 6}}, {protect_curse, {n, charm_curse}}, {curse, {n, charm_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {elem, {n, 6}}, {protect_curse, {n, charm_curse}}, {curse, {n, charm_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, charm_curse}]}, 2,
															n, null, [null], null, null, [],
																[] , null
		},
		%[Skill] – สั่ง [S] โจมตี 3 ครั้งโดยไม่ต้องจ่าย Mp ค่าโจมตี (At Line) (Charge3) (Mp 3)
		{card_skill,
			s1_dark_no086_s1, 342, 1, {3, 3}, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {protect_skill, n}], 											
									n, null, [null], null, n, [], null,			                        
										n, [], null,
											n, null, [], null,										 
												y, {do_not_need_select, 0, [{assign_atk, once}, {assign_atk, once}, {assign_atk, once}]}, 0, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
		}
	].
	
m_skill() ->
	[
		%[Skill]-Sacrifice Seal 1 ใบ;
		{card_skill,
			m1_no094_s1a, 350, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, null, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, null, [{protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, {sacrifice_collect, {target, mc}}}]} ,0,
															n, null, [null], null, null, [],
																[], null	
		},
		%เรา +Mp ตาม Mp ค่าร่ายของ Seal นั้น (Mp 0)
		{card_skill,
			m1_no094_s1b, 350, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, null, [], 1,			                        
										n, {}, null,
											y, controller, {do_not_need_select, 0, [{mp, {'+', {get_erase, mc}}}]}, 0,										
												n, [], null, 
													n, null, [null], null, null, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
		}
	].
	
test() ->	
	[{card_skill, 
			skill_id, card_id, skill_no, skill_mp, can_interfere,
				skill_condition_need_check, 
					then_assign, then_do,
						playerown_must_check, playerown_check,
							player_must_check, player_side_check, player_check,									
								owner_must_check, owner_check, 											
									other_must_check, other_player_check, other_present_check, other_card_type_check, other_self_include_check, other_check, other_match_count,			                        
										playerown_have_effect, playerown_effect, playerown_duration_effect,
											player_have_effect, player_which_got_effect, player_effect,	player_duration_effect,										
												owner_have_effect, owner_effect, owner_duration_effect, 
													other_target_have_effect, target_player_check, target_present_check, target_card_type_check, target_self_include_check, target_check,
														other_effect ,other_duration_effect,
															or_target_have_effect, or_target_player_check, or_target_present_check, or_target_card_type_check, or_self_include_check, or_check,
																or_result_effect, or_duration
			}].
	

