%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(s_skill_set3).
-compile(export_all).

light_skill() ->
[
	%001 War Horn Unicorn
	%1. [Skill]–Seal 1 ใบที่มี Sp 3, 4, 5 ติด Dimension Curse 1 Turn เมื่อ [S] รวมร่างกับ [Light] (At Line) (Mp 2)
	{card_skill,
			s3_light_no001_s1, 769, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 6}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_skill, n}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "345"}, {protect_skill, n}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}],
														{player_select_exact_target, 1, [{curse, dimension_curse}]}, 2,
															n, null, [], null, null, [],
																{}, null
	},	
	%002 Beta - B
	%1. [Skill]–ดู Mystic Card ทุกใบในมือฝ่ายตรงข้ามเมื่อ [S] รวมร่าง ? (At Line) (Mp 2)
	{card_skill,
			s3_light_no002_s1, 770, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, opponent, [hand_cards], mystic, null, [], 1,			                        
										y, {do_not_need_select, 0, [{player_action, {show_opponent_card, mystic}}]}, null,
											n, null, {}, null,										
												n, {}, null, 
													n, null, [], null, null, [],
														{} , null,
															n, null, [null], null, null, [],
																{}, null	
	},
	%003 Angel of Sword
	%[Skill]-นำ [S] ขึ้นมือจากสนาม เมื่อ [S] ไม่รวมร่าง (Mp 2)
	{card_skill,
			s3_light_no003_s1, 771, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, n}, {protect_skill, n}], 											
									n, null, [], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_hand}]}, 0, 
													n, null, [], null, null, [],
														[], null,
															n, null, [], null, null, [],
																[], null	
	},
	% 004 Sweetbrier Alraune
	%1. [Skill]-Seal 1 ใบที่มี Sp 1, 2, 3, 4, 5 ติด Dimension Curse 2 Turn เมื่อ [S] มี [Light] เป็น Seal ใบรองรวมร่าง (At Line) (Mp 3)
	{card_skill,
			s3_light_no004_s1, 772, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 6}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {protect_skill, n}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "12345"}, {protect_skill, n}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}],
														{player_select_exact_target, 1, [{curse, dimension_curse}]}, 4,
															n, null, [], null, null, [],
																[], null	
	},
	% 004 Sweetbrier Alraune
	%%%%%%%%%2. [Skill]-[Plant] ทุกใบในสนามฝ่ายผู้ใช้ Skill ยกเลิก Ability ของ Seal ฝ่ายตรงข้ามของ [Plant] ใบนั้น 1 Turn (Mp 2)
	{card_skill,
			s3_light_no004_s2, 772, 2, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, owner, [arena_zone], seal, y, [{protect_skill, n}, {type, "Plant"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, owner, [arena_zone], seal, y, [{protect_skill, n}, {type, "Plant"}],
														{do_not_need_select, 1, [{cancel_ability, [all_opponent]}]}, 2,
															n, null, [], null, null, [],
																[], null	
	},
	% 005 Alazertus
	%1. [Skill]-Seal ใบอื่นทุกใบในสนามสูญเสีย Charge Counter ทั้งหมด จากนั้น [S] ได้รับ Charge Counter ตามจำนวน Charge Counter ที่สูญเสียไปนั้น  (Mp)
	{card_skill,
			s3_light_no005_s1a, 773, 1, 2, n,
				y, 
					[{then_do, [s3_light_no005_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}],
									y, null, [arena_zone], seal, n, [{counter, {more_than, 0}}, {protect_skill, n}], 1,
										n, [], null,
											n, null, [], null,
												n, {}, null,
													y, null, [arena_zone], seal, n, [{counter, {more_than, 0}}, {protect_skill, n}],
														{do_not_need_select, 0, [{counter, loose_all_and_put_all_loose_counter}]}, null,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_light_no005_s1b, 773, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}], 											
									n, null, [], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{counter, add_all_other_loose_counter}]}, null, 
													n, null, [], null, null, [],
														[], null,
															n, null, [], null, null, [],
																[], null	
	},
	% 006 Blue Wing Pegasus
	%1. [Skill]-นำ [Beast] 1 ใบเข้ามาในสนามจากมือผู้ใช้ Skill (Mp 2)  
	{card_skill,
			s3_light_no006_s1, 774, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [hand_cards], seal, null, [{type, "Beast"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, null, [{type, "Beast"}],
														{player_select_exact_target, 1, [{action, move_to_arena}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 008 Rune Unicorn
	%1. [Skill]-[Beast] ใบอื่นฝ่ายผู้ใช้ Skill ยกเลิก Mystic Card จนจบ Subturn (At Line)
	{card_skill,
			s3_light_no008_s1, 776, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, controller, [arena_zone], seal, n, [{type, "Beast"}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, n, [{type, "Beast"}, {protect_skill, n}],
														{do_not_need_select, 0, [{cancel_mystic, [all]}]}, end_of_subturn,
															n, null, [], null, null, [],
																[], null	
	},
	% 009 Naos Viper
	%1. [Skill]–Seal 1 ใบที่มี Sp 2, 3, 4 ติด Dimension Curse และ Poison Curse 2 Turn เมื่อ [S] รวมร่างกับ [Water] (At Line) (Mp 3)
	{card_skill,
			s3_light_no009_s1, 777, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 2}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_skill, n}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, dimension_curse}}, {curse, {n, dimension_curse}}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}],
														{player_select_exact_target, 1, [{curse, poison_curse}, {curse, dimension_curse}]}, 4,
															n, null, [], null, null, [],
																[], null	
	},
	% 010 Angel of Rune
	%1. [Skill]–ผู้เล่นฝ่ายตรงข้าม 1 คนทิ้ง Mystic Card 1ใบในมือ เมื่อ [S] รวมร่าง (At Line) (Mp 2)
	{card_skill,
			s3_light_no010_s1, 778, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, opponent, [hand_cards], mystic, null, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, opponent, [hand_cards], mystic, null, [],
														{opponent_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 012 Albono Unicorn
	%1. [Skill]–รักษา Curse ทุกชนิดให้กับ N[Unicorn] 1ใบ (Mp 1)
	{card_skill,
			s3_light_no012_s1, 780, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{naming, "Unicorn"}, {curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{naming, "Unicorn"}, {curse, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{heal_curse, [all]}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 014 Golden Horn Unicorn
	%1. รักษา Curse ทุกชนิดให้กับ Seal 1 ใบ (Mp 1)  
	{card_skill,
			s3_light_no014_s1, 782, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{heal_curse, [all]}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	%[Skill]–นำ [S] เข้ามาในสนามจากมือ จากนั้นสั่ง [S] รักษา Curse ทุกชนิดให้กับ N[Pegasus] 1 ใบ ? (Mp 3)
	{card_skill,
			s3_light_no015_s1a, 783, 1, 3, y,
				y, 
					[{then_do, [s3_light_no015_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [hand_cards]}], 											
									n, null, [], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_arena}]}, null, 
													n, null, [], null, null, [],
														[], null,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_light_no015_s1b, 783, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, null, [{naming, "Pegasus"}, {curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, null, [{naming, "Pegasus"}, {curse, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{heal_curse, [all]}]}, 0,
															n, null, [], null, null, [],
																[], null	
	}
].

earth_skill() ->
[
	% 018 Grand Hill Pegasus
	%1. [Skill]–นำ [S] เข้ามาในสนามจากมือ จากนั้น N[Pegasus] ใบอื่น 1 ใบฝ่ายผู้ใช้ Skill  ป้องกันการโจมตีและการทำลายจากการสวนกลับจนจบ Subturn ? (Mp 5)
	{card_skill,
			s3_earth_no018_s1a, 786, 1, 5, y,
				y, 
					[{then_do, [s3_earth_no018_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [hand_cards]}], 											
									n, null, [], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_arena}]}, null, 
													n, null, [], null, null, [],
														[], null,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_earth_no018_s1b, 786, 1, 5, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, n, [{naming, "Pegasus"}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, n, [{naming, "Pegasus"}, {protect_skill, n}],
														{player_select_exact_target, 1, [{protect_attack, [all]}, {protect_attack, [counter_attack]}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 019 Hill Harpy
	%1. [Skill]–Seal 1 ใบ ที่มี Sp น้อยกว่า [S]  ติด Stone Curse ? Turn เมื่อมี [Earth] ใบอื่นในสนาม (At Line) (Mp 2)
	{card_skill,
			s3_earth_no019_s1, 787, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1},  {{null, [arena_zone], seal, n}, {[{elem, 1}], 1}}], 											
									y, null, [arena_zone], seal, n, [{skill_target_speed, less_than_s}, {protect_curse, {n, stone_curse}}, {curse, {n, stone_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, n, [{skill_target_speed, less_than_s}, {protect_curse, {n, stone_curse}}, {curse, {n, stone_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, stone_curse}]}, infinite,
															n, null, [], null, null, [],
																[], null	
	},
	% 021 Great Horn Unicorn
	%1 [Skill]–ย้ายเป้าหมายการโจมตีของ Seal 1 ใบที่มีเป้าหมายไปที่ N[Unicorn] ฝ่ายผู้ใช้ Skill ไปที่ [S] ? (At Line) (Mp 3)
	{card_skill,
			s3_earth_no021_s1, 789, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, controller, [arena_zone], seal, y, [{naming, "Unicorn"}, {action, attacked}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, uncontrol, [arena_zone], seal, null, [{action, attacker}, {protect_skill, n}],
														{do_not_need_select, 0, [{move_attack_target, to_s}]}, after_affect,
															n, null, [], null, null, [],
																[], null	
	},
	% 022 Death Guardian of Ruin
	%1. [Skill]–เลือก 1 ธาตุ Seal 1 ใบเปลี่ยนธาตุเป็นธาตุที่เลือก 1 Turn เมื่อ [S] รวมร่าง (Mp 3)
	{card_skill,
			s3_earth_no022_s1, 790, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}], 											
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{elem, {select, 1}}]}, 2,
															n, null, [], null, null, [],
																[], null	
	},
	% 022 Death Guardian of Ruin
	%2. [Skill]–เลือก 1 ธาตุ Seal 1 ใบฝ่ายผู้ใช้ Skill เปลี่ยนธาตุเป็นธาตุที่เลือก 1 Turn เมื่อ [S] รวมร่าง ? (Mp 3)  
	{card_skill,
			s3_earth_no022_s2, 790, 2, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}], 											
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{elem, {select, 1}}]}, 2,
															n, null, [], null, null, [],
																[], null	
	},
	% 024 Grace, the Valkyrie
	%1. [Skill]-แสดง [Beast] 1 ใบจากกองการ์ด Seal ผู้ใช้ Skill แล้วนำขึ้นมือ (Mp 2)  
	{card_skill,
			s3_earth_no024_s1, 792, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [seal_deck], all, null, [{type, "Beast"}], 1,			                        
										n, [], null,
											n, null, [], null,
												n, {}, null,
													y, controller, [seal_deck], all, null, [{type, "Beast"}],
														{player_select_exact_target, 1, [{player_action, player_reveal}, {player_action, move_to_hand}]}, 0,
															n, null, [], null, null, [],
																[], null
	},
	% {card_skill,
			% s3_earth_no024_s1b, 792, 1, 2, n,
				% y, 
					% null, null,
						% n, [],
							% n, null, [],
								% y, [{zone, [arena_zone]}], 											
									% y, owner, [seal_deck], all, null, [{type, "Beast"}], 1,
										% n, [], null,
											% n, null, [], null,
												% n, {}, null,
													% y, owner, [seal_deck], all, null, [{type, "Beast"}],
														% {{depend_on, s3_earth_no024_s1a}, 1, [{player_action, move_to_hand}]}, 0,
															% n, null, [], null, null, [],
																% [], null
	% },
	% 029 Golem Guardian
	%%%%% Require Change %%%%%%1. [Skill]– [S] สลับ At กับ Df 1 Turn (ผลที่ทำให้ At เปลี่ยนแปลงไปเปลี่ยนแปลง Df และผลที่ทำให้ Df เปลี่ยนแปลงไปเปลี่ยนแปลง At) ? (Mp 2)  
	{card_skill,
			s3_earth_no029_s1, 797, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}], 											
									n, null, [], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{swap_power, {attack, defend}}]}, 2, 
													n, null, [], null, null, [],
														{}, null,
															n, null, [], null, null, [],
																[], null	
	},
	% 033 Cocktrice
	%1. [Skill]-Seal 1 ใบที่มี Sp 1, 2, 3, 4 ติด Stone Curse 1 Turn เมื่อ [S] รวมร่าง (Mp 2) 
	{card_skill,
			s3_earth_no033_s1, 801, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "1234"}, {protect_curse, {n, stone_curse}}, {curse, {n, stone_curse}}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "1234"}, {protect_curse, {n, stone_curse}}, {curse, {n, stone_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, stone_curse}]}, 2,
															n, null, [], null, null, [],
																[], null	
	}
].

fire_skill() ->
[
	% 035 Flame Wing Pegasus
	%1. [Skill]–นำ [S] เข้ามาในสนามจากมือจากนั้น N[Pegasus] ใบอื่น 1 ใบ At +2 Df -2 จนจบ Subturn ? (Mp 3)
	{card_skill,
			s3_fire_no035_s1a, 803, 1, 3, y,
				y, 
					[{then_do, [s3_fire_no035_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{pre_zone, [hand_cards]}], 											
									y, null, [arena_zone], seal, n, [{naming, "Pegasus"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_arena}]}, null, 
													n, null, [null], null, null, [],
														{}, null,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_fire_no035_s1b, 803, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, n, [{naming, "Pegasus"}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, n, [{naming, "Pegasus"}, {protect_skill, n}],
														{player_select_exact_target, 1, [{at, 2}, {df, -2}]}, end_of_subturn,
															n, null, [], null, null, [],
																[], null	
	},
	% 038 Vivian Law
	%1. [Skill] – ทิ้ง [Machine] 1 ใบในมือผู้ใช้ Skill; ทำลาย Seal 1 ใบที่อยู่ใน At Line ที่มี At น้อยกว่า [S] เมื่อ [S] รวมร่าง (Mp 3)
	{card_skill,
			s3_fire_no038_s1a, 806, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}, {{null, [arena_zone], seal, n}, {[{line, 1}, {attack, less_than_s}], 1}}, {protect_skill, n}],
									y, controller, [hand_cards], seal, n, [{type, "Machine"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [hand_cards], seal, n, [{type, "Machine"}],
														{player_select_exact_target, 1, [{player_action, discard}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_fire_no038_s1b, 806, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, y}, {{controller, [hand_cards], seal, n}, {[{type, "Machine"}], 1}}], 											
									y, null, [arena_zone], seal, n, [{line, 1}, {attack, less_than_s}, {protect_skill, n}], 1,
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, n, [{line, 1}, {attack, less_than_s}, {protect_skill, n}],
														{player_select_exact_target, 1, [{action, destroy}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 040 Acatan
	%[Skill]-[S] At +2 จนจบ Subturn จากนั้นสั่ง [S] โจมตี (At Line) (Charge 2) (Mp 2)
	{card_skill,
			s3_fire_no040_s1a, 808, 1, {2, 2}, n,
				y, 
					[{then_assign, [s3_fire_no040_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {protect_skill, n}], 											
									y, uncontrol, [arena_zone], seal, n, [{protect_attack, {n, [all]}}], 1,
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{at, 2}]}, end_of_subturn, 
													n, null, [], null, null, [],
														{}, null,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_fire_no040_s1b, 808, 1, {2, 2}, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, uncontrol, [arena_zone], seal, n, [{protect_attack, {n, [all]}}], 1,
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{assign_atk, once}]}, 0, 
													n, null, [], null, null, [],
														{}, null,
															n, null, [], null, null, [],
																[], null	
	},
	% 042 FlareFairy
	%[Skill]–Sacrifice Seal 1 ใบ; นำ Seal 1 ใบใน Shrine ผู้ใช้ Skill ขึ้นมือ เมื่อ [S] รวมร่างกับ [Light] (At Line) (Mp 2)  
	{card_skill,
			s3_fire_no042_s1a, 810, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 6}}, {{controller, [arena_zone], seal, y}, {[{protect_skill, n}], 1}}], 											
									y, controller, [shrine_cards], seal, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{player_action, sacrifice}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_fire_no042_s1b, 810, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 6}}, {{controller, [arena_zone], seal, y}, {[{protect_skill, n}], 1}}], 											
									y, controller, [shrine_cards], seal, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [shrine_cards], seal, y, [],
														{player_select_exact_target, 1, [{action, move_to_hand}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 043 Scarlet Mane Unicorn
	%1. [Skill]-ผู้เล่นทุกคนสามารถนำ [Beast] 1 ใบเข้ามาในสนามจากมือ (Mp 2)
	{card_skill,
			s3_fire_no043_s1a, 811, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									n, null, [], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, owner, [hand_cards], seal, n, [{type, "Beast"}],
														{player_can_select_own_exact_target, 1, [{player_action, move_to_arena}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_fire_no043_s1b, 811, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									n, null, [], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, opponent, [hand_cards], seal, n, [{type, "Beast"}],
														{opponent_can_select_own_exact_target, 1, [{player_action, move_to_arena}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 046 Soul Stag
	%1. [Skill]–Sacrifice Seal ใบรองรวมร่างของ [S] 1 ใบ; รักษา Curse ทุกชนิดให้ Seal 1 ใบในสนาม ? (Mp 3) 
	{card_skill,
			s3_fire_no046_s1a, 814, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {card_type, is_seal}}],
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}], 1,
									%y, owner, [support_cards], seal, null, [{support_to, s}], 1,
										n, [], null,
											n, null, [], null,	
												n, {}, null, 
													y, owner, [support_cards], seal, null, [{support_to, s}],
														{player_select_exact_target, 1, [{player_action, sacrifice}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_fire_no046_s1b, 814, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {card_type, is_seal}}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{curse, y}, {protect_skill, n}],
														{player_select_exact_target, 1, [{heal_curse, [all]}]}, 0,
															n, null, [], null, null, [],
																[], null	
	}
].

water_skill() ->
[
	% 051 Phoaviros
	%[Skill]-Seal 1 ใบในสนามฝ่ายผู้ใช้ Skill สามารถใช้ Skill ได้แม้ Seal ที่เป็นเป้าหมายมี Sp ไม่ตรงตามเงื่อนไข 1 Turn (At Line) (Mp 1)	{card_skill,
	{card_skill,
			s3_water_no051_s1, 819, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, controller, [arena_zone], seal, y, [{protect_skill, n}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{skill, can_use_even_target_sp_mismatch}]}, 0,
															n, null, [], null, null, [],
																[], null	
	},
	% 054 Ocean Unicorn
	%1. [Skill]–Seal 1 ใบที่มี Sp 2, 3, 4 ติด Freeze Curse 1 Turn เมื่อ [S] รวมร่างกับ [Water] (At Line) (Mp 2)
	{card_skill,
			s3_water_no054_s1, 822, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 2}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, y, [{skill_target_speed, "234"}, {protect_curse, {n, freeze_curse}}, {curse, {n, freeze_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, 2,
															n, null, [], null, null, [],
																[], null	
	},
	% 056 Butterfly Stingray
	%1. [Skill]-สุ่มนำการ์ด 1 ใบในมือผู้เล่น 1 คนเข้ากองการ์ด จากนั้นผู้เล่นนั้นจั่วการ์ด 1 ใบ (Mp 2)
	{card_skill,
			s3_water_no056_s1a, 824, 1, 2, n,
				y, 
					[{then_do, [s3_water_no056_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [hand_cards], all, null, [], 1,	                        
										y, {player_select_exact_player, 1, [{player_action, {random_select, target_player, [hand_cards], 1, move_to_deck}}]}, 0,
											n, null, [], null,										
												n, {}, null, 
													n, null, [], null, null, [],
														[], null,
															n, null, [], null, null, [],
																[], null	
	},
	{card_skill,
			s3_water_no056_s1b, 824, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}],
									n, null, [null], null, null, [], null,	                        
										y, {{depend_on, s3_water_no056_s1a}, 1, [{draw_card, 1}]}, 0,
											n, null, [], null,										
												n, {}, null, 
													n, null, [], null, null, [],
														[], null,
															n, null, [], null, null, [],
																[], null	
	},
	%60. Ghost Ship
	%[Skill]-นำ [S] กลับเข้ากองการ์ด เมื่อ [S] อยู่ในท่า Double Combination (Mp 0) 
	{card_skill,
			s3_water_no060_s1, 828, 1, 0, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, d}, {protect_skill, n}],
									n, null, [null], null, null, [], null,	                        
										n, {}, null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_library}]}, null,
													n, null, [], null, null, [],
														[], null,
															n, null, [], null, null, [],
																[], null	
	}
].

wind_skill() ->
[
	% 064 Regina, Princess of Swards
	%1. [Skill]-ผู้เล่นทุกคนนำ Seal ทุกใบในสนามฝ่ายตนไปที่ At Line เมื่อ [S] รวมร่างกับ [Wind] (At Line) (Mp 2) (ผลจาก Skill  นี้ไม่นับว่าเป็นการกำหนด Line)
	{card_skill,
			s3_wind_no064_s1, 832, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, n, [{line, 0}, {can_move_to, 1}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, n, [{line, 0}, {can_move_to, 1}],
														{do_not_need_select, 0, [{player_action, to_at_line}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	% 066 Perun Pegasus
	%1. [Skill]-นำ [S] เข้ามาในสนามจากมือ จากนั้น N[Pegasus] ไม่เกิน 3 ใบในมือใช้ Skill ได้โดยไม่ต้องจ่าย Mp ค่าใช้ Skill จนจบ Subturn ? (Mp 5)
	{card_skill,
			s3_wind_no066_s1a, 834, 1, 5, y,
				y, 
					[{then_do, [s3_wind_no066_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [hand_cards]}], 											
									y, controller, [hand_cards], seal, y, [{naming, "Pegasus"}], 1,
										n, [], null,
											n, null, [], null,
												y, {do_not_need_select, 0, [{action, move_to_arena}]}, 0,
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s3_wind_no066_s1b, 834, 1, 5, y,
				y, 
					null, null,
						n, [],
							n, null, [],
								y, [{zone, [arena_zone]}],
									y, controller, [hand_cards], seal, null, [{naming, "Pegasus"}], 1,
										n, [], null,
											n, null, [], null,
												n, {}, 0,
													y, controller, [hand_cards], seal, y, [{naming, "Pegasus"}],
														{player_select_range_target, 3, [{skill, use_without_cost}]}, end_of_subturn,
															n, null, [null], null, null, [],
																[], null	
	},
	% 067 Armored Guardian
	%1. [Skill]-ย้ายเป้าหมายการโจมตีของ Seal 1 ใบไปที่ [S] ?(Charge 2) (Mp 2)
	{card_skill,
			s3_wind_no067_s1, 835, 1, {2,2}, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, null, [arena_zone], seal, n, [{action, attacker}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, 0, 
													y, null, [arena_zone], seal, n, [{action, attacker}],
														{do_not_need_select, 0, [{move_attack_target, to_s}]}, after_affect,
															n, null, [null], null, null, [],
																[], null	
	},
	% 069 Metallic Unicorn
	%1. [Skill]–Seal ที่ติด Curse 1 ใบติด Last Dance Curse At +2 / 1 Turn (At Line) (Mp 2)
	{card_skill,
			s3_wind_no069_s1, 837, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{curse, y}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, 0, 
													y, null, [arena_zone], seal, y, [{curse, y}, {protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, 2}}}]}, 2,
															n, null, [null], null, null, [],
																[], null	
	},
	% 070 Sore Griffin
	%1. [Skill]-เมื่อ [Beast] ฝ่ายผู้ใช้ Skill เป็นเป้าหมายการโจมตี Sacrifice [Beast] ใบนั้น; นำ [S] เข้ามาที่ At Line จากมือ จากนั้นย้ายเป้าหมายการโจมตีไปที่ [S] ? (Mp4)
	{card_skill,
			s3_wind_no070_s1a, 838, 1, 4, y,
				y, 
					null, null,	
						n, [],
							n, null, [],
								y, [{zone, [hand_cards]}], 											
									y, controller, [arena_zone], seal, null, [{action, attacked}, {type, "Beast"}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, 0, 
													y, controller, [arena_zone], seal, null, [{action, attacked}, {type, "Beast"}],
														{do_not_need_select, 0, [{player_action, sacrifice}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s3_wind_no070_s1b, 838, 1, 4, y,
				y, 
					[{then_do, [s3_wind_no070_s1c]}], null,
						n, [],
							n, null, [],
								y, [{zone, [hand_cards]}],
									y, controller, [arena_zone], seal, null, [{action, attacked}, {type, "Beast"}], 1,
										n, [], null,
											n, null, [], null,
												y, {do_not_need_select, 0, [{action, move_to_at_line}]}, 0,
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
	},
	{card_skill,
			s3_wind_no070_s1c, 838, 1, 4, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}],
									n, null, [], null, null, [], null,
										n, [], null,
											n, null, [], null,										
												n, {}, null,
													y, uncontrol, [arena_zone], seal, n, [{action, attacker}],
														{do_not_need_select, 0, [{move_attack_target, to_s}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	% 071 Blue Wind Griffin
	%1. [Skill]-Seal 1 ใบในสนาม Sp +1 จนจบ Subturn ? (Mp 2)
	{card_skill,
			s3_wind_no071_s1, 839, 1, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],
								y, [{zone, [arena_zone]}],
									y, null, [arena_zone], seal, y, [{protect_skill, n}], 1,
										n, [], null,
											n, null, [], null,
												null, {}, null,
													y, null, [arena_zone], seal, y, [{protect_skill, n}],
														{player_select_exact_target, 1, [{sp, 1}]}, end_of_subturn,
															n, null, [null], null, null, [],
																[], null
	},
	% 073 Brown Zebra Unicorn
	%1. [Skill]–เมื่อ N[Unicorn] ฝ่ายผู้ใช้ Skill เป็นเป้าหมายการโจมตี นำ [S] เข้ามาในสนามจากมือจากนั้นย้ายเป้าหมายการโจมตีหรือ Skill นั้นไปที่ [S] ? (Mp 3)
	{card_skill,
			s3_wind_no073_s1a, 841, 1, 3, y,
				y, 
					[{then_do, [s3_wind_no073_s1b]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [hand_cards]}], 											
									y, controller, [arena_zone], seal, null, [{action, attacked}, {naming, "Unicorn"}], 1,	                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_arena}]}, 0, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s3_wind_no073_s1b, 841, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, null, [{action, attacked}, {naming, "Unicorn"}], 1,
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, uncontrol, [arena_zone], seal, null, [{action, attacker}],
														{do_not_need_select, 0, [{move_attack_target, to_s}]}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	% 073 Brown Zebra Unicorn
	%2. [Skill]–เมื่อ N[Unicorn] ฝ่ายผู้ใช้ Skill เป็นเป้าหมาย Skill นำ [S] เข้ามาในสนามจากมือจากนั้นย้ายเป้าหมายการโจมตีหรือ Skill นั้นไปที่ [S] ? (Mp 3)
	{card_skill,
			s3_wind_no073_s1ca, 841, 1, 3, y,
				y, 
					[{then_do, [s3_wind_no073_s1d]}], null,	
						n, [],
							n, null, [],									
								y, [{zone, [hand_cards]}], 											
									y, controller, [arena_zone], seal, null, [{action, skill_target}, {naming, "Unicorn"}], 1,	                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_arena}]}, 0, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s3_wind_no073_s1d, 841, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [arena_zone], seal, null, [{action, skill_target}, {naming, "Unicorn"}], 1,
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, uncontrol, [arena_zone], seal, null, [{action, using_skill}],
														{do_not_need_select, 0, [{move_skill_target, {{select_seal_controller_arena, [{naming, "Unicorn"}, {action, skill_target}], 1}, to_s}}]}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	% 074 Delta - D 
	%[Skill]-ผู้เล่น 1 คนจั่วการ์ด 1 ใบ (Df Line) (Mp 3)
	{card_skill,
			s3_dark_no074_s1, 842, 1, 3, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 0}], 											
									y, owner, [seal_deck, mystic_deck], all, null, [], 1,	                        
										y, {player_select_exact_player, 1, [{draw_card, 1}]}, null,
											n, null, [], null,										
												n, {}, null, 
													n, null, [], null, null, [],
														{}, null,
															n, null, [null], null, null, [],
																[], null	
	},
	% 076 Rainbow Wing Pegasus
	%[Skill]–นำ [S] ขึ้นมือจากสนาม ? (Mp 3)
	{card_skill,
			s3_wind_no076_s1, 844, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {protect_skill, n}], 											
									n, null, [null], null, null, [], null,	                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_hand}]}, 0, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null	
	},
	% 077 Falkner, the Beast Tamer
	%1. [Skill]– นำ [ฺBeast] 1 ใบเข้ามาในสนามจากมือผู้ใช้ Skill (Mp 2) 
	{card_skill,
			s3_wind_no077_s1, 845, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [hand_cards], seal, null, [{type, "Beast"}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, 0, 
													y, controller, [hand_cards], seal, null, [{type, "Beast"}],
														{player_select_exact_target, 1, [{action, move_to_arena}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	% 077 Falkne, the Beast Tamer
	%[Skill]–แสดง Sore Wing 1 ใบจากกองการ์ด Seal ผู้ใช้ Skill แล้วนำขึ้นมือ (Mp 1) 
	{card_skill,
			s3_wind_no077_s2a, 845, 2, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [seal_deck], seal, null, [{name, "Sore Wing"}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, 0, 
													y, controller, [seal_deck], seal, null, [{name, "Sore Wing"}],
														{player_select_exact_target, 1, [{player_action, player_reveal}, {action, move_to_hand}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	 }
	% {card_skill,
			% s3_wind_no077_s2b, 845, 2, 2, n,
				% y, 
					% null, null,	
						% n, [],
							% n, null, [],									
								% y, [{zone, [arena_zone]}], 											
									% y, controller, [seal_deck], seal, null, [{name, "Sore Wing"}], 1,	                        
										% n, [], null,
											% n, null, [], null,										
												% n, {}, 0, 
													% y, null, [], null, null, [],
														% {{depend_on, s3_wind_no077_s2b}, 1, []}, 0,
															% n, null, [null], null, null, [],
																% [], null	
	% }
].

dark_skill() ->
[
	% 084 Dark Dream Pegasus
	%1. [Skill]–เมื่อมี N[Pegasus] 1 ใบใช้ Skill จากมือ Sacrifice [S]; Seal 1 ใบที่มี Sp 3, 4, 5 ติด Poison Curse 2 Turn ? (Mp 0)
	{card_skill,
			s3_dark_no084_s1, 852, 1, 0, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {{null, [arena_zone], seal, null}, {[{skill_target_speed, "345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}], 1}}, {protect_skill, n}], 											
									y, null, [hand_cards], seal, null, [{naming, "Pegasus"}, {action, using_skill}], 1,	                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{player_action, sacrifice}]}, 0, 
													y, null, [arena_zone], seal, null, [{skill_target_speed, "345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 4,
															n, null, [null], null, null, [],
																[], null	
	},
	% 085 Black Thunder Unicorn
	%1. [Skill]–Sacrifice N[Unicorn] 1 ใบ; Seal 1ใบที่มี Sp 1, 2, 3, 4 ติด Poison Curse 1 Turn เมื่อ [S] รวมร่าง (At Line) (Mp 2)
	{card_skill,
			s3_dark_no085_s1a, 853, 1, 2, n,
				y, 
					null, s3_dark_no085_s1b,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}, {{null, [arena_zone], seal, null}, {[{skill_target_speed, "1234"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1}}],
									y, controller, [arena_zone], seal, y, [{naming, "Unicorn"}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [arena_zone], seal, y, [{naming, "Unicorn"}],
														{player_select_exact_target, 1, [{player_action, sacrifice}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s3_dark_no085_s1b, 853, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}, {{controller, [arena_zone], seal, y}, {[{naming, "Unicorn"}], 1}}],
									y, null, [arena_zone], seal, null, [{skill_target_speed, "1234"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, null, [{skill_target_speed, "1234"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 2,
															n, null, [null], null, null, [],
																[], null	
	},
	% 086 Dark Widow
	%1.  [Skill]-Seal 1 ใบที่มี Sp 2, 3, 4, 5 ติด Charm Curse 1 Turn เมื่อ [S] รวมร่างกับ [Dark] (At Line) (Mp 2)
	{card_skill,
			s3_dark_no086_s1, 854, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 5}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, charm_curse}}, {curse, {n, charm_curse}}, {protect_skill, n}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, null, [{skill_target_speed, "2345"}, {protect_curse, {n, charm_curse}}, {curse, {n, charm_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, charm_curse}]}, 2,
															n, null, [null], null, null, [],
																[], null	
	},
	% 086 Dark Widow
	%1. [Skill]-Seal 1 ใบที่มี Sp 2, 3, 4, 5 ติด Poison Curse 3 Turn เมื่อ [S] รวมร่างกับ [Water] (Mp 2)
	{card_skill,
			s3_dark_no086_s2, 854, 2, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}, {combine, {elem, 2}}], 											
									y, null, [arena_zone], seal, y, [{skill_target_speed, "2345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, null, [arena_zone], seal, null, [{skill_target_speed, "2345"}, {protect_curse, {n, poison_curse}}, {curse, {n, poison_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 6,
															n, null, [null], null, null, [],
																[], null	
	},
	% 088 Aramellon, the Dragon of the Tale
	%1. [Skill]-Seal 1 ใบติด Last Dance Curse At +2 / 2 Turn เมื่อ [S] รวมร่าง ? (At Line) (Mp 3)
	{card_skill,
			s3_dark_no088_s1, 856, 1, 3, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}], 1,	                        
										n, [], null,
											n, null, [], null,	
												n, {}, null, 
													y, null, [arena_zone], seal, null, [{protect_curse, {n, last_dance_curse}}, {curse, {n, last_dance_curse}}, {protect_skill, n}],
														{player_select_exact_target, 1, [{curse, {last_dance_curse, {at, 2}}}]}, 4,
															n, null, [null], null, null, [],
																[], null	
	},
	% Evil Baron
	%1.  [Skill]-ดูการ์ดใบบนสุด 1 ใบจากกองการ์ด 1 กองของผู้ใช้ Skill จากนั้น ผู้ใช้ Skill สามารถนำการ์ดนั้นไปยัง Shrine (Mp 1)
	{card_skill,
			s3_dark_no092_s1a, 860, 1, 1, n,
				y, 
					[{then_do, [s3_dark_no092_s1b]}], null,
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, controller, [seal_deck, mystic_deck], all, null, [], 1,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [seal_deck, mystic_deck], all, null, [],
														{player_select_1_deck_and_system_select_top_deck, 1, [{player_action, consider}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	},
	{card_skill,
			s3_dark_no092_s1b, 860, 1, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									n, null, [], null, null, [], null,	                        
										n, [], null,
											n, null, [], null,										
												n, {}, null, 
													y, controller, [seal_deck, mystic_deck], all, null, [],
														{{depend_on, s3_dark_no092_s1a}, 0, [{player_action, can_move_to_shirne}]}, 0,
															n, null, [null], null, null, [],
																[], null	
	}
].

m_skill() ->
	% 094 Phenomenon World
	%[Skill]-เลือกธาตุ 1 ธาตุ จากนั้น Seal 1 ใบฝ่ายเราเปลี่ยนเป็นธาตุที่เลือก ? Turn (Mp 2)
	[
		{card_skill,
			m3_no094_s1, 862, 1, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{zone, [arena_zone]}], 											
									y, owner, [arena_zone], seal, null, [], 1,			                        
										n, {}, 0,
											n, null, [], null,										
												n, [], null, 
													y, owner, [arena_zone], seal, null, [],
														{player_select_exact_target, 1, [{elem, {select, 1}}]}, infinite,
															n, null, [null], null, null, [],
																[], null	
		}
	].