%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set1_seal_wind).
-export([wind/0]).
wind() ->
[ 
	{seal_card,317,
	                1,
	                61,
	                ["Charles, the General of Felasia"],
	                ["Knight"],			%type
	                [3],				%elem
	                ["Felasia","Charles"],	%naming
	                3,
	                2,
	                2,
	                7,
	                7,
	                3,
	                3}, 
	{seal_card,318,
	                1,
	                62,
	                ["Alicia, the Queen of Felasia"],
	                ["Mage"],
	                [3],
	                ["Felasia"],
	                3,
	                2,
	                3,
	                8,
	                9,
	                4,
	                3}, 
	{seal_card,319,
	                1,
	                63,
	                ["Felasia Swordsmaster"],
	                ["Knight"],
	                [3],
	                ["Felasia"],
	                4,
	                3,
	                3,
	                9,
	                9,
	                4,
	                3}, 
	{seal_card,320,
	                1,
	                64,
	                ["Aerial Turtle"],
	                ["Monster"],
	                [3],
	                [],
	                3,
	                1,
	                2,
	                7,
	                9,
	                3,
	                3}, 
	{seal_card,321,
	                1,
	                65,
	                ["Maluchius"],
	                ["Evil","Machine"],
	                [3],
	                [],
	                3,
	                2,
	                2,
	                8,
	                7,
	                4,
	                3}, 
	{seal_card,322,
	                1,
	                66,
	                ["Gale Garuda"],
	                ["Monster"],
	                [3],
	                ["Garuda"],
	                3,
	                2,
	                2,
	                8,
	                8,
	                5,
	                2}, 
	{seal_card,323,
	                1,
	                67,
	                [[86,
	                  97,
	                  108,
	                  110,
	                  105,
	                  97,
	                  32,
	                  68,
	                  105,
	                  115,
	                  116,
	                  114,
	                  105,
	                  99,
	                  116,
	                  226,
	                  128,
	                  153,
	                  115,
	                  32,
	                  84,
	                  111,
	                  114,
	                  116,
	                  111,
	                  105,
	                  115,
	                  101]],
	                ["Monster"],
	                [3],
	                [],
	                2,
	                1,
	                2,
	                5,
	                8,
	                4,
	                2}, 
	{seal_card,324,
	                1,
	                68,
	                ["Felasia Dragoon"],
	                ["Knight"],
	                [3],
	                ["Felasia","Dragoon"],
	                3,
	                2,
	                2,
	                8,
	                9,
	                3,
	                2}, 
	{seal_card,325,1,69,["Ballista"],["Machine"],[3],[],3,1,2,6,7,3,2}, 
	{seal_card,326,
	                1,
	                70,
	                ["Saber Tail Tiger"],
	                ["Monster"],
	                [3],
	                [],
	                2,
	                1,
	                2,
	                6,
	                6,
	                3,
	                2}, 
	{seal_card,327,
	                1,
	                71,
	                ["Felasia Assassin"],
	                ["Knight"],
	                [3],
	                ["Felasia"],
	                1,
	                1,
	                1,
	                5,
	                6,
	                3,
	                1}, 
	{seal_card,328,
	                1,
	                72,
	                [[70,
	                  101,
	                  108,
	                  97,
	                  115,
	                  105,
	                  97,
	                  226,
	                  128,
	                  153,
	                  115,
	                  32,
	                  75,
	                  110,
	                  105,
	                  103,
	                  104,
	                  116]],
	                ["Knight"],
	                [3],
	                ["Felasia"],
	                1,
	                1,
	                1,
	                5,
	                5,
	                3,
	                1}, 
	{seal_card,329,
	                1,
	                73,
	                ["Centaur Knight"],
	                ["Knight"],
	                [3],
	                ["Centaur"],
	                2,
	                1,
	                1,
	                5,
	                5,
	                2,
	                1}, 
	{seal_card,330,1,74,["Akim"],["Monster"],[3],[],2,1,1,5,6,4,1}, 
	{seal_card,331,
	                1,
	                75,
	                ["Night Flower Fairy"],
	                ["Evil"],
	                [3],
	                ["Fairy"],
	                1,
	                1,
	                1,
	                4,
	                4,
	                4,
	                1},
	{seal_card,367,
	                1,
	                111,
	                ["Leucon, The Ionosphere Dragon"],
	                ["Dragon"],
	                [3],
	                [],
	                2,
	                1,
	                2,
	                6,
	                6,
	                4,
	                4},
	{seal_card,374,
	                1,
	                118,
	                ["Charles’ s Adjutant"],
	                ["Knight"],
	                [3],
	                ["Charles"],
	                2,
	                1,
	                1,
	                5,
	                5,
	                4,
	                2},
	{seal_card,380,
	                1,
	                124,
	                ["Annimone, the Sky Wind Witch "],
	                ["Mage"],
	                [3],
	                ["Witch"],
	                2,
	                1,
	                2,
	                6,
	                8,
	                4,
	                2}
].