%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set1_seal_dark).
-export([dark/0]).
dark() ->
[ 
	{seal_card,332,
	                1,
	                76,
	                ["Haemon, the Dread Knight"],
	                ["Knight"], %type
	                [5], 		%elem
	                [],		%naming
	                3,
	                1,
	                2,
	                7,
	                7,
	                3,
	                3}, 
	{seal_card,333,
	                1,
	                77,
	                ["Cruel Giant"],
	                ["Titan"],
	                [5],
	                [],
	                4,
	                1,
	                2,
	                7,
	                8,
	                2,
	                3}, 
	{seal_card,334,
	                1,
	                78,
	                ["Dead Tail Masticore"],
	                ["Monster"],
	                [5],
	                [],
	                2,
	                1,
	                2,
	                6,
	                7,
	                4,
	                3}, 
	{seal_card,335,1,79,["Dark Doom"],["Monster"],[5],[],3,1,2,6,7,4,3}, 
	{seal_card,336,
	                1,
	                80,
	                ["Vice Wizard"],
	                ["Mage"],
	                [5],
	                [],
	                2,
	                1,
	                1,
	                6,
	                5,
	                5,
	                3}, 
	{seal_card,337,
	                1,
	                81,
	                ["Nazae, the Oracle of Zalom"],
	                ["Mage"],
	                [5],
	                ["Zalom"],
	                2,
	                1,
	                1,
	                5,
	                6,
	                2,
	                2}, 
	{seal_card,338,
	                1,
	                82,
	                ["Dread Knight"],
	                ["Knight"],
	                [5],
	                [],
	                3,
	                3,
	                2,
	                8,
	                0,
	                3,
	                2}, 
	{seal_card,339,
	                1,
	                83,
	                ["Wild Night Centaur"],
	                ["Knight"],
	                [5],
	                ["Centaur"],
	                2,
	                1,
	                2,
	                7,
	                5,
	                3,
	                2}, 
	{seal_card,340,
	                1,
	                84,
	                ["Death Paradise"],
	                ["Insect"],
	                [5],
	                [],
	                2,
	                1,
	                1,
	                6,
	                6,
	                3,
	                2}, 
	{seal_card,341,
	                1,
	                85,
	                ["Succubus"],
	                ["Evil"],
	                [5],
	                ["Succubus"],
	                2,
	                1,
	                2,
	                6,
	                6,
	                3,
	                2}, 
	{seal_card,342,1,86,["Duo Armor"],["Titan"],[5],[],2,1,2,6,6,4,1}, 
	{seal_card,343,
	                1,
	                87,
	                ["White Werewolf"],
	                ["Evil"],
	                [5],
	                ["Werewolf"],
	                2,
	                1,
	                1,
	                5,
	                6,
	                3,
	                1}, 
	{seal_card,344,1,88,["Maliceo"],["Insect"],[5],[],1,1,1,4,5,4,1}, 
	{seal_card,345,
	                1,
	                89,
	                ["Black Wood Lancer"],
	                ["Knight"],
	                [5],
	                [],
	                3,
	                1,
	                2,
	                6,
	                5,
	                3,
	                1}, 
	{seal_card,346,
	                1,
	                90,
	                ["Lazal Robber"],
	                ["Bandit"],
	                [5],
	                ["Lazal"],
	                1,
	                1,
	                1,
	                4,
	                5,
	                3,
	                1},
	{seal_card,371,
	                1,
	                115,
	                ["Night Crocotta"],
	                ["Monster"],
	                [5],
	                [],
	                2,
	                1,
	                1,
	                6,
	                5,
	                3,
	                2}
].
