%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set1_seal_earth).
-export([earth/0]).
earth() ->
[ 
	{seal_card,272,
	                1,
	                16,
	                ["Harison, Knight of Pentacles"],
	                ["Knight"],   %type
	                [1],		%elem
	                ["Harison"],%naming
	                4,
	                2,
	                3,
	                8,
	                11,
	                3,
	                3}, 
	{seal_card,273,
	                1,
	                17,
	                ["Wanaan, Princess of Pentacles"],
	                ["Mage"],
	                [1],
	                [],
	                4,
	                2,
	                3,
	                8,
	                12,
	                3,
	                3}, 
	{seal_card,274,
	                1,
	                18,
	                ["Tiger Manticore"],
	                ["Monster"],
	                [1],
	                [],
	                2,
	                1,
	                1,
	                4,
	                7,
	                2,
	                3}, 
	{seal_card,275,
	                1,
	                19,
	                [[71,
	                  97,
	                  115,
	                  104,
	                  44,
	                  32,
	                  116,
	                  104,
	                  101,
	                  32,
	                  70,
	                  117,
	                  100,
	                  101,
	                  110,
	                  117,
	                  110,
	                  226,
	                  128,
	                  153,
	                  115,
	                  32,
	                  87,
	                  97,
	                  114,
	                  108,
	                  111,
	                  114,
	                  100]],
	                ["Knight"],
	                [1],
	                ["Fudenun"],
	                3,
	                1,
	                2,
	                7,
	                8,
	                3,
	                3}, 
	{seal_card,276,
	                1,
	                20,
	                ["Woojin, the Elder of Fudenun"],
	                ["Mage"],
	                [1],
	                ["Fudenun"],
	                4,
	                2,
	                3,
	                8,
	                12,
	                2,
	                3}, 
	{seal_card,277,
	                1,
	                21,
	                ["Fudenun Miner"],
	                ["Knight"],
	                [1],
	                ["Fudenun"],
	                2,
	                1,
	                2,
	                6,
	                7,
	                2,
	                2}, 
	{seal_card,278,
	                1,
	                22,
	                ["Centaur Scout"],
	                ["Knight"],
	                [1],
	                ["Centaur"],
	                3,
	                2,
	                2,
	                6,
	                8,
	                4,
	                2}, 
	{seal_card,279,1,23,["Dead Armor"],["Knight"],[1],[],3,1,2,6,8,2,2}, 
	{seal_card,280,1,24,["Tartaroo"],["Monster"],[1],[],4,1,2,7,9,2,2}, 
	{seal_card,281,
	                1,
	                25,
	                ["Stone Lizard"],
	                ["Monster"],
	                [1],
	                [],
	                2,
	                1,
	                2,
	                5,
	                7,
	                2,
	                2}, 
	{seal_card,282,
	                1,
	                26,
	                ["Light Therion"],
	                ["Monster"],
	                [1],
	                ["Therion"],
	                3,
	                1,
	                2,
	                6,
	                8,
	                3,
	                1}, 
	{seal_card,283,
	                1,
	                27,
	                ["Fudenun Tribal Warrior"],
	                ["Knight"],
	                [1],
	                ["Fudenun"],
	                2,
	                1,
	                2,
	                6,
	                7,
	                3,
	                1}, 
	{seal_card,284,
	                1,
	                28,
	                ["Fudenun Guard"],
	                ["Knight"],
	                [1],
	                ["Fudenun"],
	                2,
	                1,
	                1,
	                5,
	                7,
	                2,
	                1}, 
	{seal_card,285,
	                1,
	                29,
	                ["Fudenun Shaman"],
	                ["Mage"],
	                [1],
	                ["Fudenun"],
	                2,
	                1,
	                1,
	                5,
	                6,
	                2,
	                1}, 
	{seal_card,286,1,30,["Ebonga"],["Monster"],[1],[],2,1,1,5,6,4,1},
	{seal_card,365,
	                1,
	                109,
	                ["Georgina, Elf Archer T - II"],
	                ["Knight"],
	                [1],
	                ["Archer"],
	                3,
	                1,
	                2,
	                7,
	                8,
	                3,
	                4},
	{seal_card,368,
	                1,
	                112,
	                ["Parrier Infantry"],
	                ["Knight"],
	                [1],
	                [],
	                2,
	                1,
	                2,
	                6,
	                8,
	                2,
	                2}, 
	{seal_card,369,
	                1,
	                113,
	                ["Armarabby"],
	                ["Monster"],
	                [1],
	                [],
	                1,
	                1,
	                1,
	                5,
	                6,
	                2,
	                2},
	{seal_card,379,
	                1,
	                123,
	                ["Garry, Elf Warrior"],
	                ["Knight"],
	                [1],
	                ["Elf"],
	                3,
	                1,
	                2,
	                7,
	                8,
	                3,
	                2}
].