%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set1_seal_water).
-export([water/0]).
water() ->
[ 
	{seal_card,302,
	                1,
	                46,
	                ["Andre, Knight of Cups"],
	                ["Knight"],	%type
	                [2],		%elem
	                ["Andre"],	%naming
	                4,
	                3,
	                3,
	                9,
	                10,
	                4,
	                3}, 
	{seal_card,303,
	                1,
	                47,
	                ["Eric, Merman Commander"],
	                ["Knight"],
	                [2],
	                ["Merman"],
	                1,
	                1,
	                1,
	                4,
	                5,
	                2,
	                3}, 
	{seal_card,304,
	                1,
	                48,
	                ["Alana, Princess of Cups"],
	                ["Mage"],
	                [2],
	                ["Alana"],
	                4,
	                2,
	                3,
	                9,
	                10,
	                3,
	                3}, 
	{seal_card,305,
	                1,
	                49,
	                ["King & Queen of Annedisonge"],
	                ["Mage"],
	                [2],
	                ["Annedisonge"],
	                4,
	                1,
	                2,
	                7,
	                8,
	                3,
	                3}, 
	{seal_card,306,
	                1,
	                50,
	                ["Merman Knight"],
	                ["Knight"],
	                [2],
	                ["Merman"],
	                3,
	                1,
	                2,
	                7,
	                7,
	                2,
	                3}, 
	{seal_card,307,
	                1,
	                51,
	                ["Marine Warrior"],
	                ["Knight"],
	                [2],
	                [],
	                2,
	                1,
	                2,
	                6,
	                7,
	                3,
	                2}, 
	{seal_card,308,
	                1,
	                52,
	                ["Lame Shaman"],
	                ["Mage"],
	                [2],
	                [],
	                1,
	                1,
	                1,
	                3,
	                6,
	                2,
	                2}, 
	{seal_card,309,
	                1,
	                53,
	                ["Green Tadpole"],
	                ["Monster"],
	                [2],
	                [],
	                1,
	                1,
	                1,
	                5,
	                6,
	                3,
	                2}, 
	{seal_card,310,
	                1,
	                54,
	                ["Melanie, the Inventor of Annedisonge"],
	                ["Scientist"],
	                [2],
	                ["Annedisonge"],
	                2,
	                1,
	                1,
	                5,
	                6,
	                2,
	                2}, 
	{seal_card,311,
	                1,
	                55,
	                ["Annedisonge Airship"],
	                ["Machine"],
	                [2],
	                ["Annedisonge"],
	                2,
	                1,
	                1,
	                5,
	                6,
	                3,
	                2}, 
	{seal_card,312,1,56,["Aqualo"],["Insect"],[2],[],2,1,1,3,4,2,1}, 
	{seal_card,313,1,57,["Hexapus"],["Monster"],[2],[],2,1,1,5,7,3,1}, 
	{seal_card,314,
	                1,
	                58,
	                ["Merman Trooper"],
	                ["Knight"],
	                [2],
	                ["Merman"],
	                2,
	                1,
	                2,
	                6,
	                7,
	                3,
	                1}, 
	{seal_card,315,
	                1,
	                59,
	                ["Merman Ranger"],
	                ["Monster"],
	                [2],
	                ["Merman"],
	                2,
	                1,
	                1,
	                5,
	                6,
	                3,
	                1}, 
	{seal_card,316,1,60,["Wild Whale"],["Monster"],[2],[],2,1,2,6,8,3,1},
	{seal_card,372,
	                1,
	                116,
	                ["Sahagorus"],
	                ["Monster"],
	                [2],
	                [],
	                2,
	                1,
	                2,
	                6,
	                7,
	                3,
	                2},						 
	{seal_card,373,
	                1,
	                117,
	                ["Crystal Knight"],
	                ["Knight"],
	                [2],
	                [],
	                3,
	                1,
	                2,
	                6,
	                7,
	                2,
	                2},
	{seal_card,377,1,121,["Megan, the Water Witch"],["Mage"],[2],["Witch"],3,1,2,6,7,3,3}
].
%card_id, card_set, card_no, card_name, card_type, card_element, card_naming, mp_cast, mp_atk, level, attack, defend, speed, rarity