%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set1_seal_light).
-export([light/0]).
light() ->
[ 
	{seal_card,257,
	                1,
	                1,
	                ["Heaven Knight"],
	                ["Knight"],		%type
	                [6],			%elem
	                ["Heaven Knight"],	%naming
	                5,
	                3,
	                4,
	                10,
	                11,
	                5,
	                3}, 
	{seal_card,258,
	                1,
	                2,
	                ["Nephele, the Goddess of Centaur"],
	                ["Knight"],
	                [6],
	                ["Centaur"],
	                3,
	                1,
	                2,
	                7,
	                7,
	                4,
	                3}, 
	{seal_card,259,
	                1,
	                3,
	                ["Gregory, the Bishop of Felasia"],
	                ["Mage"],
	                [6],
	                ["Gregory","Bishop","Felasia"],
	                3,
	                1,
	                2,
	                7,
	                8,
	                2,
	                3}, 
	{seal_card,260,
	                1,
	                4,
	                ["Daniella, the Valkyrie"],
	                ["Divine"],
	                [6],
	                ["Valkyrie"],
	                2,
	                1,
	                2,
	                5,
	                6,
	                2,
	                3}, 
	{seal_card,261,
	                1,
	                5,
	                ["Holy Zealot"],
	                ["Mage"],
	                [6],
	                ["Holy"],
	                3,
	                1,
	                2,
	                7,
	                7,
	                3,
	                3}, 
	{seal_card,262,
	                1,
	                6,
	                ["Martin' s Adjutant Officer"],
	                ["Knight"],
	                [6],
	                ["Martin"],
	                3,
	                1,
	                2,
	                7,
	                7,
	                3,
	                2}, 
	{seal_card,263,1,7,["Martin' s Guardian Knight"],["Knight"],[6],["Martin"],2,1,2,6,7,4,2}, 
	{seal_card,264,1,8,["Titania"],["Divine"],[6],[],2,1,2,6,7,3,2}, 
	{seal_card,265,1,9,["Unicorn Fairy"],["Divine"],[6],["Fairy", "Unicorn"],2,1,1,5,6,3,2}, 
	{seal_card,266,
	                1,
	                10,
	                ["Raina Shaman"],
	                ["Mage"],
	                [6],
	                [],
	                3,
	                1,
	                2,
	                7,
	                8,
	                2,
	                2}, 
	{seal_card,267,
	                1,
	                11,
	                ["Ekklesia Sentry"],
	                ["Knight"],
	                [6],
	                [],
	                1,
	                1,
	                1,
	                5,
	                6,
	                3,
	                1}, 
	{seal_card,268,
	                1,
	                12,
	                ["Ekklesia Knight"],
	                ["Knight"],
	                [6],
	                [],
	                2,
	                1,
	                2,
	                6,
	                6,
	                2,
	                1}, 
	{seal_card,269,
	                1,
	                13,
	                ["Sister Rosana"],
	                ["Mage"],
	                [6],
	                [],
	                2,
	                1,
	                1,
	                5,
	                6,
	                3,
	                1}, 
	{seal_card,270,
	                1,
	                14,
	                ["Saber Mongoose"],
	                ["Monster"],
	                [6],
	                [],
	                1,
	                1,
	                1,
	                4,
	                4,
	                4,
	                1}, 
	{seal_card,271,
	                1,
	                15,
	                ["Mountain Cat"],
	                ["Monster"],
	                [6],
	                [],
	                3,
	                1,
	                2,
	                7,
	                7,
	                2,
	                1},
	{seal_card,366,
	                1,
	                110,
	                ["Alana, Princess of Annedisonge T - II"],
	                ["Mage"],
	                [6, 2],
	                ["Alana", "Annedisonge"],
	                3,
	                1,
	                2,
	                6,
	                8,
	                3,
	                4},
	{seal_card,375,
	                1,
	                119,
	                ["Silver Archery Knight"],
	                ["Knight"],
	                [6],
	                ["Archer"],
	                3,
	                1,
	                2,
	                7,
	                7,
	                4,
	                2},
	{seal_card,378,
	                1,
	                122,
	                ["Colossus Warlock"],
	                ["Tamer"],
	                [6],
	                [],
	                2,
	                1,
	                1,
	                5,
	                6,
	                2,
	                2}
].
