%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set1_seal_fire).
-export([fire/0]).
fire() ->
[ 
	{seal_card,287,
	                1,
	                31,
	                ["Yacehan, the Lord of Lazal"],
	                ["Knight"], %type
	                [4],		%elem
	                ["Lazal"],	%naming
	                4,
	                3,
	                4,
	                10,
	                7,
	                3,
	                3}, 
	{seal_card,288,
	                1,
	                32,
	                ["Lazal Sword Maiden"],
	                ["Knight"],
	                [4],
	                ["Lazal"],
	                2,
	                1,
	                2,
	                5,
	                5,
	                3,
	                3}, 
	{seal_card,289,
	                1,
	                33,
	                ["Cyrus, the Swordman"],
	                ["Knight"],
	                [4],
	                [],
	                3,
	                1,
	                2,
	                7,
	                9,
	                4,
	                3}, 
	{seal_card,290,
	                1,
	                34,
	                ["Zalom Fighter"],
	                ["Knight"],
	                [4],
	                ["Zalom"],
	                2,
	                1,
	                2,
	                6,
	                5,
	                2,
	                3}, 
	{seal_card,291,
	                1,
	                35,
	                ["Blaze Sage, the Viceroy of Zalom"],
	                ["Mage"],
	                [4],
	                ["Zalom"],
	                3,
	                1,
	                2,
	                6,
	                6,
	                3,
	                3}, 
	{seal_card,292,
	                1,
	                36,
	                ["Mor Mercenary"],
	                ["Knight"],
	                [4],
	                [],
	                2,
	                2,
	                2,
	                6,
	                6,
	                3,
	                2}, 
	{seal_card,293,
	                1,
	                37,
	                [[78,
	                  97,
	                  114,
	                  105,
	                  115,
	                  32,
	                  83,
	                  117,
	                  108,
	                  97,
	                  105,
	                  109,
	                  97,
	                  110,
	                  44,
	                  32,
	                  90,
	                  97,
	                  108,
	                  111,
	                  109,
	                  226,
	                  128,
	                  153,
	                  115,
	                  32,
	                  71,
	                  114,
	                  97,
	                  110,
	                  100,
	                  32,
	                  67,
	                  111,
	                  117,
	                  110,
	                  99,
	                  105,
	                  108,
	                  108,
	                  111,
	                  114]],
	                ["Knight"],
	                [4],
	                ["Zalom"],
	                2,
	                1,
	                2,
	                6,
	                5,
	                3,
	                2}, 
	{seal_card,294,
	                1,
	                38,
	                ["Evil Impostess"],
	                ["Mage", "Evil"],
	                [4],
	                [],
	                3,
	                1,
	                2,
	                6,
	                5,
	                4,
	                2}, 
	{seal_card,295,1,39,["Butterfire"],["Insect"],[4],[],2,1,2,4,4,4,2}, 
	{seal_card,296,1,40,["Phonos"],["Evil"],[4],[],3,2,2,7,7,3,2}, 
	{seal_card,297,
	                1,
	                41,
	                [[90,97,108,111,109,226,128,153,115,32,82,105,100,101,114]],
	                ["Knight"],
	                [4],
	                ["Zalom"],
	                2,
	                1,
	                2,
	                6,
	                6,
	                3,
	                1}, 
	{seal_card,298,
	                1,
	                42,
	                ["Evil Fire Warrior"],
	                ["Knight"],
	                [4],
	                [],
	                2,
	                1,
	                2,
	                6,
	                8,
	                2,
	                1}, 
	{seal_card,299,1,43,["Nightmare"],["Evil"],[4],["Nightmare"],2,1,1,4,4,4,1}, 
	{seal_card,300,
	                1,
	                44,
	                ["Zalom Fortress Archer"],
	                ["Knight"],
	                [4],
	                ["Zalom"],
	                2,
	                1,
	                1,
	                5,
	                4,
	                3,
	                1}, 
	{seal_card,301,1,45,["Souless"],["Knight"],[4],[],1,1,1,5,5,3,1},
	{seal_card,370,
	                1,
	                114,
	                ["Scarlet Swordmaiden"],
	                ["Knight"],
	                [4],
	                [],
	                3,
	                1,
	                2,
	                7,
	                6,
	                3,
	                2},
	{seal_card,376,1,120,["Pyroberserker"],["Knight"],[4],[],4,3,3,9,9,3,3}
].
%card_id, card_set, card_no, card_name, card_type, card_element, card_naming, mp_cast, mp_atk, level, attack, defend, speed, rarity