%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_seal_water).
-export([water/0]).
water() ->
[ 
	{seal_card,559,
	                2,
	                47,
	                ["Jormungand"],
	                ["Dragon"],
	                [2],
	                ["Jormungand"],
	                5,
	                3,
	                3,
	                10,
	                11,
	                2,
	                3}, 
	{seal_card,560,
	                2,
	                48,
	                ["Vermiculas, Deep Sea Dragon"],
	                ["Dragon"],
	                [2],
	                [],
	                5,
	                3,
	                3,
	                10,
	                11,
	                2,
	                3}, 
	{seal_card,561,
	                2,
	                49,
	                ["Ocean Golem"],
	                ["Titan"],
	                [2],
	                [],
	                3,
	                1,
	                2,
	                7,
	                8,
	                2,
	                3}, 
	{seal_card,562,
	                2,
	                50,
	                ["Sarindra, the Goddess of Reflexion"],
	                ["Divine"],
	                [2],
	                [],
	                3,
	                1,
	                2,
	                7,
	                8,
	                3,
	                3}, 
	{seal_card,563,
	                2,
	                51,
	                ["Deep Sea Guardian"],
	                ["Titan"],
	                [2],
	                [],
	                4,
	                1,
	                3,
	                8,
	                12,
	                1,
	                3}, 
	{seal_card,564,
	                2,
	                52,
	                ["Aireserke, the Weapon of Lemuria"],
	                ["Dragon"],
	                [2],
	                [],
	                2,
	                1,
	                2,
	                6,
	                8,
	                3,
	                2}, 
	{seal_card,565,
	                2,
	                53,
	                ["Hydra of Warok"],
	                ["Dragon"],
	                [2],
	                [],
	                3,
	                2,
	                2,
	                8,
	                9,
	                2,
	                2}, 
	{seal_card,566,
	                2,
	                54,
	                ["The Dragon's Egg in the Laboratory"],
	                ["Dragon's Egg"],
	                [2],
	                [],
	                1,
	                0,
	                1,
	                3,
	                4,
	                0,
	                2}, 
	{seal_card,567,
	                2,
	                55,
	                ["Carfac, the Lemurian Dragon"],
	                ["Dragon"],
	                [2],
	                [],
	                2,
	                1,
	                2,
	                6,
	                6,
	                4,
	                2}, 
	{seal_card,568,2,56,["Naftikos"],["Monster"],[2],[],2,1,2,5,8,2,2}, 
	{seal_card,569,
	                2,
	                57,
	                ["Firngollo, the Baby Dragon"],
	                ["Dragon"],
	                [2],
	                ["Baby Dragon"],
	                1,
	                1,
	                1,
	                4,
	                5,
	                3,
	                1}, 
	{seal_card,570,2,58,["Armadillon"],["Monster"],[2],[],2,1,2,7,9,2,1}, 
	{seal_card,571,
	                2,
	                59,
	                ["Aqua Tail Viper"],
	                ["Monster"],
	                [2],
	                ["Viper"],
	                1,
	                1,
	                1,
	                5,
	                6,
	                3,
	                1}, 
	{seal_card,572,
	                2,
	                60,
	                ["Magamouth"],
	                ["Fish"],
	                [2],
	                ["Magamouth"],
	                1,
	                1,
	                1,
	                5,
	                6,
	                3,
	                1}, 
	{seal_card,573,
	                2,
	                61,
	                ["Ancient Lizard"],
	                ["Monster"],
	                [2],
	                [],
	                1,
	                1,
	                1,
	                4,
	                6,
	                1,
	                1}
].
