%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_seal_wind).
-export([wind/0]).
wind() ->
[ 
	{seal_card,574,
	                2,
	                62,
	                ["Tera, Mist Dragon"],
	                ["Dragon"],
	                [3, 4],
	                [],
	                4,
	                3,
	                3,
	                9,
	                10,
	                5,
	                3}, 
	{seal_card,575,
	                2,
	                63,
	                ["Wool Wyvern"],
	                ["Dragon"],
	                [3],
	                [],
	                4,
	                2,
	                2,
	                8,
	                9,
	                5,
	                3}, 
	{seal_card,576,
	                2,
	                64,
	                ["Gusty Phamakos"],
	                ["Mage"],
	                [3],
	                [],
	                3,
	                1,
	                2,
	                6,
	                7,
	                3,
	                3}, 
	{seal_card,577,
	                2,
	                65,
	                ["Felasia Tamer"],
	                ["Tamer"],
	                [3],
	                ["Felesia"],
	                3,
	                1,
	                2,
	                7,
	                8,
	                4,
	                3}, 
	{seal_card,578,
	                2,
	                66,
	                ["Magnificent Griffin"],
	                ["Beast"],
	                [3],
	                ["Griffin"],
	                3,
	                1,
	                2,
	                6,
	                8,
	                5,
	                3}, 
	{seal_card,579,2,67,["Catapult"],["Machine"],[3],[],2,1,2,5,6,2,2}, 
	{seal_card,580,
	                2,
	                68,
	                ["Nurnov, the High Hill Dragon"],
	                ["Dragon"],
	                [3],
	                [],
	                2,
	                1,
	                2,
	                6,
	                6,
	                5,
	                2}, 
	{seal_card,581,2,69,["Jamaria"],["Monster"],[3],[],2,1,1,5,6,4,2}, 
	{seal_card,582,
	                2,
	                70,
	                ["The Dragon's Egg on the Cliff"],
	                ["Dragon's Egg"],
	                [3],
	                [],
	                1,
	                0,
	                1,
	                3,
	                4,
	                5,
	                2}, 
	{seal_card,583,
	                2,
	                71,
	                ["Tanorod, the Wasteland Dragon"],
	                ["Dragon"],
	                [3],
	                [],
	                2,
	                1,
	                1,
	                4,
	                6,
	                4,
	                2}, 
	{seal_card,584,2,72,["Agile Mangoose"],["Monster"],[3],[],3,1,2,7,7,4,2}, 
	{seal_card,585,
	                2,
	                73,
	                ["Dimminuial, the Baby Dragon"],
	                ["Dragon"],
	                [3],
	                ["Baby Dragon"],
	                1,
	                1,
	                1,
	                4,
	                4,
	                5,
	                1}, 
	{seal_card,586,2,74,["Sgaleo"],["Insect"],[3],[],1,1,1,4,4,5,1}, 
	{seal_card,587,2,75,["Aebolas"],["Monster"],[3],[],2,1,2,6,8,4,1}, 
	{seal_card,588,2,76,["Crown Lion"],["Monster"],[3],[],3,1,2,7,7,4,1}, 
	{seal_card,589,
	                2,
	                77,
	                ["Garuda Lancer"],
	                ["Monster"],
	                [3],
	                ["Garuda"],
	                3,
	                1,
	                2,
	                7,
	                7,
	                4,
	                1}
].
