%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_seal_dark).
-export([dark/0]).
dark() ->
[ 
	{seal_card,590,
	                2,
	                78,
	                ["Tiamat, the Black Dragon"],
	                ["Dragon"],
	                [5],
	                [],
	                4,
	                2,
	                3,
	                9,
	                10,
	                2,
	                3}, 
	{seal_card,591,
	                2,
	                79,
	                ["Cricus, Cursed Bone Dragon"],
	                ["Dragon"],
	                [5],
	                ["Curse"],
	                4,
	                3,
	                3,
	                9,
	                9,
	                3,
	                3}, 
	{seal_card,592,
	                2,
	                80,
	                ["Hubris Iron Golem"],
	                ["Titan"],
	                [5],
	                [],
	                4,
	                2,
	                3,
	                8,
	                10,
	                1,
	                3}, 
	{seal_card,593,
	                2,
	                81,
	                ["Amber, the Valkyrie"],
	                ["Divine"],
	                [5],
	                [],
	                3,
	                1,
	                3,
	                8,
	                7,
	                3,
	                3}, 
	{seal_card,594,2,82,["Baalzebub"],["Machine"],[5],[],4,3,3,9,9,5,3}, 
	{seal_card,595,2,83,["Cerberus"],["Monster"],[5],[],3,2,2,7,8,2,2}, 
	{seal_card,596,2,84,["Screak"],["Evil"],[5],[],2,1,2,5,5,3,2}, 
	{seal_card,597,
	                2,
	                85,
	                ["Black Horn Viper"],
	                ["Monster"],
	                [5],
	                ["Viper"],
	                2,
	                1,
	                1,
	                5,
	                6,
	                4,
	                2}, 
	{seal_card,598,
	                2,
	                86,
	                ["Fierce Therion"],
	                ["Monster"],
	                [5],
	                ["Therion"],
	                3,
	                1,
	                2,
	                7,
	                7,
	                3,
	                2}, 
	{seal_card,599,
	                2,
	                87,
	                ["Bloody Waritant"],
	                ["Monster"],
	                [5],
	                [],
	                1,
	                1,
	                1,
	                4,
	                5,
	                3,
	                2}, 
	{seal_card,600,
	                2,
	                88,
	                ["Ungawee, the Venomous Dragon"],
	                ["Dragon"],
	                [5],
	                [],
	                3,
	                2,
	                2,
	                8,
	                10,
	                3,
	                2}, 
	{seal_card,601,
	                2,
	                89,
	                ["All Eye Viper"],
	                ["Monster"],
	                [5],
	                ["Viper"],
	                1,
	                1,
	                1,
	                4,
	                5,
	                3,
	                1}, 
	{seal_card,602,
	                2,
	                90,
	                ["Novhoth, the Baby Dragon"],
	                ["Dragon"],
	                [5],
	                ["Baby Dragon"],
	                1,
	                1,
	                1,
	                5,
	                4,
	                4,
	                1}, 
	{seal_card,603,
	                2,
	                91,
	                ["The Dragon's Egg in the Cave"],
	                ["Dragon's Egg"],
	                [5],
	                [],
	                1,
	                1,
	                1,
	                4,
	                4,
	                0,
	                1}, 
	{seal_card,604,
	                2,
	                92,
	                ["Poisoned Parasite"],
	                ["Monster"],
	                [5],
	                [],
	                2,
	                1,
	                1,
	                5,
	                6,
	                2,
	                1}, 
	{seal_card,605,
	                2,
	                93,
	                ["Winged Slayer"],
	                ["Monster"],
	                [5],
	                [],
	                3,
	                1,
	                2,
	                7,
	                6,
	                3,
	                1},
	{seal_card,623,
	                2,
	                111,
	                ["Xerxes, the Necromancer"],
	                ["Mage"],
	                [5],
	                [],
	                4, %mp√Ë“¬
	                1, %mpµ’
	                2, %Lv
	                7, %Atk
	                9, %Def
	                3, %Sp
	                2}
].
