%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_earth).
-export([earth2_ability/0]).

earth2_ability() ->
[
	%เมื่อ [S] ถูกโจมตี เทียบ Df ของ [S]   กับค่าพลังของ Seal ที่โจมตี [S] จนออกจากการโจมตีนั้น
	{card_ability,
		s2_earth_no16_a1, 528, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]},{action, attacked}],													
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [], null,							
										y, y, {do_not_need_select, 0, [{combat, {when_target, {power, df}}}]},	end_of_fighting,										
											n, null, [null], null, [],
												null, [] ,null
	},
	%ขณะที่ [S] ต่อสู้กับ [Wind] [S] At –3
	{card_ability,
		s2_earth_no16_a2, 528, 2,
			n,[],
				n, null, [],								
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {elem, 3}], 1,
	                  n, [],
								n, null, [], null,
									n, null, null, [],	null,
				                  y, y, {do_not_need_select, 0, [{at, -3}]}, end_of_fighting,											
											n, null, [null], null, [],
												null, [] ,null
	},
	%เมื่อ [S] ต่อสู้เทียบ Df ของ [S] กับ Df ของ Seal ที่ต่อสู้กับ [S] จนออกจากการโจมตีนั้น
	{card_ability,
		s2_earth_no17_a, 529, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]},{action, fight}],													
						y, null, [arena_zone], n, [{action, fight}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{combat, {when_fight_attack, {df, df}}}, {combat, {when_fight_target, {df, df}}}]}, end_of_fighting,										
											n, null, [null], null, [],
												null, [] ,null
	},
	%เมื่อ Seal เข้ามาในสนามที่ Df Line ฝ่ายเรา สามารถให้ Seal นั้น Df = 11 Sp = 0 / 1 Turn (Df Line) (Ability นี้ทำงาน 2 ครั้งใน 1 Subturn)
	{card_ability,
		s2_earth_no18_a1, 530, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {line, 0}, {activate_ability, {2, 0}}], % 2 ครั้ง ใน 1 Subturn
						y, owner, [arena_zone], y, [{card_type, seal}, {action, into_arena}], 1,	
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										n, null, [], null,
											y, owner, [arena_zone], y, [{card_type, seal}, {action, into_arena}],
												y, {owner_can_activate_ability, 1, [{check_condition, {[{line, 0}], {df , {equal, 11}}}}, {check_condition, {[{line, 0}], {sp, {equal, 0}}}}]}, 2
	},
	%[S] ยกเลิก Freeze Curse
	{card_ability,
		s2_earth_no19_a1, 531, 1, 
			n, [],
				n, null, [],									
					y,[{zone, [arena_zone]}, {action, on_arena}], 											
						n, null, [null], null, [], null,
							y, [],
								n, null, [], null,                       
									n, null, null, [],	null,												
										y, y,{do_not_need_select, 0, [{cancel_curse, [freeze_curse]}]}, null,											
											n, null, [null], null, [],
												null, [] ,null					
	},
	%ตราบเท่าที่มี Seal ในสนามฝ่ายตรงข้ามน้อยกว่าเรา ผู้เล่นไม่สามารถสั่ง Seal โจมตี [S] ได้
	{card_ability,
		s2_earth_no21_a1, 533, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [null], null, [], null,							
							y, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{assign_attack_to_s, {disallow, all}}]}, null,
											n, null, [null], null, [],
												null, [] ,null
	},
	%ผู้เล่นไม่สามารถสั่ง [S] โจมตีได้
	{card_ability,
		s2_earth_no21_a2, 533, 2, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [null], null, [], null,							
							y, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{assign_atk, disallow}]}, null,
											n, null, [null], null, [],
												null, [] ,null
	},
	%ตราบเท่าที่ Angorion, the Earth Spirit อยู่ในสนาม [Earth] ทุกใบในสนามฝ่ายเรา Df +1
	{card_ability,
		s2_earth_no22_a1, 534, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [null], null, [], null,							
							y, [],
								n, null, [], null,
									n, null, null, [],	null,							
										n, null, [], null,
											y, owner, [arena_zone], y, [{elem, 1}],
												y, {do_not_need_select, 0, [{df, 1}]}, null
	},
	%ตราบเท่าที่ [S] อยู่ในสนาม Angorion, the Earth Spirit ทุกใบในสนาม At +1 Sp +1 Mp ค่าใช้ Skill –1 (Effect นี้ยังคงส่งผลแม้ว่า [S] อยู่ใน Shrine)
	{card_ability,
		s2_earth_no22_a2a, 534, 2, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [], null, [], null,							
							y, [],
								n, null, [], null,
									n, null, null, [],	null,							
										n, null, [], null,
											y, null, [arena_zone], null, [{card_type, seal}, {name, "Angorion, the Earth Spirit"}],
												y, {do_not_need_select, 0, [{at, 1}, {sp, 1}, {ms, -1}]}, null
	},
	%ตราบเท่าที่ [S] อยู่ใน Shrine Angorion, the Earth Spirit ทุกใบในสนาม At +1 Sp +1 Mp ค่าใช้ Skill –1 (Effect นี้ยังคงส่งผลแม้ว่า [S] อยู่ใน Shrine)
	{card_ability,
		s2_earth_no22_a2b, 534, 2, 
			n,[],
				n, null, [],									
					y, [{zone, [shrine_cards]}, {action, in_shrine}],													
						n, null, [], null, [], null,							
							y, [],
								n, null, [], null,
									n, null, null, [], null,							
										n, null, [], null,
											y, null, [arena_zone], null, [{card_type, seal}, {name, "Angorion, the Earth Spirit"}],
												y, {do_not_need_select, 0, [{at, 1}, {sp, 1}, {ms, -1}]}, null
	},
	%ขณะที่ [S]ต่อสู้ กับ Seal ที่รวมร่าง [S] At +1, Df +2
	{card_ability,
		s2_earth_no24_a1, 536, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {combine, y}], 1,							
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{at, 1}, {df, 2}]}, end_of_fighting,
											n, null, [null], null, [],
												null, [], null
	},
	%ขณะที่ [S] ต่อสู้ กับ [Wind] [S] At -2
	{card_ability,
		s2_earth_no24_a2, 536, 2, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {elem, 3}], 1,							
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,
											n, null, [null], null, [],
												null, [], null
	},
	%Growth: [Dragon] ธาตุ [Earth] + [Monster] เมื่อ [S] โจมตี Seal ที่ Sp มากกว่า [S] Seal ที่ถูกโจมตีนั้นแยกการรวมร่าง
	{card_ability,
		s2_earth_no24_a3, 536, 3, 
			n,[],
				n, null, [],									
					y, [{growth, y}, {action, attacker}],													
						y, null, [arena_zone], n, [{action, attacked}, {speed, more_than_s}, {combine, y}], 1,							
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										n, null, [], null,
											y, null, [arena_zone], n, [{action, attacked}, {speed, more_than_s}, {combine, y}],							
												y, {do_not_need_select, 0, [{action, break_combine}]}, null
	},
	%Growth: [Dragon] ธาตุ [Earth] + [Monster] [S] At +1 Df +1 Sp -1
	{card_ability,
		s2_earth_no24_a4, 536, 4, 
			n,[],
				n, null, [],									
					y, [{growth, y}, {action, on_arena}],													
						n, null, [], n, [], null,							
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{at, 1}, {df, 1}, {sp, -1}]}, null,
											n, null, [null], null, [],
												null, [], null
	},
	%[S] สามารถโจมตีจาก Df Line ได้
	{card_ability,
		s2_earth_no25_a1, 537, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [null], null, [], null,
							y, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{attack, from_df}]}, null,
											n, null, [null], null, [],
												null, [] ,null
	},
	%ขณะที่ [S] ต่อสู้กับ [Wind] [S] At -2
	{card_ability,
		s2_earth_no25_a2, 537, 2, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {elem, 3}], 1,							
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,
											n, null, [null], null, [],
												null, [], null
	},
	%ขณะที่ [S] ต่อสู้กับ [Water] [S] At +1
	{card_ability,
		s2_earth_no26_a1, 538, 1, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {elem, 2}], 1,							
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{at, 1}]}, end_of_fighting,
											n, null, [null], null, [],
												null, [], null
	},
	%ขณะที่ [S] ต่อสู้กับ [Tamer] [S] At -2
	{card_ability,
		s2_earth_no26_a2, 538, 2, 
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {type, "Tamer"}], 1,							
							n, [],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,
											n, null, [null], null, [],
												null, [], null
	},
	%Growth: [Dragon's Egg] [S] สามารถโจมตีจาก Df Line ได้
	{card_ability,
		s2_earth_no26_a3, 538, 3, 
			n,[],
				n, null, [],									
%					y, [{growth, y}, {action, on_arena}],		
					y, [{growth, y}, {action, growth_into_arena}],
						n, null, [null], null, [], null,
							y, [s_growth],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{attack, from_df}]}, null,
											n, null, [null], null, [],
												null, [], null
	},
	%Growth: [Dragon's Egg]%[S] สามารถโจมตีข้ามไปยัง Df Line ได้
	{card_ability,
		s2_earth_no26_a4, 538, 4, 
			n,[],
				n, null, [],									
%					y, [{growth, y}, {action, on_arena}],		
					y, [{growth, y}, {action, growth_into_arena}],
						n, null, [null], null, [], null,
							y, [s_growth],
								n, null, [], null,
									n, null, null, [],	null,							
										y, y, {do_not_need_select, 0, [{attack, to_df}]}, null,
											n, null, [null], null, [],
												null, [], null
	},
	%เมื่อ [S] โจมตี Seal ที่รวมร่าง ผู้ควบคุม [S] สามารถใช้ Df ของ [S] เทียบกับค่าพลังของ Seal ที่ถูก [S] โจมตี
	{card_ability,
		s2_earth_no28_a1, 540, 1,
			n,[],
				n, null, [],									
					y,[{zone, [arena_zone]},{action, attacker}],													
						y, null, [arena_zone], n, [{action, attacked}, {combine, y}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,
										y, y, {controller_can_activate_ability, 0, [{action, can_compare_df_to_target_power}]}, end_of_fighting,
											n, null, [null], null, [],
												null, [], null									
	},
	%[S] สามารถโจมตีจาก Df Line ได้
	{card_ability,
		s2_earth_n28_a2, 540, 2,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]},{action, on_arena}],												
						n, null, [null], null, [], null,
							y, [],
								n, null, [], null,
									n, null, null, [],	null,
										y, y, {do_not_need_select, 0, [{attack, from_df}]}, null,
											n, null, [null], null, [],
												null, [], null								
	},
	%เมื่อ [S] ถูกโจมตี [S] +Df ตาม Lv ของ Seal ที่โจมตี [S] จนจบ Subturn 
	{card_ability,
		s2_earth_no29_a1, 541, 1,
			n,[],
				n, null, [],									
					y,[{zone, [arena_zone]},{action, attacked}],													
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,
										y, y, {do_not_need_select, 0, [{df, {'+', attack_to_s_level}}]}, 1,
											n, null, [null], null, [],
												null, [], null									
	},
	%[S] สามารถโจมตีจาก Df Line ได้
	{card_ability,
		s2_earth_no29_a2, 541, 2,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]},{action, on_arena}],												
						n, null, [null], null, [], null,
							y, [],
								n, null, [], null,
									n, null, null, [],	null,
										y, y, {do_not_need_select, 0, [{attack, from_df}]}, null,
											n, null, [null], null, [],
												null, [], null								
	}
].