%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_seal_earth).
-export([earth/0]).
earth() ->
[ 
	{seal_card,528,
	                2,
	                16,
	                ["Python, Kerebandas Guardian"],
	                ["Dragon"],
	                [1],
	                [],
	                4,
	                1,
	                2,
	                7,
	                10,
	                2,
	                3}, 
	{seal_card,529,
	                2,
	                17,
	                ["Kamot, the Ghost of Waste Land"],
	                ["Evil"],
	                [1],
	                [],
	                3,
	                2,
	                2,
	                7,
	                7,
	                2,
	                3}, 
	{seal_card,530,
	                2,
	                18,
	                ["Yggdrasil"],
	                ["Divine",17226],
	                [1],
	                [],
	                5,
	                1,
	                3,
	                3,
	                12,
	                0,
	                3}, 
	{seal_card,531,
	                2,
	                19,
	                ["Megalasta"],
	                ["Monster"],
	                [1],
	                [],
	                4,
	                1,
	                2,
	                2,
	                10,
	                2,
	                3}, 
	{seal_card,532,
	                2,
	                20,
	                ["Floret Feme"],
	                ["Mage"],
	                [1],
	                [],
	                2,
	                1,
	                2,
	                6,
	                7,
	                2,
	                3}, 
	{seal_card,533,
	                2,
	                21,
	                ["The Dragon's Egg on the Rock"],
	                ["Dragon's Egg"],
	                [1],
	                [],
	                1,
	                1,
	                1,
	                0,
	                0,
	                0,
	                2}, 
	{seal_card,534,
	                2,
	                22,
	                ["Angorion Shaman"],
	                ["Mage"],
	                [1],
	                [],
	                2,
	                1,
	                1,
	                6,
	                8,
	                3,
	                2}, 
	{seal_card,535,
	                2,
	                23,
	                ["Ruin Therion"],
	                ["Monster"],
	                [1],
	                ["Therion"],
	                1,
	                1,
	                2,
	                4,
	                7,
	                2,
	                2}, 
	{seal_card,536,
	                2,
	                24,
	                ["Lainaur, the Forest Dragon"],
	                ["Dragon","Monster"],
	                [1],
	                [],
	                3,
	                1,
	                2,
	                7,
	                7,
	                4,
	                2}, 
	{seal_card,537,
	                2,
	                25,
	                ["Vorhil, the Highland Dragon"],
	                ["Dragon"],
	                [1],
	                [],
	                2,
	                1,
	                2,
	                6,
	                7,
	                3,
	                2}, 
	{seal_card,538,
	                2,
	                26,
	                ["Nilhir, the Baby Dragon"],
	                ["Dragon"],
	                [1],
	                ["Baby Dragon"],
	                1,
	                1,
	                1,
	                4,
	                6,
	                1,
	                1}, 
	{seal_card,539,2,27,["Tigery"],["Monster"],[1],[],1,1,1,4,6,2,1}, 
	{seal_card,540,2,28,["Scalo"],["Insect"],[1],[],1,1,1,3,6,1,1}, 
	{seal_card,541,2,29,["Havocana"],["Monster"],[1],[],1,1,1,4,3,2,1}, 
	{seal_card,542,
	                2,
	                30,
	                ["King Crown Viper"],
	                ["Monster"],
	                [1],
	                ["Viper"],
	                1,
	                1,
	                1,
	                3,
	                6,
	                1,
	                1}
].
