%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_fire).
-export([fire2_ability/0]).

fire2_ability() ->
[
	%[S] +At ตามจำนวน Seal ที่อยู่ใน At Line ฝ่ายเรา
	{card_ability,
		s2_fire_no31_a1, 543, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],											
							n, null, [null], null, [], null,
								y, [],
			                  n, null, [], null,
										n, null, null, [],	null,												
					                  y, y, {do_not_need_select, 0, [{at, {'+', {{target, owner, [arena_zone], seal, y}, [{line, 1}]}}}]}, null,											
												n, null, [null], null, [],
													null, [], null									
	},
	%[S] -At ตามจำนวน Seal ที่อยู่ใน At Line ฝ่ายตรงข้าม
	{card_ability,
		s2_fire_no31_a2, 543, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],											
							n, null, [null], null, [], null,
								y, [],
			                  n, null, [], null,
										n, null, null, [],	null,												
					                  y, y, {do_not_need_select, 0, [{at, {'-', {{target, opponent, [arena_zone], seal, null}, [{line, 1}]}}}]}, null,											
												n, null, [null], null, [],
													null, [], null									
	},
	%ขณะที่ [S] ต่อสู้ [S] +At ตาม Sp ของ Seal ที่ต่อสู้กับ [S] 
	{card_ability, 
		s2_fire_no32_a1, 544, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],																						
							n, null, [null], null, [], null,
								n, [],
									n, null, [], null,
										n, null, null, [],	null,												
											y, y, {do_not_need_select, 0, [{at, {'+', fighting_with_s_speed}}]}, end_of_fighting,											
												n, null, [null], null, [],
													null, [], null					
	},
	%ขณะที่ [S] ต่อสู้กับ [Water] [S] At –2 
	{card_ability, 
		s2_fire_no32_a2, 544, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],																						
							y, null, [arena_zone], n, [{action, fight}, {elem, 2}], 1,
								n, [],
									n, null, [], null,
										n, null, null, [],	null,												
											y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,											
												n, null, [null], null, [],
													null, [], null					
	},
	%ตราบเท่าที่ [S] รวมร่างกับ [Dragon] [S] สามารถโจมตีข้ามไปยัง Df Line ได้
	{card_ability,
		s2_fire_no33_a1, 545, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
									n, null, [], null,
										n, null, null, [], null,												
											y, y, {do_not_need_select, 0, [{attack, to_df}]}, null,											
												n, null, [null], null, [],
													null, [], null
	},
	%[Fire] ทุกใบในสนามฝ่ายเรา At +1 Df -3 (Df Line)
	{card_ability,
		s2_fire_no34_a1, 546, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
									n, null, [], null,
										n, null, null, [], null,												
											n, null, [], null,
												y, owner, [arena_zone], y, [{elem, 4}],																																		
													y, {do_not_need_select, 0, [{at, 1}, {df, -3}]}, null									
	},
	%เมื่อ [S] เข้ามาในสนาม [S] ได้รับ 3 Charge Counter 
	{card_ability, 
		s2_fire_no35_a1, 547, 1,
				n,[],
					n, null, [],									
						y, [{action, into_arena}, {stack_check, self}],													
							n, null, [null], null, [], null,
								c, [],
									n, null, [], null,
										n, null, null, [],	null,												
											y, y, {do_not_need_select, 0, [{counter, 3}]}, null,
												n, null, [null], null, [],
													null, [], null
	},
	%[S] ยกเลิก Mystic Card ประเภท [Relic] ฝ่ายตรงข้าม
	{card_ability, 
		s2_fire_no35_a2, 547, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
									n, null, [], null,
										n, null, null, [],	null,												
											y, y, {do_not_need_select, 0, [{cancel_mystic, [opponent_relic]}]}, null,
												n, null, [null], null, [],
													null, [], null
	},
	%เมื่อ [S] ตก Shrine จากสนาม Seal ทุกใบในสนามฝ่ายตรงข้าม At -1 / 1 Turn
	{card_ability, 
		s2_fire_no37_a1, 549, 1,
				n,[],
					n, null, [],									
						y, [{zone, [shrine_cards]}, {action, arena_to_shrine}, {action, into_shrine}, {stack_check, card_destroy}],													
							y, opponent, [arena_zone], null, [{card_type, seal}], 1,
								c, [],
									n, null, [], null,
										n, null, null, [],	null,												
											n, null, [], null,
												y, opponent, [arena_zone], null, [{card_type, seal}],
													y, {do_not_need_select, 0, [{at, -1}]}, 2
	},
	%ขณะที่ [S] ต่อสู้กับ [Wind] [S] At +2
	{card_ability, 
		s2_fire_no37_a2, 549, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],													
							y, null, [arena_zone], n, [{action, fight}, {elem, 3}], 1,
								n, [],
									n, null, [], null,
										n, null, null, [],	null,												
											y, y, {do_not_need_select, 0, [{at, 2}]}, end_of_fighting,
												n, null, [null], null, [],
													null, [], null
	},
	%ขณะที่ [S] ต่อสู้กับ [Water] [S] At -2
	{card_ability, 
		s2_fire_no37_a3, 549, 3,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],													
							y, null, [arena_zone], n, [{action, fight}, {elem, 2}], 1,
								n, [],
									n, null, [], null,
										n, null, null, [],	null,												
											y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,
												n, null, [null], null, [],
													null, [], null
	},
	%Growth: Niltinco, the Baby Dragon + [Fire] เมื่อ Seal ฝ่ายเราตก Shrine เราสามารถจั่วการ์ด 1 ใบ
	{card_ability, 
		s2_fire_no37_a4, 549, 4,
				n,[],
					n, null, [],									
						y, [{growth, y}, {zone, [arena_zone]}],													
							y, owner, [shrine_cards], n, [{action, into_shrine}, {card_type, seal}, {stack_check, card_destroy}], 1,
								n, [],
									y, y, {do_not_need_select, 0, [{draw_card, 1}]}, null,
										n, null, null, [],	null,												
											n, null, [], null,
												n, null, [null], null, [],
													null, [], null
	},
	%Growth: [Dragon] ธาตุ [Fire] [S] At +1 Df -1 
	{card_ability,
		s2_fire_no38_a1, 550, 1,
				n,[],
					n, null, [],									
						y, [{growth, y}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
			                  n, null, [], null,
										n, null, null, [],	null,												
					                  y, y, {do_not_need_select, 0, [{at, 1}, {df, -1}, {protect_attack, [attack_all]}]}, null,											
												n, null, [null], null, [],
													null, [], null									
	},
	%%Growth: [Dragon] หรือ [Earth] [S] สามารถโจมตีจาก Df Line ได้
%	{card_ability,
%		s2_fire_no38_a3, 550, 3,
%				n,[],
%					n, null, [],									
%						y, [{growth, y}, {action, growth_on_arena}],													
%							n, null, [null], null, [], null,
%								y, [s_growth],
%			                  n, null, [], null,
%										n, null, null, [],	null,												
%					                  y, y, {do_not_need_select, 0, [{attack, from_df}]}, null,											
%												n, null, [null], null, [],
%													null, [], null									
%	},
	%ตราบเท่าที่มี [Fire] ใน Shrine เรา [S] At +1
	{card_ability,
		s2_fire_no39_a1, 551, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
				               n, null, [], null,
										n, null, null, [], null,												
						               y, y, {do_not_need_select, 0, [{at, 1}]}, null,									
												n, null, [null], null, [],
													null, [] ,null									
	},
	%ตราบเท่าที่มี [Knight] ใน Shrine เรา [S] At +2
	{card_ability,
		s2_fire_no39_a2, 551, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
				               n, null, [], null,
										n, null, null, [], null,													
					                  y, y, {do_not_need_select, 0, [{at, 2}]}, null,
												n, null, [null], null, [],
													null, [], null										
	},
	%ตราบเท่าที่มี [Dragon] ตั้งแต่ 3 ใบขึ้นไปในสนามฝ่ายเรา [S] At +2
	{card_ability,
		s2_fire_no40_a1, 552, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
			                  n, null, [], null,
										n, null, null, [],	null,												
					                  y, y, {do_not_need_select, 0, [{at, 2}]}, null,											
												n, null, [null], null, [],
													null, [], null										
	},
	%ขณะที่ [S] ต่อสู้กับ [Light] [S] At +2
	{card_ability,
		s2_fire_no41_a1, 553, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],													
							y, null, [arena_zone], n, [{action, fight}, {elem, 6}], 1,
								n, [],
			                  n, null, [], null,
										n, null, null, [],	null,												
					                  y, y, {do_not_need_select, 0, [{at, 2}]}, end_of_fighting,											
												n, null, [null], null, [],
													null, [], null										
	},
	%ขณะที่ [S] ต่อสู้กับ [Water] [S] At -2
	{card_ability,
		s2_fire_no41_a2, 553, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],													
							y, null, [arena_zone], n, [{action, fight}, {elem, 2}], 1,
								n, [],
			                  n, null, [], null,
										n, null, null, [],	null,												
					                  y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,											
												n, null, [null], null, [],
													null, [], null										
	},
	%ขณะที่ [S] ต่อสู้กับ [Wind] [S] At +1
	{card_ability,
		s2_fire_no42_a1, 554, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],													
							y, null, [arena_zone], n, [{action, fight}, {elem, 3}], 1,
								n, [],
			                  n, null, [], null,
										n, null, null, [], null,												
					                  y, y, {do_not_need_select, 0, [{at, 1}]}, end_of_fighting,											
												n, null, [null], null, [],
													null, [], null										
	},
	%ขณะที่ [S] ต่อสู้กับ [Tamer] [S] At -2
	{card_ability,
		s2_fire_no42_a2, 554, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, fight}],													
							y, null, [arena_zone], n, [{action, fight}, {type, "Tamer"}], 1,
								n, [],
			                  n, null, [], null,
										n, null, null, [],	null,												
					                  y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,											
												n, null, [null], null, [],
													null, [], null										
	},
	%Growth: [Dragon's Egg] ผู้เล่นฝ่ายตรงข้ามไม่สามารถสั่ง Seal โจมตีข้ามไปยัง Df Line ได้ (At line)
	{card_ability,
		s2_fire_no42_a3, 554, 3,
				n,[],
					n, null, [],									
						y, [{growth, y}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
			                  n, null, [], null,
										y, y, opponent, {do_not_need_select, 0, [{player_assign_atk, {disallow, across_to_df}}]}, null,												
					                  n, null, [], null,											
												n, null, [null], null, [],
													null, [], null										
	},
	%[S] +At ตามจำนวน [S] ใบอื่นใน Shrine เรา
	{card_ability,
		s2_fire_no45_a1, 557, 1,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
				               n, null, [], null,
										n, null, null, [], null,													
					                  y, y, {do_not_need_select, 0, [{at, {'+', {{target, owner, [shrine_cards], seal, null}, [{name, "Scarlet"}]}}}]}, null,
												n, null, [null], null, [],
													null, [], null										
	},
	%เมื่อ [S] ตก Shrine [Dragon] ทุกใบในสนาม At +1 Df -1 / 1 Turn
	{card_ability,
		s2_fire_no46_a1, 558, 1,
				n,[],
					n, null, [],									
						y, [{zone, [shrine_cards]}, {action, into_shrine}],													
							y, null, [arena_zone], y, [{type, "Dragon"}], 1,
								n, [],
				               n, null, [], null,
										n, null, null, [],	null,												
						               n, null, {}, null,											
												y, null, [arena_zone], y, [{type, "Dragon"}],
													y, {do_not_need_select, 0, [{at, 1}, {df, -1}]}, 2
	},
	%ผู้เล่นไม่สามารถสั่ง [S] โจมตีได้
	{card_ability,
		s2_fire_no46_a2, 558, 2,
				n,[],
					n, null, [],									
						y, [{zone, [arena_zone]}, {action, on_arena}],													
							n, null, [null], null, [], null,
								y, [],
			                  n, null, [], null,
										n, null, null, {}, null,												
					                  y, y, {do_not_need_select, 0, [{assign_atk, disallow}]}, null,
												n, null, [null], null, [],
													null, [], null										
	}
].