%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_seal_fire).
-export([fire/0]).
fire() ->
[ 
	{seal_card,543,
	                2,
	                31,
	                ["Salamandera"],
	                ["Dragon"],
	                [4],
	                ["Salamandera"],
	                3,
	                2,
	                3,
	                8,
	                9,
	                3,
	                3}, 
	{seal_card,544,
	                2,
	                32,
	                ["Magma Dragon"],
	                ["Dragon"],
	                [4],
	                [],
	                4,
	                2,
	                3,
	                6,
	                4,
	                4,
	                3}, 
	{seal_card,545,
	                2,
	                33,
	                ["Zadin, Knight of Wands"],
	                ["Knight"],
	                [4],
	                ["Zadin"],
	                5,
	                3,
	                4,
	                10,
	                10,
	                3,
	                3}, 
	{seal_card,546,
	                2,
	                34,
	                ["Nerimor, Princess of Wands"],
	                ["Mage"],
	                [4],
	                ["Nerimor"],
	                4,
	                3,
	                3,
	                9,
	                9,
	                4,
	                3}, 
	{seal_card,547,
	                2,
	                35,
	                ["Ariane, the Sword Gunner"],
	                ["Gunner"],
	                [4],
	                [],
	                3,
	                1,
	                2,
	                7,
	                7,
	                3,
	                3}, 
	{seal_card,548,
	                2,
	                36,
	                ["Rawega, the Goddess of Sagacity"],
	                ["Divine"],
	                [4],
	                [],
	                2,
	                1,
	                2,
	                7,
	                6,
	                3,
	                3}, 
	{seal_card,549,
	                2,
	                37,
	                ["Telepaha, the Flare Dragon"],
	                ["Dragon"],
	                [4],
	                [],
	                3,
	                1,
	                2,
	                7,
	                8,
	                3,
	                2}, 
	{seal_card,550,
	                2,
	                38,
	                ["Nordilion, the Desert Dragon"],
	                ["Dragon"],
	                [4],
	                [],
	                2,
	                1,
	                2,
	                7,
	                6,
	                3,
	                2}, 
	{seal_card,551,
	                2,
	                39,
	                ["Necrotrooper"],
	                ["Evil"],
	                [4],
	                [],
	                2,
	                1,
	                2,
	                5,
	                0,
	                4,
	                2}, 
	{seal_card,552,2,40,["Lava Drake"],["Dragon"],[4],[],3,2,2,8,6,4,2}, 
	{seal_card,553,
	                2,
	                41,
	                ["Minyaernil, the Volcanic Dragon"],
	                ["Dragon"],
	                [4],
	                [],
	                2,
	                1,
	                2,
	                7,
	                5,
	                4,
	                2}, 
	{seal_card,554,
	                2,
	                42,
	                ["Niltinco, the Baby Dragon"],
	                ["Dragon"],
	                [4],
	                ["Baby Dragon"],
	                1,
	                1,
	                1,
	                5,
	                5,
	                3,
	                1}, 
	{seal_card,555,
	                2,
	                43,
	                ["Desert Chimera"],
	                ["Monster"],
	                [4],
	                [],
	                3,
	                1,
	                2,
	                7,
	                8,
	                3,
	                1}, 
	{seal_card,556,2,44,["Infernos"],["Evil"],[4],[],2,1,1,5,5,3,1}, 
	{seal_card,557,2,45,["Scarlet"],["Insect"],[4],[],1,1,1,4,4,4,1}, 
	{seal_card,558,2,46,["The Dragon’s Egg in the Valcano"],["Dragon's Egg"],[4],[],1,0,1,5,5,0,1},
	{seal_card,622,2,110,["Fire Whip Maiden"],["Mage"],[4],[],2,1,2,7,5,3,2}
].
