%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_seal_light).
-export([light/0]).
light() ->
[ 
	{seal_card,513,
	                2,
	                1,
	                ["Divine Dragon"],
	                ["Dragon"],
	                [6],
	                [],
	                4,
	                2,
	                3,
	                7,
	                9,
	                3,
	                3}, 
	{seal_card,514,
	                2,
	                2,
	                ["Angorion, the Earth Spirit"],
	                ["Divine"],
	                [6],
	                [],
	                2,
	                1,
	                2,
	                6,
	                7,
	                1,
	                3}, 
	{seal_card,515,
	                2,
	                3,
	                ["Penguin Family"],
	                ["Monster"],
	                [6],
	                ["Penguin"],
	                3,
	                1,
	                2,
	                6,
	                6,
	                4,
	                3}, 
	{seal_card,516,
	                2,
	                4,
	                ["Alessandra, the Angel of Blessing"],
	                ["Divine"],
	                [6],
	                ["Angel"],
	                2,
	                1,
	                1,
	                3,
	                4,
	                2,
	                3}, 
	{seal_card,517,
	                2,
	                5,
	                ["Gorothparma , the Weapon of Gods"],
	                ["Dragon"],
	                [6, 4],
	                [],
	                2,
	                3,
	                2,
	                6,
	                7,
	                3,
	                3}, 
	{seal_card,518,
	                2,
	                6,
	                ["Brigitte, the Valkyrie"],
	                ["Knight"],
	                [6],
	                [],
	                3,
	                1,
	                2,
	                7,
	                9,
	                3,
	                2}, 
	{seal_card,519,
	                2,
	                7,
	                ["Quelleiavas, the Holy Light Dragon"],
	                ["Dragon","Divine"],
	                [6],
	                [],
	                3,
	                1,
	                2,
	                7,
	                7,
	                5,
	                2}, 
	{seal_card,520,
	                2,
	                8,
	                ["Sanctuary's Guard"],
	                ["Knight"],
	                [6],
	                [],
	                3,
	                1,
	                2,
	                7,
	                8,
	                4,
	                2}, 
	{seal_card,521,2,9,["ShinShin"],["Monster"],[6],[],3,1,2,7,8,3,2}, 
	{seal_card,522,
	                2,
	                10,
	                ["Ekklesia Dragoon"],
	                ["Dragon","Knight"],
	                [6],
	                ["Dragoon"],
	                3,
	                2,
	                2,
	                8,
	                8,
	                3,
	                2}, 
	{seal_card,523,
	                2,
	                11,
	                ["Palanalcar, the Baby Dragon"],
	                ["Dragon"],
	                [6],
	                ["Baby Dragon"],
	                1,
	                1,
	                1,
	                5,
	                5,
	                3,
	                1}, 
	{seal_card,524,
	                2,
	                12,
	                ["The Dragon's Egg in the Temple"],
	                ["Dragon's Egg"],
	                [6],
	                [],
	                1,
	                1,
	                1,
	                3,
	                6,
	                0,
	                1}, 
	{seal_card,525,
	                2,
	                13,
	                ["Hillside Dragon"],
	                ["Dragon"],
	                [6],
	                [],
	                1,
	                1,
	                1,
	                5,
	                5,
	                3,
	                1}, 
	{seal_card,526,
	                2,
	                14,
	                ["Beneath Sea Tail"],
	                ["Insect"],
	                [6],
	                [],
	                2,
	                1,
	                1,
	                5,
	                5,
	                3,
	                1}, 
	{seal_card,527,2,15,["Scalight"],["Insect"],[6],[],1,1,1,4,5,4,1},
	{seal_card,621,
	                2,
	                109,
	                ["Humble Judge"],
	                ["Mage"],
	                [6],
	                [],
	                2,
	                1,
	                2,
	                6,
	                8,
	                3,
	                2}
	
	
].
