%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set2_wind).
-export([wind2_ability/0]).

wind2_ability() ->
[
	{card_ability, 
		s2_wind_no062_a1, 574, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, combine_success}, {stack_check, self}],													
						n, null, [], null, [], null,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{at, 1}]}, end_of_subturn,											
											n, null, [null], null, [],
												null, [], null									 
	},
	%ขณะที่ [S] ต่อสู้กับ [Fire] [S] At –2
	{card_ability, 
		s2_wind_no063_a1, 575, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {elem, 4}], 1,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,											
											n, null, [null], null, [],
												null, [], null									 
	},
	%ขณะที่ S ต่อสู้ เทียบค่าพลังของ [S] กับ At ของ Seal ที่ต่อสู้กับ [S]
	{card_ability, 
		s2_wind_no067_a1, 579, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						n, null, [null], null, [], null,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{combat, {when_fight_attack, {power, at}}}, {combat, {when_fight_target, {at, power}}}]}, end_of_fighting,											
											n, null, [null], null, [],
												null, [], null									 
	},
	%[S] ยกเลิก Freeze Curse
	{card_ability, 
		s2_wind_no068_a1, 580, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [], null, [], null,
							y, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{cancel_curse, [freeze_curse]}]}, null,											
											n, null, [null], null, [],
												null, [] ,null									
	},
	%Growth: Dimminuial, the Baby Dragon [S] At +1
	{card_ability, 
		s2_wind_no068_a2, 580, 2,
			n,[],
				n, null, [],									
					y, [{growth, y}, {action, on_arena}],													
						n, null, [], n, [], null,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{at, 1}]}, null,											
											n, null, [null], null, [],
												null, [], null									 
	},
	%ขณะที่ต่อสู้ [S] Sp +1 และ Seal ที่ต่อสู้กับ [S] Sp -1
	{card_ability, 
		s2_wind_no069_a1, 581, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}], 1,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{sp, 1}]}, end_of_fighting,											
											y, null, [arena_zone], n, [{action, fight}],
												y, {do_not_need_select, 0, [{sp, -1}]}, end_of_fighting									 
	},
	%%%%%%%%%%%%%%%%%%เมื่อ [S] ออกจากสนาม เราสามารถจั่วการ์ด 1 ใบ
	{card_ability, 
		s2_wind_no070_a1a, 582, 1,
			n,[],
				n, null, [],									
					y, [{zone, [shrine_cards]}, {action, into_shrine}, {action, arena_to_shrine}, {stack_check, card_destroy}],													
						n, null, [], null, [], null,
							n, [],
			               y, y, {owner_can_activate_ability, 0, [{draw_card, 1}]}, null,
									n, null, null, [],	null,												
					               n, null, [], null,
											n, null, [null], null, [],
												null, [] ,null									
	},
	{card_ability, 
		s2_wind_no070_a1b, 582, 1,
			n,[],
				n, null, [],									
					y, [{zone, [remove_cards]}, {action, into_remove}, {action, remove_from_arena}],													
						n, null, [], null, [], null,
							n, [],
			               y, y, {owner_can_activate_ability, 0, [{draw_card, 1}]}, null,
									n, null, null, [],	null,												
					               n, null, [], null,
											n, null, [null], null, [],
												null, [] ,null									
	},
	{card_ability, 
		s2_wind_no070_a1c, 582, 1,
			n,[],
				n, null, [],									
					y, [{zone, [hand_cards]}, {action, arena_to_hand}],													
						n, null, [], null, [], null,
							n, [],
			               y, y, {owner_can_activate_ability, 0, [{draw_card, 1}]}, null,
									n, null, null, [],	null,												
					               n, null, [], null,
											n, null, [null], null, [],
												null, [] ,null									
	},
	{card_ability, 
		s2_wind_no070_a1d, 582, 1,
			n,[],
				n, null, [],									
					y, [{zone, [seal_deck]}, {action, into_library}, {action, arena_to_library}],													
						n, null, [], null, [], null,
							n, [],
			               y, y, {owner_can_activate_ability, 0, [{draw_card, 1}]}, null,
									n, null, null, [],	null,												
					               n, null, [], null,
											n, null, [null], null, [],
												null, [] ,null									
	},
	%ผู้เล่นไม่สามารถสั่ง [S] โจมตีได้
	{card_ability, 
		s2_wind_no070_a2, 582, 2,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [], null, [], null,
							y, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{assign_atk, disallow}]}, null,
											n, null, [null], null, [],
												null, [] ,null									
	},
	%071   Tanorod, the Wasteland Dragon
	%[S] +At ตามจำนวน Seal ที่ติด Poison Curse
	{card_ability, 
		s2_wind_no071_a1, 583, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, on_arena}],													
						n, null, [], null, [], null,
							y, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{at, {'+', {{target, null, [arena_zone], seal, y}, [{curse, poison_curse}]}}}]}, null,
											n, null, [null], null, [],
												null, [] ,null									
	},
	%ขณะที่ [S] ต่อสู้กับ [Earth] [S] At +1
	{card_ability, 
		s2_wind_no073_a1, 585, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {elem, 1}], 1,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{at, 1}]}, end_of_fighting,											
											n, null, [null], null, [],
												null, [], null									 
	},
	%ขณะที่ [S] ต่อสู้กับ [Tamer] [S] At -2
	{card_ability, 
		s2_wind_no073_a2, 585, 2,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, fight}],													
						y, null, [arena_zone], n, [{action, fight}, {type, "Tamer"}], 1,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {do_not_need_select, 0, [{at, -2}]}, end_of_fighting,											
											n, null, [null], null, [],
												null, [], null									 
	},
	%Growth: [Dragon's Egg] เมื่อ [S] โจมตีสำเร็จ ผู้ควบคุมจั่วการ์ด 1 ใบ
	{card_ability, 
		s2_wind_no073_a3, 585, 3,
			n,[],
				n, null, [],									
					y, [{action, attack_success}, {growth, y}],													
						n, null, [null], null, [], null,
							n, [],
			               y, y, {do_not_need_select, 0, [{draw_card, 1}]}, null,
									n, null, null, [],	null,												
					               n, n, [], null,											
											n, null, [null], null, [],
												null, [], null									 
	},
	%เมื่อ [S] เข้ามาในสนาม แสดง Seal ใบบนสุด 3 ใบจากกองการ์ด Seal เรา จากนั้นเราสามารถนำ [Insect] 1 ใบจากการ์ดที่แสดงขึ้นมือเรา
	{card_ability, 
		s2_wind_no074_a1a, 586, 1,
			n,[],
				n, null, [],									
					y, [{action, into_arena}, {stack_check, self}],													
						y, owner, [{seal_deck, top, 3}], null, [], 3,
							{then_do, s2_wind_no074_a1b}, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               n, n, [], null,											
											y, owner, [{seal_deck, top, 3}], null, [],
												y, {do_not_need_select, 0, [{action, {show, 3, [{type, "Insect"}], move_to_hand, 1}}]}, null									 
	},
	{card_ability, 
		s2_wind_no074_a1b, 586, 1,
			n,[],
				n, null, [],									
					y, [{action, into_arena}, {stack_check, self}],													
						y, owner, [seal_deck], null, [{action, show}, {type, "Insect"}], 1,
							n, [],
			               n, null, [], null,
									n, null, null, [], null,												
					               n, n, [], null,											
											y, owner, [seal_deck], null, [{action, show}, {type, "Insect"}],
												y, {owner_can_select_exact_target, 1, [{action, move_to_hand}]}, null									 
	},
	%เมื่อจบ Subturn โจมตีของผู้ควบคุม [S] เราสามารถทิ้งการ์ด 1 ใบในมือ และ [S] เปลี่ยน Line (ผลจาก Ability  นี้ ไม่นับว่าเป็นการกำหนด Line)
	{card_ability, 
		s2_wind_no075_a1a, 587, 1,
			n,[],
				y, controller, [{turn, at}, {pharse, eos}],									
					y, [{zone, [arena_zone]}, {line, null}, {can_move_to, any}],													
						n, null, [], null, [], null,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               n, null, {}, null,											
											y, owner, [hand_cards], null, [],
												y, {owner_can_select_exact_target, 1, [{action, discard}]}, null									
	},
	{card_ability, 
		s2_wind_no075_a1b, 587, 1,
			n,[],
				y, controller, [{turn, at}, {pharse, eos}],									
					y, [{zone, [arena_zone]}, {line, null}, {can_move_to, any}],													
						n, null, [], null, [], null,
							n, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               y, y, {{check, s2_wind_no075_a1a, do_not_need_select}, 0, [{action, change_line}]}, null,											
											n, null, [], null, [],
												n, {}, null									
	},
	%เมื่อ [S] ตก Shrine เราต้องจั่วการ์ด 1 ใบ   
	{card_ability, 
		s2_wind_no076_a1, 588, 1,
			n,[],
				n, null, [],									
					y, [{zone, [shrine_cards]}, {action, into_shrine}, {stack_check, card_destroy}],													
						n, null, [], null, [], null,
							n, [],
			              y, y, {do_not_need_select, 0, [{draw_card, 1}]}, null,
									n, null, null, [],	null,												
					               n, null, [], null,											
											n, null, [null], null, [],
												null, [] ,null									
	},
	%เมื่อ [S] เข้ามาในสนาม เราสามารถนำ [S] ใบอื่น 1 ใบเข้ามาในสนามจากมือเรา
	{card_ability, 
		s2_wind_no077_a1, 589, 1,
			n,[],
				n, null, [],									
					y, [{action, into_arena}, {stack_check, self}],													
						y, owner, [hand_cards], n, [{card_type, seal}, {name, "Garuda Lancer"}], 1,
							c, [],
			               n, null, [], null,
									n, null, null, [],	null,												
					               n, n, [], null,											
											y, owner, [hand_cards], n, [{card_type, seal}, {name, "Garuda Lancer"}],
												y, {owner_can_select_exact_target, 1, [{action, move_to_arena}]}, null									 
	}
].