%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(set3_fire).
-export([fire3_ability/0]).

fire3_ability() ->
[
%*36 เมื่อ [S] โจมตี [S] At +1 จนจบ Subturn
	{card_ability, 
		s3_fire_no036_a1, 804, 1,
			n,[],
				n, null, [],									
					y, [{action, attacker}],											
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [], null,
										y, y, {do_not_need_select, 0, [{at, 1}]}, end_of_subturn,										
											n, null, [null], null, [],
												null, [] ,null
	},
%37 ใน Subturn โจมตีของผู้ควบคุม [S] ถ้าผู้ควบคุม [S] ไม่สั่ง [S] โจมตี เมื่อเข้าสู่ Subturn ป้องกันของผู้ควบคุม [S] [S] ติด Freeze Curse จนจบ Subturn 
	{card_ability, 
		s3_fire_no037_a1, 805, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]},{action, assign_attack}],											
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [], null,
										y, y, {do_not_need_select, 0, [{add_flag, attack_last_subturn}]}, null,										
											n, null, [null], null, [],
												null, [] ,null
	},
	{card_ability, 
		s3_fire_no037_a2, 805, 2,
			y, [{turn, df}, {pharse, checkup}],								
				n, null, [],		
					y, [{zone, [arena_zone]}, {check_flag, {n, attack_last_subturn}}, {curse, {n, freeze_curse}}, {protect_curse, {n, freeze_curse}}],
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [], null,
										y, y, {do_not_need_select, 0, [{curse, freeze_curse}]}, 1,									
											n, null, [null], null, [],
												null, [] ,null
	},
	{card_ability, 
		s3_fire_no037_a3, 805, 3,
			y, [{turn, df}, {pharse, checkup}],								
				n, null, [],		
					y, [{zone, [arena_zone]},{check_flag, attack_last_subturn}],
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [], null,
										y, y, {do_not_need_select, 0, [{clear_flag, attack_last_subturn}]}, null,										
											n, null, [null], null, [],
												null, [] ,null
	},
%*39 เมื่อ [S] เข้ามาในสนาม Seal ทุกใบในสนามฝ่ายตรงข้าม At -1 Df -1 / 1 Turn
	{card_ability, 
		s3_fire_no039_a1, 807, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, into_arena}],													
						y, opponent, [arena_zone], null, [{card_type, seal}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,												
										n, null, [], null,
											y, opponent, [arena_zone], null, [{card_type, seal}],
												y, {do_not_need_select, 0, [{at, -1},{df, -1}]}, 2
	},
%*39 เมื่อ [S] ตก Shrine Seal ทุกใบในสนามฝ่ายตรงข้าม At -1 Df -1 / 1 Turn
	{card_ability, 
		s3_fire_no039_a2, 807, 2,
			n,[],
				n, null, [],							
					y, [{zone, [shrine_cards]}, {action, into_shrine}],													
						y, opponent, [arena_zone], null, [{card_type, seal}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,												
										n, null, [], null,
											y, opponent, [arena_zone], null, [{card_type, seal}],
												y, {do_not_need_select, 0, [{at, -1},{df, -1}]}, 2
	},
%*40 Charging 2
	{card_ability, 
		s3_fire_no040_a1, 808, 1,
			y,[{turn, at}, {pharse, checkup}],
				n, null, [],									
					y, [{zone, [arena_zone]}, {counter, {less_than, 2}}],													
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,												
										y, y, {do_not_need_select, 0, [{counter, 1}]}, null,											
											n, null, [null], null, [],
												null, [] ,null										
	},
%*41 เมื่อ [S] โจมตีสำเร็จ ผู้ควบคุม [S] Sacrifice [Ins] 1 ใบ ถ้าไม่สามารถ Sacrifice [Ins] ได้ทำลาย [S]
	{card_ability, 
		s3_fire_no041_a1, 809, 1,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, attack_success}],													
						y, controller, [arena_zone], y, [{type, "Insect"}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,												
										n, null, [], null,											
											y, controller, [arena_zone], null, [{card_type, seal},{type, "Insect"}],
												y, {controller_select_exact_target, 1, [{player_action, sacrifice}]}, null								 
	},
	{card_ability, 
		s3_fire_no041_a2, 809, 2,
			n,[],
				n, null, [],									
					y, [{zone, [arena_zone]}, {action, attack_success}],													
						y, controller, [arena_zone], y, [{type, "Insect"}], {less_than, 1},
							n, [],
								n, null, [], null,
									n, null, null, [],	null,												
										y, y, {do_not_need_select, 0, [{action, destroy}]}, null,											
											n, null, [null], null, [],
												null, [] ,null
	},
%43 เมื่อ [S] ตก Shrine จากกองการ์ด ผู้เล่นทุกคนสามารถนำ [Be] 1 ใบเข้ามาในสนามจากมือ
	{card_ability, 
		s3_fire_no043_a1, 811, 1,
			n,[],
				n, null, [],									
					y, [{action, into_shrine}, {action, deck_to_shrine}, {stack_check, self}],
						y, opponent, [hand_cards], null, [{card_type, seal},{type, "Beast"}], 1,
							n, [],
								n, n, [], null,
									n, null, null, [],	null,												
										n, n, [], null,											
											y, opponent, [hand_cards], y, [{card_type, seal},{type,"Beast"}],
												y, {opponent_can_select_exact_target, 1, [{action, move_to_arena}]} ,null				
	},
	{card_ability, 
		s3_fire_no043_a2, 811, 2,
			n,[],
				n, null, [],									
					y, [{action, into_shrine}, {action, deck_to_shrine}, {stack_check, self}],
						y, owner, [hand_cards], null, [{card_type, seal},{type, "Beast"}], 1,
							n, [],
								n, n, [], null,
									n, null, null, [],	null,												
										n, n, [], null,											
											y, owner, [hand_cards], y, [{card_type, seal},{type, "Beast"}],
												y, {owner_can_select_exact_target, 1, [{action, move_to_arena}]} ,null				
	},	
%44 เมื่อ [S] เข้ามาในสนามหรือตก Shrine จากกองการ์ด เราสามารถ Sacrifice Seal 1 ใบ จากนั้น Seal 1 ใบในสนามสูญเสีย Ability 3 Subturn
		{card_ability, 
		s3_fire_no044_a1a, 812, 1,
			n, [],
				n, null, [],
					y, [{action, into_arena}, {action, deck_to_arena}],
						y, owner, [arena_zone], y, [{card_type, seal}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,
										n, null, [], null, 
											y, owner, [arena_zone], y, [{card_type, seal}],
												y, {owner_can_select_exact_target, 1, [{player_action, sacrifice}]}, null
	},
	{card_ability, 
		s3_fire_no044_a1b, 812, 1,
			n, [],
				n, null, [],									
					y, [{action, into_arena}, {action, deck_to_arena}],
						y, null, [arena_zone], y, [{card_type, seal}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,										
										n, null, [], null, 
											y, null, [arena_zone], y, [{card_type, seal}],
												y, {owner_select_exact_target, 1, [{ability, {loss, [all]}}]}, 3
	},
	{card_ability, 
		s3_fire_no044_a2a, 812, 2,
			n, [],
				n, null, [],									
					y, [{action, into_shrine}, {action, deck_to_shrine}],
						y, owner, [arena_zone], y, [{card_type, seal}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,										
										n, null, [], null, 
											y, owner, [arena_zone], y, [{card_type, seal}],
												y, {owner_can_select_exact_target, 1, [{player_action, sacrifice}]}, null
	},
	{card_ability, 
		s3_fire_no044_a2b, 812, 2,
			n, [],
				n, null, [],									
					y, [{action, into_shrine}, {action, deck_to_shrine}],
						y, null, [arena_zone], y, [{card_type, seal}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,										
										n, null, [], null, 
											y, null, [arena_zone], y, [{card_type, seal}],
												y, {owner_select_exact_target, 1, [{ability, {loss, [all]}}]}, 3
	},
%*45 เมื่อ [S] ตก Shrine จากสนาม [Machine] 1 ใบฝ่ายเรา At +1 / 1 Turn
	{card_ability, 
		s3_fire_no045_a1, 813, 1,
			n,[],
				n, null, [],									
					y, [{zone, [shrine_cards]}, {action, into_shrine}, {action, arena_to_shrine}],													
						y, owner, [arena_zone], y, [{card_type, seal},{type, "Machine"}], 1,
							n, [],
								n, n, [], null,
									n, null, null, [],	null,												
										n, n, [], null,											
											y, owner, [arena_zone], y, [{card_type, seal},{type,"Machine"}],
												y, {owner_select_exact_target, 1, [{at, 1}]} ,2				
	},
%*45 [S] ยกเลิก Mystic Card
	{card_ability, 
		s3_fire_no045_a2, 813, 2,
			n, [],
				n, null, [],									
					y,[{zone, [arena_zone]}, {action, on_arena}],				
						n, null, [null], null, [], null,
							y, [],
								n, null, [], null,                       
									n, null, null, [],	null,												
										y, y, {do_not_need_select, 0, [{cancel_mystic, [all]}]}, null,											
											n, null, [null], null, [],
													null, [] ,null					
	},
%*48 เมื่อ [S] เข้ามาในสนาม เราสามารถ Sacrifice [Uni] 1 ใบ [S] + At ตาม Lv ของ [Uni] นั้น [Inf] Turn
	{card_ability, 
		s3_fire_no048_a1a, 816, 1,
			n, [],
				n, null, [],									
					y, [{action, into_arena}, {stack_check, self}],
						y, owner, [arena_zone], y, [{card_type, seal},{naming, "Unicorn"}], 1,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,										
										n, null, [], null, 
											y, owner, [arena_zone], y, [{card_type, seal},{naming, "Unicorn"}],
												y, {owner_can_select_exact_target, 1, [{player_action, {sacrifice, put_value, {s3_fire_no048_a1a, level}}}]}, null
	},
	{card_ability, 
		s3_fire_no048_a1b, 816, 1,
			n, [],
				n, null, [],									
					y, [{action, into_arena}, {stack_check, self}],
						n, null, [null], null, [], null,
							n, [],
								n, null, [], null,
									n, null, null, [],	null,												
										y, y, {{check, s3_fire_no048_a1a, do_not_need_select}, 0, [{at, {'+', {get_value, s3_fire_no048_a1a}}}]}, 98,									
											n, null, [null], null, [],
													null, [] ,null
	}
].