%% Copyright (c) 2008-2013, Nanusorn Photpipat <nanusorn@photpipat.com>
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.
%%
%% THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
%% WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
%% MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
%% ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
%% WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
%% ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
%% OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.-module (ability_effect).
-module(skill_set1).
-compile(export_all).

light_skill() ->
	[
		%[Skill]-à¸—à¸´à¹?à¸? Mystic Card 1 à¹?à¸?à¹?à¸?à¸¡à¸·à¸­à¸?à¸¹à¹?à¹?à¸?à¹? Skill;  
		{card_skill,
			s1_light_no004_s1, 260, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, owner, [hand_cards], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [hand_cards], mystic, n, [],
														{player_select_exact_target, 1, [{action, move_to_shrine}]} ,0,
															n, null, [null], null, null, [],
																[], null	
		},
		%à¸—à¸³à¸¥à¸²à¸¢ Mystic Card 1 à¹?à¸?à¹?à¸?à¸ªà¸?à¸²à¸¡ (Mp 2)
		{card_skill,
			s1_light_no004_s2, 260, 2, n,
				y, 
					null, null, 
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], mystic, n, [],
														{player_select_exact_target, 1, [{action, move_to_remove_zone}]} ,0,
															n, null, [null], null, null, [],
																[], null
		},
		%[Skill]â€“à¸?à¸³ Mystic Card 1 à¹?à¸?à¹?à¸? Shrine à¸?à¸¹à¹?à¹?à¸?à¹? Skill à¸?à¸¥à¸±à¸?à¸?à¸¶à¹?à¸?à¸¡à¸·à¸­
		{card_skill,
			s1_light_no005_s1a, 261, 1, n,
				y, 
					s1_light_no005_s1b, null,
						n, [],
							n, null, [],									
								n, [], 											
									y, owner, [shrine_cards], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [shrine_cards], mystic, n, [],
														{player_select_exact_target, 1, [{action, move_to_hand}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%à¹€à¸¡à¸·à¹?à¸­ Mystic Card à¸?à¸±à¹?à¸?à¸•à¸? Shrine à¸?à¸³à¸­à¸­à¸?à¸?à¸²à¸?à¹€à¸?à¸¡
		{card_skill,
			s1_light_no005_s1b, 261, 1, n,
				y, 
					null, s1_light_no005_s1a,
						n, [],
							n, null, [],									
								n, [], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													n, null, [null], null, null, [],
														{do_not_need_select, 0, [{move, to_remove_zone}]}, result_to_shrine,
															n, null, [null], null, null, [],
																[] ,null
		},
		% à¹€à¸¡à¸·à¹?à¸­à¸?à¸? Subturn à¸–à¹?à¸²à¹?à¸¡à¹?à¹?à¸”à¹?à¹?à¸?à¹? Mystic Card à¸?à¸±à¹?à¸? à¸?à¸³ Mystic Card à¸?à¸±à¹?à¸?à¸­à¸­à¸?à¸?à¸²à¸?à¹€à¸?à¸¡ à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸?
		{card_skill,
			s1_light_no005_s1c, 261, 1, n,
				y, 
					null, s1_light_no005_s1a,
						n, [],
							n, null, [],									
								n, [], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													n, null, [null], null, null, [],
														{do_not_need_select, 0, [{move, to_remove_zone}]}, end_of_subturn_if_not_use,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-à¸—à¸³à¸¥à¸²à¸¢ Mystic Card 1 à¹?à¸?à¹?à¸?à¸ªà¸?à¸²à¸¡ à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸?à¸?à¸±à¸? [Light] (Mp 2)
		{card_skill,
			s1_light_no008_s1, 264, 1, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{combine, {elem, 16694}}], 											
									y, null, [arena_zone], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [],	null,										
												n, [], null, 
													y, null, [arena_zone], mystic, n, [],
														{player_select_exact_target, 1, [{action, move_to_shrine}]}, 0,
															n, null, [null], null, null, [],
																[], null
		},
		%[Skill]â€“à¸?à¸³ Mystic Card 1 à¹?à¸?à¹?à¸? Shrine à¸?à¸¹à¹?à¹?à¸?à¹? Skill à¸­à¸­à¸?à¸?à¸²à¸?à¹€à¸?à¸¡ à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (Mp 1)
		{card_skill,
			s1_light_no010_s1, 266, 1, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{combine, y}], 											
									y, owner, [shrine_cards], mystic, n, [], 1,			                        
										n, [], null,
											n, null, [],	null,										
												n, [], null, 
													y, owner, [shrine_cards], mystic, n, [],
														{player_select_exact_target, 1, [{action, to_remove_zone}]} ,null,
															n, null, [null], null, null, [],
																[], null
		},
		%[Skill]-à¸£à¸±à¸?à¸©à¸² Curse 1 à¸?à¸?à¸´à¸”à¹?à¸«à¹?à¸?à¸±à¸? Seal 1 à¹?à¸? (Mp 1)
		{card_skill,
			s1_light_no013_s1, 269, 1, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [{curse, y}], 1,			                        
										n, [], null,
											n, null, [],	null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{curse, y}],
														{player_select_exact_target, 1, [{heal_curse, {player_select_exact_curse, 1}}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-à¸£à¸±à¸?à¸©à¸² Curse 1 à¸?à¸?à¸´à¸”à¹?à¸«à¹?à¸?à¸±à¸? Seal à¸—à¸¸à¸?à¹?à¸?à¹?à¸?à¸ªà¸?à¸²à¸¡ à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (Mp 3)
		{card_skill,
			s1_light_no013_s2, 269, 2, n,
				y, 
					null, null,
						n, [],
							n, null, [],									
								y, [{combine, y}], 											
									y, null, [arena_zone], seal, y, [{curse, y}], 1,			                        
										n, [], null,
											n, null, [],	null,										
												n, [], null, 
													y, null, [null], seal, y, [{curse, y}],
														{do_not_need_select, 0, [{heal_curse, {player_select_exact_curse, 1}}]} ,0,
															n, null, [null], null, null, [],
																[], null
		}
	].
	
earth_skill() ->
	[
		%[Skill]-à¸—à¸³à¸¥à¸²à¸¢ Seal à¸—à¸µà¹?à¸•à¸´à¸” Stone Curse 1 à¹?à¸? (At Line) (Mp 3)
		{card_skill,
			s1_earth_no016_s1, 272, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{curse, stone_curse}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{curse, stone_curse}],
														{player_select_exact_target, 1, [{action, move_to_shrine}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal à¹?à¸?à¸­à¸·à¹?à¸? 1 à¹?à¸? +Df à¸•à¸²à¸¡ Mp à¸?à¹?à¸²à¸£à¹?à¸²à¸¢à¸?à¸­à¸? Seal à¸?à¸±à¹?à¸?à¸?à¸?à¸?à¸? Subturn ï?¾(Mp 2)
		{card_skill,
			s1_earth_no017_s1, 273, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, n, [],
														{player_select_exact_target, 1, [{df, '+Q'}]}, end_of_subturn,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Sp 1, 2, 3, 4 à¸•à¸´à¸” Stone Curse à¹?à¸¥à¸° Poison Curse 2 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (At Line) (Mp 3)
		{card_skill,
			s1_earth_no018_s1, 274, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}, {line, 1}], 											
									y, null, [arena_zone], seal, y, [{speed, "1234"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{speed, "1234"}],
														{player_select_exact_target, 1, [{curse, stone_curse}, {curse, freeze_curse}]}, 4,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 à¹?à¸?à¸•à¸´à¸” Dimension Curse 1 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸?à¸?à¸±à¸? [Light] (Mp 3)
		{card_skill,
			s1_earth_no020_s1, 276, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, {elem, 16694}}], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{curse, dimension_curse}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 à¹?à¸?à¸?à¹?à¸­à¸?à¸?à¸±à¸? Curse 1 Turn (Mp 1)
		{card_skill,
			s1_earth_no029_s1, 285, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{protect_curse, [all]}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		}
	].

fire_skill() ->
	[
		%[Skill]â€“Sacrifice Seal 1 à¹?à¸?; 
		{card_skill,
			s1_fire_no031_s1, 287, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{action, sacrifice}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%Seal à¸—à¸¸à¸?à¹?à¸?à¸?à¹?à¸²à¸¢à¸?à¸¹à¹?à¹?à¸?à¹? Skill At +1 à¸?à¸?à¸?à¸? Subturn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (At Line) (Mp 1) 
		{card_skill,
			s1_fire_no031_s2, 287, 2, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}, {line, 1}], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [arena_zone], seal, y, [],
														{do_not_need_select, 0, [{at, '+1'}]}, end_of_subturn,
															n, null, [null], null, null, [],
																[], null
		},
		%[Skill]-Sacrifice Seal 1 à¹?à¸?;   
		{card_skill,
			s1_fire_no035_s1, 291, 1, n,
				y, 
					s1_fire_no035_s2, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{action, sacrifice}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%Seal 1 à¹?à¸? +At à¸•à¸²à¸¡ Mp à¸?à¹?à¸²à¸£à¹?à¸²à¸¢à¸?à¸­à¸? Seal à¸—à¸µà¹? Sacrifice 1 Turn (Mp 2) 
		{card_skill,
			s1_fire_no035_s2, 291, 2,
				y, 
					null, s1_fire_no035_s1, n,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{at, '+R'}]}, 2 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 à¹?à¸? At +1 à¸?à¸?à¸?à¸? Subturn (Mp 1)
		{card_skill,
			s1_fire_no041_s1, 297, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{action, '+1'}]}, end_of_subturn, 
															n, null, [null], null, null, [],
																[] ,null
		},
		%Seal 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Sp 3, 4, 5 à¸•à¸´à¸” Last Dance Curse At + 3 / 2 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸?à¸?à¸±à¸? [Dark] (At Line) (Mp 2)
		{card_skill,
			s1_fire_no043_s1, 299, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, {elem, 16693}}, {line, 1}], 											
									y, null, [arena_zone], seal, y, [{speed, "345"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{speed, "345"}],
														{player_select_exact_target, 1, [{curse, last_dance_curse}]}, 4, 
															n, null, [null], null, null, [],
																[] ,null
		}
	].

water_skill() ->
	[
		%[Skill]-à¸?à¸³ Seal à¸—à¸µà¹?à¸•à¸´à¸” Freeze Curse 1 à¹?à¸?à¸?à¸¶à¹?à¸?à¸¡à¸·à¸­ (At Line) (Mp 1)
		{card_skill,
			s1_water_no048_s1, 304, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{curse, freeze_curse}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, [], null, 
													y, null, [arena_zone], seal, y, [{curse, freeze_curse}],
														{player_select_exact_target, 1, [{action, move_to_hand}]}, 0 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]â€“Seal 1 à¹?à¸?à¹?à¸?à¸ªà¸?à¸²à¸¡ Mp à¸?à¹?à¸²à¹?à¸?à¹? Skill +1 / 1 Turn (Mp 1)  
		{card_skill,
			s1_water_no052_s1, 308, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{ms, '+1'}]}, 2 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-à¸—à¸´à¹?à¸? [Machine] 1 à¹?à¸?à¹?à¸?à¸¡à¸·à¸­à¸?à¸¹à¹?à¹?à¸?à¹? Skill; 
		{card_skill,
			s1_water_no054_s1, 310, 1,
				y, 
					s1_fire_no054_s2, null,	n,
						n, [],
							n, null, [],									
								n, [], 											
									y, owner, [hand_cards], seal, null, [{type, 17251}], 1,			                        
										y, [{1, action, 'SZ9'}], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [hand_cards], seal, null, [{type, 17251}],
														{player_select_exact_target, 1, [{action, move_to_shrine}]}, 0 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%à¸?à¸¹à¹?à¹?à¸?à¹? Skill + Mp à¸•à¸²à¸¡ Mp à¸?à¹?à¸²à¸£à¹?à¸²à¸¢ à¸?à¸­à¸? [Machine] à¹?à¸?à¸?à¸±à¹?à¸? (Mp 0)
		{card_skill,
			s1_water_no054_s2, 310, 2,
				y, 
					null, s1_fire_no054_s1,	n,
						n, [],
							n, null, [],									
								n, [], 											
									n, null, [null], null, null, [], null,			                        
										y, {do_not_need_select, 0, [{mp, '+R'}]}, 0,
											n, null, [], null,										
												n, [], null, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null 
		},
		%[Skill]-à¸?à¸³ Seal 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Lv 1 à¹€à¸?à¹?à¸²à¸¡à¸²à¹?à¸?à¸ªà¸?à¸²à¸¡à¸?à¸²à¸?à¸¡à¸·à¸­à¸?à¸¹à¹?à¹?à¸?à¹? Skill (Mp 1)
		{card_skill,
			s1_water_no055_s1, 311, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, owner, [hand_cards], seal, null, [{level, 1}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [hand_cards], seal, null, [{level, 1}],
														{player_select_exact_target, 1, [{action, move_to_arena}]}, 0 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]â€“Seal 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Sp 2, 3, 4 à¸•à¸´à¸” Poison Curse 1 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸?à¸?à¸±à¸? [Dark] (At Line) (Mp 2)
		{card_skill,
			s1_water_no057_s1, 313, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, {elem, 16693}}], 											
									y, null, [arena_zone], seal, y, [{speed, "234"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{speed, "234"}],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 2 ,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]â€“à¸?à¸¹à¹?à¹?à¸?à¹? Skill à¸ªà¸±à¹?à¸? [S] à¹?à¸¢à¸?à¸?à¸²à¸£à¸£à¸§à¸¡à¸£à¹?à¸²à¸? ï?¾ (Mp 2)
		{card_skill,
			s1_water_no058_s1, 314, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}], 											
									n, null, [null], null, null, [], null,			                        
										y, {do_not_need_select, 0, [{action, assign_s_breack_combine}]}, 0,
											n, null, [], null,										
												n, [], null, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null 
		},
		%[Skill]â€“Seal 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Sp 3, 4 à¸•à¸´à¸” Freeze Curse 2 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (At Line) (Mp 2)
		{card_skill,
			s1_water_no060_s1, 316, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}, {line, 1}], 											
									y, null, [arena_zone], seal, y, [{speed, "34"}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{speed, "34"}],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, 4,  
															n, null, [null], null, null, [],
																[] ,null
		}
	].
	
wind_skill() ->
	[
		%[Skill]â€“Seal 1 à¹?à¸?à¹?à¸?à¸ªà¸?à¸²à¸¡ Mp +1 / 1 Turn (Mp 0) 
		{card_skill,
			s1_wind_no062_s1, 318, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, null, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{curse, freeze_curse}]}, 2,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-Seal 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Df à¸?à¹?à¸­à¸¢à¸?à¸§à¹?à¸² [S] à¸ªà¸²à¸¡à¸²à¸£à¸–à¹?à¸?à¸¡à¸•à¸µà¸?à¹?à¸²à¸¡à¹?à¸?à¸¢à¸±à¸? Df Line à¹?à¸”à¹?à¸?à¸?à¸?à¸? Subturn (At Line) (Mp2)
		{card_skill,
			s1_wind_no064_s1, 320, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{defend, less_than_s}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{defend, less_than_s}],
														{player_select_exact_target, 1, [{at, to_df}]}, end_of_subturn,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]- [S] à¹?à¸¥à¸° Seal 1 à¹?à¸?à¸?à¹?à¸²à¸¢à¸?à¸¹à¹?à¹?à¸?à¹? Skill à¹€à¸?à¸¥à¸µà¹?à¸¢à¸? Line ï?¾ (Mp3) (à¸?à¸¥à¸?à¸²à¸? Skill  à¸?à¸µà¹?à¹?à¸¡à¹?à¸?à¸±à¸?à¸§à¹?à¸²à¹€à¸?à¹?à¸?à¸?à¸²à¸£à¸?à¸³à¸«à¸?à¸” Line)
		{card_skill,
			s1_wind_no064_s2, 320, 2, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								n ,[], 											
									y, owner, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{action, change_line}]}, 0,  
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-à¸?à¸³ Seal 2 à¹?à¸?à¹?à¸?à¸ªà¸?à¸²à¸¡à¸—à¸µà¹?à¸¡à¸µ Sp à¸?à¹?à¸­à¸¢à¸?à¸§à¹?à¸² [S] à¹?à¸?à¸—à¸µà¹? At Line (At Line) (Mp3)(à¸?à¸¥à¸?à¸²à¸? Skill  à¸?à¸µà¹?à¹?à¸¡à¹?à¸?à¸±à¸?à¸§à¹?à¸²à¹€à¸?à¹?à¸?à¸?à¸²à¸£à¸?à¸³à¸«à¸?à¸” Line)
		{card_skill,
			s1_wind_no065_s1, 321, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{speed, less_than_s}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{speed, less_than_s}],
														{player_select_exact_target, 2, [{action, to_at_line}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-à¹€à¸¡à¸·à¹?à¸­à¸?à¸¹à¹?à¹€à¸¥à¹?à¸?à¸?à¹?à¸²à¸¢à¸•à¸£à¸?à¸?à¹?à¸²à¸¡à¸ªà¸±à¹?à¸? Seal à¸£à¸§à¸¡à¸£à¹?à¸²à¸? à¸?à¸³ [S] à¹€à¸?à¹?à¸²à¸¡à¸²à¸—à¸µà¹? At Line à¸?à¸²à¸?à¸¡à¸·à¸­ à¸?à¸²à¸?à¸?à¸±à¹?à¸?à¸ªà¸±à¹?à¸? [S] à¹?à¸?à¸¡à¸•à¸µ Seal à¸—à¸µà¹?à¸?à¸³à¸¥à¸±à¸?à¸£à¸§à¸¡à¸£à¹?à¸²à¸? ï?¾ (Mp 4)
		{card_skill,
			s1_wind_no066_s1a, 322, 1, y,
				y, 
					s1_wind_no066_s1b, null,	
						n, [],
							y, opponent, [{action, assign_combine}],									
								y, [{zone, [hand_cards]}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null, 
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, move_to_at_line}]}, 0,
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null  
		},
		{card_skill,
			s1_wind_no066_s1b, 322, 1, y,
				y, 
					null, s1_wind_no066_s1a,	
						n, [],
							n, null, [],									
								n, [], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, opponent, [arenaz_zone], seal, null, [{action, being_combine}],
														{player_select_exact_target, 1, [{action, target_to_attack}]}, 0,
															n, null, [null], null, null, [],
																[], null  
		},
		%[Skill]â€“Seal 1 à¹?à¸?à¸?à¹?à¸²à¸¢à¸?à¸¹à¹?à¹?à¸?à¹? Skill à¹€à¸?à¸¥à¸µà¹?à¸¢à¸? Line à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸?ï?¾ (Mp 3) (à¸?à¸¥à¸?à¸²à¸? Skill  à¸?à¸µà¹?à¹?à¸¡à¹?à¸?à¸±à¸?à¸§à¹?à¸²à¹€à¸?à¹?à¸?à¸?à¸²à¸£à¸?à¸³à¸«à¸?à¸” Line)
		{card_skill,
			s1_wind_no067_s1, 323, 1, y,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, y}], 											
									y, owner, [arena_zone], seal, y, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [arena_zone], seal, y, [],
														{player_select_exact_target, 1, [{action, change_line}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]-à¸ªà¸±à¹?à¸? [S] à¹?à¸?à¸¡à¸•à¸µ 2 à¸?à¸£à¸±à¹?à¸?
			%-	à¸?à¸£à¸±à¹?à¸?à¸—à¸µà¹? 1 At = 9 
			%-	à¸?à¸£à¸±à¹?à¸?à¸—à¸µà¹? 2 At à¸?à¸?à¸•à¸´à¸?à¸­à¸? [Dragon] à¸—à¸µà¹?à¹€à¸?à¹?à¸? Seal  à¹?à¸?à¸£à¸­à¸?à¸£à¸§à¸¡à¸£à¹?à¸²à¸?à¸?à¸­à¸? [S] 
		{card_skill,
			s1_wind_no068_s1, 324, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{combine, {type, 17220}}], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{at1, '=9'}, {at2, '=S'}]}, 0, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null  
		},
		%[Skill]-à¸—à¸³à¸¥à¸²à¸¢ Seal à¸—à¸µà¹?à¹?à¸¡à¹?à¹?à¸”à¹?à¸£à¸§à¸¡à¸£à¹?à¸²à¸? 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Lv1 (At Line) (Mp 3)
		{card_skill,
			s1_wind_no069_s1, 325, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, null, [arena_zone], seal, y, [{combine, n}, {level, 1}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{combine, n}, {level, 1}],
														{player_select_exact_target, 1, [{action, move_to_shrine}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		}
	].

dark_skill() ->
	[
		%[Skill]- [S] +At à¸•à¸²à¸¡à¸?à¸³à¸?à¸§à¸? [Dark] à¹?à¸? Shrine à¸?à¸¹à¹?à¹?à¸?à¹? Skill à¸?à¸?à¸?à¸? Subturn à¸?à¸²à¸?à¸?à¸±à¹?à¸?à¸ªà¸±à¹?à¸? [S] à¹?à¸?à¸¡à¸•à¸µ (At Line) (Charge 2) (Mp 3)
		{card_skill,
			s1_dark_no077_s1a, 333, 1, n,
				y, 
					s1_dark_no077_s1b, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									y, owner, [shrine_cards], seal, null, [{elem, 16693}], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{at, '+S'}]}, end_of_subturn, 
													n, null, [null], null, null, [],
														[] ,null,
															n, null, [null], null, null, [],
																[], null
		},
		{card_skill,
			s1_dark_no077_s1b, 333, 1, n,
				y, 
					null, s1_dark_no077_s1a,	
						n, [],
							n, null, [],									
								n, [], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, assign_attack}]}, 0, 
													n, null, [null], null, null, [],
														[] ,null,
															n, nul, [null], null, null, [],
																[], null
		},
		%[Skill] â€“ Seal 2 à¹?à¸?à¸•à¸´à¸” Poison Curse 2 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (At Line) (Mp 4)
		{card_skill,
			s1_dark_no078_s1, 334, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [], 2,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [null], seal, y, [],
														{player_select_exact_target, 2, [{curse, poison_curse}]}, 4,
															n, nul, [null], null, null, [],
																[] ,null
		},
		%[Skill]â€“à¸—à¸³à¸¥à¸²à¸¢ Seal  à¸—à¸µà¹?à¸•à¸´à¸” Curse 1 à¹?à¸? à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (At Line) (Mp 3) 
		{card_skill,
			s1_dark_no079_s1, 335, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{curse, y}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{curse, y}],
														{player_select_exact_target, 1, [{action, move_to_shrine}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		%[Skill]â€“à¸?à¸³ Mystic Card à¸?à¸?à¸´à¸” PS 1 à¹?à¸?à¹?à¸? Shrine à¹€à¸£à¸²à¸¡à¸²à¸•à¸´à¸”à¸—à¸µà¹? [S] à¹€à¸¡à¸·à¹?à¸­ Mystic Card à¸?à¸±à¹?à¸?à¸•à¸? Shrine à¸?à¸³ Mystic Card à¸?à¸±à¹?à¸?à¸­à¸­à¸?à¸?à¸²à¸?à¹€à¸?à¸¡ (Mp 2) 
		{card_skill,
			s1_dark_no081_s1a, 337, 1, n,
				y, 
					s1_dark_no081_s1b, null,	
						n, [],
							n, null, [],									
								n, [], 											
									y, owner, [shrine_cards], mystic, null, [{paste_type, 1}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, owner, [shrine_cards], mystic, null, [{paste_type, 1}],
														{player_select_exact_target, 1, [{action, attach_to_s}]}, 0,
															n, null, [null], null, null, [],
																[] ,null
		},
		{card_skill,
			s1_dark_no081_s1b, 337, 1, n,
				y, 
					null, s1_dark_no081_s1a,	
						n, [],
							n, null, [],									
								n, [], 											
									n, null, [null], null, null, [], null,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													n, null, [null], null, null, [],
														{do_not_need_select, 0, [{move, to_remove_zone}]}, result_to_shrine,
															n, null, [null], null, null, [],
																[], null
		},
		%[Skill]â€“Seal 1 à¹?à¸? à¹?à¸¥à¸° [S] à¸•à¸´à¸” Poison Curse 1 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (At Line) (Mp3)
		{card_skill,
			s1_dark_no084_s1, 340, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, n, [], 1,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{curse, poison_curse}]}, 2, 
													y, null, [arena_zone], seal, n, [],
														{player_select_exact_target, 1, [{curse, poison_curse}]}, 2,
															n, null, [null], null, null, [],
																[] , null
		},
		%[Skill]-Seal à¸—à¸µà¹?à¹?à¸¡à¹?à¹?à¸?à¹? [Light] 1 à¹?à¸?à¸—à¸µà¹?à¸¡à¸µ Sp 1, 2, 3, 4, 5 à¸•à¸´à¸” Charm Curse 1 Turn à¹€à¸¡à¸·à¹?à¸­ [S] à¸£à¸§à¸¡à¸£à¹?à¸²à¸? (At Line) (Mp 2)
		{card_skill,
			s1_dark_no085_s1, 341, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}, {combine, y}], 											
									y, null, [arena_zone], seal, y, [{speed, "12345"}, {elem, {n, 16694}}], 1,			                        
										n, [], null,
											n, null, [], null,										
												n, [], null, 
													y, null, [arena_zone], seal, y, [{speed, "12345"}, {elem, {n, 16694}}],
														{player_select_exact_target, 1, [{curse, charm_curse}]}, 2,
															n, null, [null], null, null, [],
																[] , null
		},
		%[Skill] â€“ à¸ªà¸±à¹?à¸? [S] à¹?à¸?à¸¡à¸•à¸µ 3 à¸?à¸£à¸±à¹?à¸?à¹?à¸”à¸¢à¹?à¸¡à¹?à¸•à¹?à¸­à¸?à¸?à¹?à¸²à¸¢ Mp à¸?à¹?à¸²à¹?à¸?à¸¡à¸•à¸µ (At Line) (Charge3) (Mp 3)
		{card_skill,
			s1_dark_no086_s1, 342, 1, n,
				y, 
					null, null,	
						n, [],
							n, null, [],									
								y, [{line, 1}], 											
									n, null, [null], null, n, [], null,			                        
										n, [], null,
											n, null, [], null,										
												y, {do_not_need_select, 0, [{action, triple_attack_without_cost}]}, 0, 
													n, null, [null], null, null, [],
														[], null,
															n, null, [null], null, null, [],
																[], null
		}
	].
test() ->	
	[{card_skill, 
			skill_id, card_id, skill_no, can_interfere,
				skill_condition_need_check, 
					then_assign, then_do,
						playerown_must_check, playerown_check,
							player_must_check, player_side_check, player_check,									
								owner_must_check, owner_check, 											
									other_must_check, other_player_check, other_present_check, other_card_type_check, other_self_include_check, other_check, other_match_count,			                        
										playerown_have_effect, playerown_effect, playerown_duration_effect,
											player_have_effect, player_which_got_effect, player_effect,	player_duration_effect,										
												owner_have_effect, owner_effect, owner_duration_effect, 
													other_target_have_effect, target_player_check, target_present_check, target_card_type_check, target_self_include_check, target_check,
														other_effect ,other_duration_effect,
															or_target_have_effect, or_target_player_check, or_target_present_check, or_target_card_type_check, or_self_include_check, or_check,
																or_result_effect, or_duration
			}].
	
